### ISSUE TITLE
Collapse/hide content in details tiles

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1006]
Like what was done on issue #749 it would be useful to have the same ability to hide much of the data in the details tile of a contact and group. There are times when sensitive data is listed in the details tile and it doesn't need to be viewed. Much of the info in this tile is important but also doesn't need to be viewed most of the time. Especially in mobile view when screen space is limited, is it more needed to have collapsible tiles.

**Comment by corsacca** [comment]
Note: We don't want to hide the status, assigned to and subassigned field.

**Comment by mikeallbutt** [comment]
The attached image shows how a normally filled out contact record looks when in mobile view - very long. This is a reason that having collapsable tiles would aide the user.

![long-contact-mobile-view](https://user-images.githubusercontent.com/43966676/91513426-ec4fef00-e8a9-11ea-8e56-e4207eb35f4a.png)

**Comment by corsacca** [comment]
Implemented in v1.
