### ISSUE TITLE
Indicate inactive contacts & groups in fields in tiles

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1008]
When there are people (and groups) in a field, they are all displayed the same, making it hard for the user to distinguish which contact is active, paused, closed etc.

One possible and simple way to help identify the differences would be to have the word and box around the name be a different colour.

**Comment by corsacca** [comment]
@mikeallbutt please provide these details:
- which fields
- what extra data to display
- how the data could be displayed.

**Comment by mikeallbutt** [comment]
> @mikeallbutt please provide these details:
> 
> * which fields

- Contact > Connections tile fields - Groups, Relation, Baptised by, Baptised who, Coached by, Coached who.
- Group > Groups tile - Parent, peer, child
- Group > Member list tile - member

> * what extra data to display

No extra data - just styling to indicate the difference in the statuses.

Possibly just a dot (like what the app currently has) that is the colour of their status. Green - active, Red - inactive, Orange - paused.

But better and easier might be to have the border changed for the class typeahead__label to a different color:
from #c2e0ff to 
active: green #4CAF50
inactive: grey #999999 (or red #F43636)
paused: orange #FF9800

> * how the data could be displayed.

As described previously.

![Screenshot 2020-07-19 15 35 21](https://user-images.githubusercontent.com/43966676/87884671-8b451980-c9d5-11ea-8f32-59e50e334f01.png)

**Comment by mikeallbutt** [comment]
The members list could have a different coloured icon.

![Screenshot 2020-07-19 15 50 20](https://user-images.githubusercontent.com/43966676/87884964-af095f00-c9d7-11ea-85a7-ffa876484523.png)

**Comment by mikeallbutt** [comment]
> The members list could have a different coloured icon.
> 
> ![Screenshot 2020-07-19 15 50 20](https://user-images.githubusercontent.com/43966676/87884964-af095f00-c9d7-11ea-85a7-ffa876484523.png)

What do you think of this concept? @ahillbilly and @corsacca

**Comment by ahillbilly** [comment]
This is super helpful with the additional explanation. My only comment would be to keep consistency between the color used in this display and the color used in the status display. 

Also, I think closed contacts names are already greyed out in the type-ahead, but this would further add clarity as long as the colors don't add too much noise.

**Comment by mikeallbutt** [comment]
@ahillbilly yes the colours would be the same as the `Status` colors. The same idea would be useful to be added to the Contact List / Groups List pages.

**Comment by corsacca** [comment]
Option:
![image](https://user-images.githubusercontent.com/24901539/113032651-fd3a4900-9187-11eb-9319-fa523468a0e8.png)
