### ISSUE TITLE
Prevent linking a contact/group to itself

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1011]
When making connections, the contact that is being worked on has itself available in the type-ahead list that it can be connected to. This issue is seen in all the fields that offer who to connect with.

The same happens for groups. eg. It is currently possible to assign the parent group of the group being edited because the current group is available/offered in the suggested type-ahead list.

**Comment by corsacca** [comment]
I agree, in some fields it would be better to not display the current record as an option.
In some fields it needs to be available like baptisms, subassigns, etc.

**Comment by corsacca** [comment]
Currently a typeahead will not suggest itself.
