### ISSUE TITLE
The word "of" not being translated on record list pages

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1013]
At the top of a record list page (for contacts and groups) in English it says "of" eg. "Showing 100 of 540" but when you switch another language such as Spanish, it still uses the word "of" and not the Spanish translation "de" eg. "Mostrando 100 de 540".

![Screenshot 2020-07-12 07 30 10](https://user-images.githubusercontent.com/43966676/87246314-438d2380-c412-11ea-8d77-619a98f2be20.png)
![Screenshot 2020-07-12 07 30 50](https://user-images.githubusercontent.com/43966676/87246315-44be5080-c412-11ea-8ff0-afa130006dd8.png)

**Comment by corsacca** [comment]
@mikeallbutt Please check the translation of `Showing _START_ of _TOTAL_`  in Spanish in poeditor.
Made sure `of` is also translated.
