### ISSUE TITLE
Group status set to inactive when being created.

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1015]
When a group is created, it would be better if the status was set to be "inactive" so that it doesn't get an "End Date" set when it is changed to inactive. A newly created entry for a group that gets adjusted to being inactive will then leave a group end date, that then needs to be removed once the group starts (and is no great/accurate for metrics).

By default there is a "pre-group" type which is described as "A group predominantly of non-believers." but it could be possible to use this group type (or create a custom group type) to plan new groups - ones that are proposed.

By having the status option available when the create new group modal/page is displayed, will allow the DT user to set whatever status they desire.

**Comment by corsacca** [comment]
The intended workflow is for the user to create a group record when a group has formed in real life. And the group to then become a church. If the group is no longer meeting the group record is then set to inactive with an end date.

Creating the groups as "inactive" would add extra steps to the intended workflow as the user would need to remember to set the group to active each time.

We could explore more options in how a group is created and include the status field. See https://github.com/DiscipleTools/disciple-tools-theme/issues/762

Planned group sessions sound a lot like trainings. Have you explored the trainings plugin? https://github.com/DiscipleTools/disciple-tools-training. It might fit your workflow better.

**Comment by mikeallbutt** [comment]
You are describing one workflow but it is not the only workflow. The simplest way is ofer the "status" field to be set on creation of a group. Default stays as active but can be set to inactive in the case where this is preferred.

After trying it, in its current form, the trainings plugin is not a good/right solution.

**Comment by corsacca** [comment]
All fields are now available in the create form.
