### ISSUE TITLE
WP Admin: Available Translation list modifiable

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1016]
DT has a growing list of translations but many instances will only need to offer it in a few languages. It would be helpful to have a setting area in WP Admin when what languages are offered to be used to custom translate strings.

**Comment by mikeallbutt** [comment]
The image shows the current long list of languages DT offers. Not all need to be offered for translation for most installations.

![Screenshot 2020-07-14 11 36 03](https://user-images.githubusercontent.com/43966676/87452155-7d9f2680-c5c6-11ea-9a51-e9ab050220d8.png)

**Comment by corsacca** [comment]
Alternative: have a "show more" to expand languages not with no custom translations.

**Comment by mikeallbutt** [comment]
> Alternative: have a "show more" to expand languages not with no custom translations.

But if you do that, it will still offer the full list pretty much every time you have none translated.

**Comment by corsacca** [comment]
This is in the WP Admin area and will be seldom used by users. As in you set it once and then leave it. 
I'm recommending we don't divert energy to this one.
