### ISSUE TITLE
Using the same tags for site wide - for contacts and groups

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1017]
DT has the ability to add tags to a contact #484 and for groups #710 and often the same tag would be used. It would be useful to not duplicate the tag list and just use the same list of tags in all areas of the DT instance where tags can be used.

**Comment by corsacca** [comment]
Implemented: https://github.com/DiscipleTools/disciple-tools-theme/pull/1020
