### ISSUE TITLE
Plugin Request: Church Health using 12 functions (not the 9)

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1018]
Some groups use 12 distinctives for church health. Having this option would be useful.

<img width="586" alt="Screenshot 2020-07-14 10 04 19" src="https://user-images.githubusercontent.com/43966676/87442365-d4eaca00-c5b9-11ea-8e30-1b59fe027021.png">

This 1 minute video explains them.
https://youtu.be/22fu1d-L7XA

**Comment by micahmills** [comment]
Our teams use similar 12 elements of a healthy church, I think this would probably be a good opportunity to have this in a plugin to add this functionality.

**Comment by mikeallbutt** [comment]
> Our teams use similar 12 elements of a healthy church, I think this would probably be a good opportunity to have this in a plugin to add this functionality.

I think using a plugin would be ideal. That way others can copy the plugin or have a plugin that is customizable to set up what they want to track for group health - including choosing their icons.

**Comment by prykon** [comment]
I can give this a stab.

**Comment by prykon** [comment]
Prototype complete... now working on CSS.
Preview here: [https://github.com/prykon/custom-church-health-plugin](https://github.com/prykon/custom-church-health-plugin)

**Comment by prykon** [comment]
@mikeallbutt @micahmills I'm going to need a list of all the potential titles for the labels so I can search for the icons. Thanks!

**Comment by mikeallbutt** [comment]
The 12 functions of the church as seen in Acts 2:36-47 are:

1. Gospel
2. Repent
3. Baptism
4. Holy Spirit
5. God’s word
6. Love
7. Lord’s supper
8. Prayer
9. Signs & wonders
10. Giving
11. Worship
12. Make disciples

**Comment by prykon** [comment]
Plugin is live!
https://disciple.tools/plugins/custom-group-health/

**Comment by micahmills** [comment]
Good work @prykon
