### ISSUE TITLE
Translate add members info above the dropdown: Showing {} items

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1022]
Other than English, when adding a member using the add member modal, the phrase is in English and not the chosen language for the DT user. 

**Showing** 20 **items**

![Screenshot 2020-07-16 20 51 24](https://user-images.githubusercontent.com/43966676/87740093-f52bac00-c7a6-11ea-9d06-587d6cbdd26f.png)

**Comment by corsacca** [comment]
This issue is fixed.
