### ISSUE TITLE
Set description for fields and field options from the wp-admin field settings

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1023]
DT allows for the creation of custom group types but needs a field to  write a description. When there is no description it displays empty in the information modal.

![Screenshot 2020-07-16 21 09 13](https://user-images.githubusercontent.com/43966676/87740947-04135e00-c7a9-11ea-9508-0355186043d1.png)

The fields need to be translatable too.

![Screenshot 2020-07-16 21 08 19](https://user-images.githubusercontent.com/43966676/87740956-0970a880-c7a9-11ea-84d4-50b406d07180.png)

This where the description fields need to be accessed. It would be ideal to have access to the default field descriptions too.

![Screenshot 2020-07-16 21 14 16](https://user-images.githubusercontent.com/43966676/87741191-856af080-c7a9-11ea-8204-fd6d74a8400a.png)

**Comment by corsacca** [comment]
Implemented in v1
