### ISSUE TITLE
Add missing icons to fields when create record contact & group

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1027]
At the fields for creating a contact or group, these icons are missing:

- [ ] Icon: Create New Contact > Initial Comment
- [ ] Icon: Create New Group > Group Type

**Comment by mikeallbutt** [comment]
@corsacca I @mikeallbutt would be happy to be assigned this issue.

/contacts/new
![Screen Shot 2020-09-07 at 7 31 18 am](https://user-images.githubusercontent.com/43966676/92388230-8f8bda00-f0dc-11ea-96d2-92729740e250.png)

/groups/new
![Screen Shot 2020-09-07 at 7 31 06 am](https://user-images.githubusercontent.com/43966676/92388262-9e728c80-f0dc-11ea-8dee-5565bf70aea9.png)

**Comment by corsacca** [comment]
V1 now has icons for each default field. 
Other icon considerations can be found here https://github.com/DiscipleTools/disciple-tools-theme/issues/1106
