### ISSUE TITLE
Metrics page errors when baptism data loops

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1042]
Like with issue #817 the Gen Mapper won't load when there is a loop in the baptism data.

It will break when Contact A baptizes contact B and then you say Contact B baptizes Contact A… or Contact A baptized B and B baptized C and then you say that C baptized A. 

It would be good to build a check into DT to find and/or prevent this from happening.

One way would be to exclude a person from the list of possible baptisers if they have been baptised by the same person. The same logic/function could be used in other parts of DT.

**Comment by mikeallbutt** [comment]
If you have this error, look for a contact that has the same contact set in the fields of `Baptized by` and `Baptized`. Remove the incorrect data and the loop will be fixed. ;)

PS. The same issue can happen for Coaching.

**Comment by micahmills** [comment]
So is the issue here that we need to fix the metrics page so it doesn’t error in this scenario or fix the DT fields so they can’t have this scenario selected?

**Comment by mikeallbutt** [comment]
I think @corsacca has implemented a fix to stop loops - or at least there is now info to fix the loop.

**Comment by corsacca** [comment]
:+1: There will be a message and a link to fix the issue now instead of epic crashing.
