### ISSUE TITLE
Profile Settings: Languages you are comfortable speaking 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1046]
On a users /settings/ page there is a section of Multiplier Preferences tile that permits the user to state 'Languages you are comfortable speaking' 

![Screen Shot 2020-09-05 at 9 48 33 am](https://user-images.githubusercontent.com/43966676/92307623-45c8b580-ef5d-11ea-8beb-b8612f2dfb78.png)

The choices come from /wp-admin/admin.php?page=dt_options&tab=custom-lists in the Language Options tile.
![Screen Shot 2020-09-05 at 9 48 50 am](https://user-images.githubusercontent.com/43966676/92307624-46614c00-ef5d-11ea-8200-152b35664475.png)

As can be seen, the French and German should not be being offered.

Another factor is that it is also possible to access and edit this list in Setting DT > Custom Fields > Languages. 

![Screen Shot 2020-09-05 at 9 55 46 am](https://user-images.githubusercontent.com/43966676/92307972-bc66b280-ef5f-11ea-8b2f-d3cf6045c16a.png)

**Comment by corsacca** [comment]
Thanks @mikeallbutt .
It will be fixed with: https://github.com/DiscipleTools/disciple-tools-theme/commit/ebd0d6bd419f16cc8e5a9990319c59ddeb76acb1
