### ISSUE TITLE
WP-admin: Custom Fields: New field type: textarea

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1049]
Having a `textarea` field will allow the users to add more areas to write other types of data like comments that wrap onto new/more lines.

![Screen Shot 2020-09-07 at 7 27 47 am](https://user-images.githubusercontent.com/43966676/92425387-b5e95e00-f14c-11ea-8f33-fec4e6ea95c7.png)

**Comment by corsacca** [comment]
Implemented by #1245
