### ISSUE TITLE
Configurable Quick Actions buttons

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1050]
The `Quick Actions` for a contact are ok but in some situations it would be good to be able to change the wording, icon and functionality of the list item.

One idea of what the list might have is:

Instead of it being `Contact established` (which is a one time event) it could be adjusted to `Communicated with` (this could be used to track if the user had interaction with the contact).

Another is:

`No answer` could become `Contact Attempted`.

So having access to change the wordings (and maybe icon) would be good.

It might be nice also to have a quick item that can log the type of activity.

- shared truths
- prayed with/for
- set goals

**Comment by mikeallbutt** [comment]
In the WP-admin area these wordings are adjustable.

![Screen Shot 2020-09-08 at 9 13 47 am](https://user-images.githubusercontent.com/43966676/92488031-a6e9c680-f1b3-11ea-91d3-538f5c3d1076.png)

The text can be changed but not the icon associated with it. Nor can a new quick action button be added. These two things would be good to have.

**Comment by corsacca** [comment]
The quick actions currently don't show up in the fields list.
We want to: 
- be able to change the name and icon of the quick action.
- be able to add new quick actions.

How to proceed: copy the Contact Communication Channels from WP-Admin > Settings (DT) > Custom Lists
![image](https://user-images.githubusercontent.com/24901539/104734833-1f9ff700-5741-11eb-958f-1f349d7a9c63.png)

Implement similar structure for the quick actions.
Quick actions have the property `'section'     => 'quick_buttons'`

**Comment by prykon** [comment]
I think this would be covered by the Quick Comments plugin.

**Comment by prykon** [comment]
Working on this...

**Comment by prykon** [comment]
Working on this...

**Comment by prykon** [comment]
I submitted a pull request for this. It's under review.
