### ISSUE TITLE
Contacts List: row display issue when record is in many groups

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1053]
When a contact is in many groups, the list displays all the groups and the record row is VERY high. The text vertically aligns to the center of the row which makes it hard to see who the record is related to.

I suggest that the number of groups shown is 5 and if there are more, then have `show more` type of icon link under the list in the `Groups` column for that record, that then expands to show the rest of the group names.

**Comment by corsacca** [comment]
Implemented in v1.
