### ISSUE TITLE
Users to have a system to Favorite, Star, Pin all sorts of things

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1054]
As a user there are records that I want to have quick access to. What records I want will be different to what another user needs. It needs to be done on a per user level and is a Personal Priority system for the user to aide in sorting out their records.

This data sorting could be used in the filters and dashboard or their user profile.

**Comment by micahmills** [comment]
On second look this is the same as #402 since that one is older I am going to close this issue in favor of that one. But I agree this is a good feature that we should work on.
