### ISSUE TITLE
Link a users contact record to and from their system settings user profile page

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1056]
When a user also has a contact record (the page will say`This contact represents a user.`) is viewing their /settings/ page, there should be a link to take them to their contact record from the settings page, to make it easier to update or take notes and write @mentions etc.

**Comment by corsacca** [comment]
For structure and privacy reasons most users will NOT have access to their contact record. 
These sound like good features. We can consider implementing them separately, on the profile page perhaps, or the dashboard.

**Comment by corsacca** [comment]
This is implemented
