### ISSUE TITLE
Have a place where a user can write private notes

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1057]
The users profile page could have a place where the user can makes notes that only they can see. This would be useful if there were things they wanted to remember (private/sensitive conversation) that other users need not be reading.

**Comment by micahmills** [comment]
@mikeallbutt Does the new private contact feature solve this problem

**Comment by micahmills** [comment]
Actually on further looking I think this is the same as #655. I am closing in favor of that issue
