### ISSUE TITLE
Custom Fields Icons

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1058]
Icons are often used to make is easier for the user to identify what a field is for. All of the icons are coded into the design, but if the reference to the icon was editable, then it would be possible to adjust (re-skin) the icon for the field.

If the icons were font images (emojis) then that would be easier to modify and select. The system admin would choose a font library and then assign the icon they want for that field.

**Comment by corsacca** [comment]
This issue would be resolved in by this one:
https://github.com/DiscipleTools/disciple-tools-theme/issues/1106
