### ISSUE TITLE
Choosing the username when `Make User From Contact`

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1059]
When the `Admin action` of `Make User From Contact` is invoked, 

![Screen Shot 2020-09-08 at 9 24 27 am](https://user-images.githubusercontent.com/43966676/92489354-4e1b2d80-f1b5-11ea-93e3-651e175e53cd.png)

a modal appears that gives a way to create a new user from the current contact.

![Screen Shot 2020-09-08 at 9 23 20 am](https://user-images.githubusercontent.com/43966676/92489390-570bff00-f1b5-11ea-83fe-7746283e3724.png)

Having the ability to choose the username would be helpful because at present, the email address if used username.

In WP Admin, the username and role for the contact is available to be set when creating a new user.

![Screen Shot 2020-09-08 at 9 28 46 am](https://user-images.githubusercontent.com/43966676/92489794-cbdf3900-f1b5-11ea-8912-3694d68f6203.png)

Being able to set the role (with a limited selection or roles available) might be good too.

_Originally posted by @corsacca in https://github.com/DiscipleTools/disciple-tools-theme/issues/557#issuecomment-688740928_

**Comment by cwuensche** [comment]
I'm working on and almost finished this issue. This is where I'm at so far.
<img width="604" alt="Screen Shot 2021-03-22 at 8 39 06 AM" src="https://user-images.githubusercontent.com/6157604/112016653-243eae00-8aea-11eb-8236-5a6a48113f41.png">

What do you think about all the user roles available in this list @corsacca? I removed administrator and dt_admin from the list already.

**Comment by corsacca** [comment]
Looks good.

**Comment by cwuensche** [comment]
@corsacca PR created and passed Travis CI.
