### ISSUE TITLE
Identify a contact is being a leader of a group on their contact record

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1060]
On the contacts' record, have a place where it is shown which group they are leaders of. It could probably be placed in the `Groups` field of the `Connections tile` and display it as an added icon (footprint) to the name of the group if they are leading it.

_Originally posted by @ahillbilly in https://github.com/DiscipleTools/disciple-tools-theme/issues/846#issuecomment-689488088_

**Comment by mikeallbutt** [comment]
Using the `faith_status` field, a user can now indicate a contact as being  a leader. What would be good is to have that indicated elsewhere where the record appears.

Maybe this could be done by makeing `bold` the name when it is in a drop down list.

**Comment by micahmills** [comment]
@mikeallbutt is this the same as #1115

**Comment by mikeallbutt** [comment]
> @mikeallbutt is this the same as #1115

@micahmills this is not the same. The other one is referring to the info being display on the group, while this one is refers to the info being display on the contacts record.

**Comment by mikeallbutt** [comment]
It would also be good to have a filter available that shows who of the contacts are leaders of groups.

**Comment by corsacca** [comment]
Now available with: https://github.com/DiscipleTools/disciple-tools-theme/commit/9c1d4e3dbeb4b2465d68d74585bbd8ad94ecfe10
