### ISSUE TITLE
Missing the clear search button in Firefox browser

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1063]
The icon and functionality to clear the search box on the list pages of groups and contacts is available in Safari and Chrome but missing from Firefox.

Safari
<img width="643" alt="Screen Shot 2020-09-12 at 2 49 11 pm" src="https://user-images.githubusercontent.com/43966676/93003803-679add00-f507-11ea-9de6-2aa74d50eb7f.png">

Chrome
![Screen Shot 2020-09-12 at 2 48 53 pm](https://user-images.githubusercontent.com/43966676/93003802-65d11980-f507-11ea-9646-e36bb93c9ee2.png)

Firefox
![Screen Shot 2020-09-12 at 2 49 27 pm](https://user-images.githubusercontent.com/43966676/93003789-4b973b80-f507-11ea-9642-036c71c88032.png)

**Comment by corsacca** [comment]
Thanks @mikeallbutt . These screenshots are super helpful!

**Comment by micahmills** [comment]
This comes from a difference in the way the Firefox has not implemented the clear button on their search input. There are possibilities of Javascript implementations of this, but it has some performance downsides for very little upside. I think we leave it as is and Firefox users just have to use the backspace to clear the input field.

**Comment by squigglybob** [comment]
I'm happy to take this one @corsacca

**Comment by squigglybob** [comment]
@corsacca does the styling of this need to align with the global search being done in #669 ?

**Comment by corsacca** [comment]
@squigglybob I don't think so, or at least not yet.
