### ISSUE TITLE
Date fields wrong timezone

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1064]
The date field stores the time as the start of the day utc. This gets converted to the previous day in other time zones: seehttps://github.com/DiscipleTools/disciple-tools-mobile-app/issues/408

**Comment by micahmills** [comment]
I looked into this a bit last night. The dates are not actually being saved at the start of the date UTC they are being saved at the start of the day for the timezone the user is in when they save the date. 

So if you save the date of October 1st in Istanbul, it saves the time stamp of 1601499600 if you save that date in San Francisco it saves the time stamp of 1601535600. 

We can fix this going forward by adding some parameters to the formatDate function and the moment.js calls (I will send in a PR shortly). But we will need to discuss what to do with past dates that are not saved at the beginning of the day UTC.

I see 2 possible solutions:
1. Leave them as they are and we will have a few cases where multi time zone teams will see things a day off.
2. On the next update run some sort of batch update that will update all the timestamps to utc. This is obviously the most complete solution, but it will take some work and I am not sure if it is worth it right now.

As a side note for anyone who might read this later. To make testing this easier you can change your timezone in Chrome without having to change your system time. See https://stackoverflow.com/a/60008052 for details.

**Comment by corsacca** [comment]
Closed by #1071
