### ISSUE TITLE
Indicate how many people have access to a record

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1065]
Sharing records helps prevent duplicate records so having a counter that informs the DT user how many people this record is shared with will help be aware if the count is low (just 1 person / them). 

The information could be displayed where these buttons are.

![Screen Shot 2020-09-16 at 3 59 52 am](https://user-images.githubusercontent.com/43966676/93316169-7caa9100-f7d1-11ea-8bf1-36be7b2b1bdc.png)

This is what Evernote has to indicate how many people have access to a note. I think it would good if DT does the same.

<img width="244" alt="Screen Shot 2020-09-15 at 5 52 49 am" src="https://user-images.githubusercontent.com/43966676/93315413-a3b49300-f7d0-11ea-83e5-2da517880614.png">

**Comment by corsacca** [comment]
To consider along with: https://github.com/DiscipleTools/disciple-tools-theme/issues/726

**Comment by corsacca** [comment]
This issue is a duplicate of #726
