### ISSUE TITLE
Date picker replacement

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#1067]
We have mentioned before that the jquery date picker we are using is out of date and seemingly not maintained anymore. I ran across https://github.com/duetds/date-picker as a possible replacement today.

**Comment by corsacca** [comment]
@micahmills that one looks nice.
D.T also uses a second date-picker: https://www.daterangepicker.com/. It is designed for date ranges but also can but used as a normal picker.
Since it is already included with D.T i'd like to evaluate whether it would work for all date pickers.

**Comment by micahmills** [comment]
This is working for now, we should keep it in mind for the future.

For now I am going to close this.
