### ISSUE TITLE
Indicate a group member as being inactive in that group

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1069]
Some contacts will attend a group for a while but might stop participating. What should be done with them regarding to leave them in the member count or remove them. If we want dt to have good metrics the contact should be removed but I wonder if there could be a way to set them as just being inactive and not remove them all together. Some people might be away from the group for a few months due to travel but plan to come back. That is one scenario that we could consider.

**Comment by micahmills** [comment]
I think this is the same as #1008, but I could be wrong.

**Comment by micahmills** [comment]
This is better documented in #1008 so I am going to close this issue in favor of that one.
