### ISSUE TITLE
Consideration: use a font icon library. 

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1106]
D.T uses svg icons and displays them next to field name.
Many of them come from https://thenounproject.com/

Would using a font icon library be faster and more convenient?
What happens when a icon can not be found in the library?

Libraries suggested: Font Awesome.

Requirements:
- We'd like the theme and the mobile app to be able to use the same icons.
- We'd like the user to be able to select an icon when creating a custom field
- We need to be able to display custom icons when the library does not have a good one.

**Comment by corsacca** [comment]
Notes:
The link to the icons for each field are being stored in the field declaration array.
This will enable admin users to change the icon for a field (or field values) if they want.

Location field example:
```
['location_grid'] = [
    'name'        => __( 'Locations', 'disciple_tools' ),
    'type'        => 'location',
    "icon" => get_template_directory_uri() . "/dt-assets/images/location.svg",
];
```

It is then rendered in on the front-end next to the field name
```
<?php if ( isset( $fields[$field_key]["icon"] ) ) : ?>
    <img class="dt-icon" src="<?php echo esc_url( $fields[$field_key]["icon"] ) ?>">
<?php endif;
echo esc_html( $fields[$field_key]["name"] );
```

A worthy goal for the brave will be to have this strategy also work for font icon sets.

**Comment by micahmills** [comment]
Icon fonts have some performance and accessibility issues. I think SVGs are the better solution in almost every way. The one thing icon fonts give you is the ability to let the end user select an icon from a preset list, but that has the downside of making it hard add custom stuff. 

I think that if the end goal is to make it easier for people to swap out icons we could get a large set of SVG icons (I believe Font Awesome actually offers these in their bundle) and add those in as an 'icon library' to choose from or upload your own svg if you so choose.

**Comment by corsacca** [comment]
Great feedback. Thank you @micahmills 
I like the idea of the user being able to upload an svg to use for a field icon.

**Comment by corsacca** [comment]
Exploring: Preference given to custom icons but also allows for a font library:
https://github.com/DiscipleTools/disciple-tools-theme/pull/1639

**Comment by corsacca** [comment]
The mobile app is using MaterialCommunityIcon, I wonder if the theme can use it or what the equivalent would be.

**Comment by corsacca** [comment]
https://materialdesignicons.com/ ?
