### ISSUE TITLE
Feature request: more information in group members list 

### ISSUE THREAD

**Issue by jlebouch76** [DiscipleTools/disciple-tools-theme#1112]
In the same way that you use the feet symbol to show who is the leader in a group, could you show a symbol (like maybe a vertical cross) next to each baptised contact names who are group members?  
In this way, we would quickly see who is a baptised and who is not. Right now, we have to open a tab for each group member in order to get the info. This feature is a must for a team manager who may not necessarily know each name of the people who got baptized.

**Comment by corsacca** [comment]
We would like the group members list to show more information.
Color of contact status (if available) and faith milestones.
We can start with just the baptisms faith milestone, but we want to be able to turn other milestones all (settings?) Having all the milestones enabled would probably be too much information.
