### ISSUE TITLE
List page heading for row number column

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1114]
On the records list pages it is possible to move the columns and click the icons to sort by that field/column. The #746 added number column but it has no heading nor icons to sort by that field. Adding this will allow people to move the column if so desired and also sort in reverse order.

<img width="534" alt="Screen Shot 2021-01-22 at 10 33 27 am" src="https://user-images.githubusercontent.com/43966676/105518792-4ceb2880-5c9e-11eb-8844-97dadbae9676.png">
<img width="535" alt="Screen Shot 2021-01-22 at 10 36 31 am" src="https://user-images.githubusercontent.com/43966676/105518799-4f4d8280-5c9e-11eb-9e86-398188f279fa.png">

**Comment by corsacca** [comment]
Like in excel, the number is just the number of the row. the 1st row will always be #1, so it should always be first and it can not be sorted by.
