### ISSUE TITLE
Create contact for coached by icon on mobile missing 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1116]
![Screenshot_20210124-040740.png](https://user-images.githubusercontent.com/43966676/105627040-cfd4c600-5df9-11eb-8e31-0e41be2c3d5f.png)

The icon to create a contact from the coached by field is non visible on a mobile phone browser.

When there is no info in the field, the icon is displayed.

![Screenshot_20210124-041823.png](https://user-images.githubusercontent.com/43966676/105627275-92713800-5dfb-11eb-909b-c8b9ba05c452.png)

**Comment by mikeallbutt** [comment]
The same thing happens in the other tile with the groups field of a contact record.

![Screenshot_20210124-050106.png](https://user-images.githubusercontent.com/43966676/105628233-65278880-5e01-11eb-9fb6-8158ed60aeec.png)

**Comment by corsacca** [comment]
@mikeallbutt is this not for the mobile app instead of the theme?

**Comment by mikeallbutt** [comment]
This has been fixed.
