### ISSUE TITLE
Record name often not visible mobile devices

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1118]
Once the screen is scrolled down, the name of the contact or group is no longer visible. It could be fixed by using a fixed header that always displays the name of the contact or group.

As seen in this image, there is no info about what record is being viewed etc. 

![Screenshot_20210124-043139.png](https://user-images.githubusercontent.com/43966676/105627675-d5340f80-5dfd-11eb-9a5a-c08fff515f39.png)

**Comment by micahmills** [comment]
This is addressed in PR #1129.
