### ISSUE TITLE
Details tile minimise function to hide data

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1119]
When a user clicks the arrow button on the top right of a tile, the tile minimises (or reverses the minimumise). But with the details tile, the icon opens the tile and displays all the fields that can be edited.

![Screenshot_20210124-044511.png](https://user-images.githubusercontent.com/43966676/105628078-66a48100-5e00-11eb-981c-ed227c1353ec.png)

I suggest that the minimumise icon works to show or not show the data, and have an 'edit all details'  text link in the tile (like what was available pre version 1 of DT).

There will be times when a user doesn't need to see all the details tile info, and having the tile function like the others would be good.

**Comment by corsacca** [comment]
Thank for your feedback. We prefer to have the details always visible.
