### ISSUE TITLE
All contacts number displayed in contact filters tile 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1121]
In the filter tile I would like to see displayed the number of how many contacts are in my instance. And for how many are closed/archived.

At present, most counts are displayed but not all. 

![Screenshot_20210124-052009.png](https://user-images.githubusercontent.com/43966676/105628762-6e662480-5e04-11eb-86d3-78c4bfea32cb.png)

**Comment by corsacca** [comment]
Those 2 specific queries are very resource intensive. So we chose not to implement them.
