### ISSUE TITLE
Filters should not be activated unless requested 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1122]
When using the filters in the filter tile, if I click the plus or minus icon to open or close that filter area, I might not want the first filter to be activated but instead just view the list of filters and then choose a filter.

![Screenshot_20210124-052750.png](https://user-images.githubusercontent.com/43966676/105629028-45df2a00-5e06-11eb-8f7a-8067d2432808.png)

**Comment by corsacca** [comment]
Thanks for your suggestion @mikeallbutt .
The behavior you describe was the previous behavior and it resulted in more unneeded clicks.
