### ISSUE TITLE
Missing people group item numbers

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1126]
In the user settings page, the people groups drop down list is missing the record number next to the item to help distinguish them.

Missing
![Screenshot_20210124-065731.png](https://user-images.githubusercontent.com/43966676/105631068-1cc49680-5e12-11eb-80d3-56dc72ba703d.png)

How it should be
![Screenshot_20210124-065908.png](https://user-images.githubusercontent.com/43966676/105631075-2817c200-5e12-11eb-985c-703dce40d593.png)

**Comment by corsacca** [comment]
![image](https://user-images.githubusercontent.com/24901539/110624645-c67f9d00-819e-11eb-8521-5ccc0d31bc1f.png)
This is done :)
