### ISSUE TITLE
Rearrange the order of member list items

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1128]
Have the ability in member list to manually arrange the items to be in whatever order a user prefers.

When looking at a list it is often useful to group contacts together (family members, alphabetical).

![Screenshot_20210124-071447.png](https://user-images.githubusercontent.com/43966676/105631545-99f10b00-5e14-11eb-957b-80cda2abf167.png)

**Comment by corsacca** [comment]
Hey, the overhead to saving on each group each user's ordering preference is too much hassle.
I suggest when https://github.com/DiscipleTools/disciple-tools-theme/issues/1112 and/or https://github.com/DiscipleTools/disciple-tools-theme/issues/1008 is implemented we consider a sort button for those fields.
