### ISSUE TITLE
Duplication of Extensions (DT) menu item

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1132]
The extensions menu item is replicated for a user when it is set to use the default language and not one of the installed ones of my choice.

<img width="530" alt="Screen Shot 2021-01-22 at 7 04 46 am" src="https://user-images.githubusercontent.com/43966676/105699879-a5ecd380-5ecd-11eb-9891-6d6692a420b5.png">

As noted in Slack https://disciple-tools.slack.com/archives/CDXNVC892/p1611296575007600

**Comment by micahmills** [comment]
I am not seeing this. Can you give us more info. What other plugin and extensions do you have? Is this showing for all users or just a particular user?

**Comment by corsacca** [comment]
This was caused by plugins.
I've update all our plugins, so this problem will disappear when the site will run the new version of each plugin.
