### ISSUE TITLE
Groups list page says "Sorting By: -undefined"

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1133]
The list is sorted but the info of what order is being used is not being identified and listed correctly.

![Screen Shot 2021-01-25 at 5 45 16 am](https://user-images.githubusercontent.com/43966676/105702173-016c9080-5ed1-11eb-8d56-ae48939be162.png)

**Comment by corsacca** [comment]
In testing i could not replicate this behavior.
