### ISSUE TITLE
Create new > Hide or show all fields

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1135]
When creating an record, below the main few fields there is a text link that says "Show all fields". When it is clicked, the text disappears and there is now way to hide the extra fields that are now displayed below.

![Screen Shot 2021-01-25 at 6 01 47 am](https://user-images.githubusercontent.com/43966676/105703768-57423800-5ed3-11eb-859e-b85f5dcb2b21.png)

If the "Show all fields" link area stays but swap the text to say "Hide fields" then the user can click it and not see all the extra fields.

**Comment by squigglybob** [comment]
Hi, I'm happy to take this one :)

**Comment by corsacca** [comment]
Awesome :)
