### ISSUE TITLE
Locations field not functioning well

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1139]
As seen in the included image, the locations field is not respecting the line breaks and not showing all of the information.

![Screenshot_20210127-004725.png](https://user-images.githubusercontent.com/43966676/105954074-c9349180-6039-11eb-8183-4c7cfe293106.png)

Also, there is no way to adjust the information in the location summary (where it says "new south Wales..." )

And, if you click the red mapbox icon in the location field, a drop down list opens suggesting locations, but you can not not assign something ie. The list stays open unless you choose a location.

**Comment by mikeallbutt** [comment]
There should be a better way to indicate that the locations of "new south wales, Brasil, new Mexico" are all different locations. It sort of looks they are part of the same place.

**Comment by micahmills** [comment]
How about "new south wales / Brasil / new Mexico" or new south wales - Brasil - new Mexico

**Comment by mikeallbutt** [comment]
I suggest instead they get displayed as "chips" or stones in the milestones (but much slimmer).

**Comment by corsacca** [comment]
Addressed by https://github.com/DiscipleTools/disciple-tools-theme/commit/6d3b6cd32bce5869460c8af3fd1a3e546422f958 and other commits.
