### ISSUE TITLE
Create and apply a tag directly from the tag auto-suggest list 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1145]
If you wanted to apply a tag to a record but as you typed you realised that the tag didn't yet exist, then it would be nice to be offered an option to create and apply that tag directly from the autosuggest list. The current icon to create new tags could stay but probably won't be needed too much.

![Screenshot_20210127-030517.png](https://user-images.githubusercontent.com/43966676/105968329-91831500-604c-11eb-8067-e607f8c9a86b.png)

**Comment by squigglybob** [comment]
I can take this one @corsacca
