### ISSUE TITLE
Link to record type is wrong 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1146]
Clicking on the text link where in this image says `media Record`

![Screenshot_20210127-030149.png](https://user-images.githubusercontent.com/43966676/105968471-bf685980-604c-11eb-9c66-987165c836c2.png)

Opens the modal but incorrectly has selected the first option and not `access record`. 

![Screenshot_20210127-030218.png](https://user-images.githubusercontent.com/43966676/105968667-fc345080-604c-11eb-95d1-a25370f72e44.png)

It should have chosen this instead. 

![Screenshot_20210127-030253.png](https://user-images.githubusercontent.com/43966676/105968855-37cf1a80-604d-11eb-83f2-e6a311f74788.png)

**Comment by corsacca** [comment]
Fixed with the current facebook plugin

**Comment by corsacca** [comment]
Thanks @mikeallbutt
