### ISSUE TITLE
Links from Dashboard forwarded to Settings page

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#1149]
The View View Contacts List and View All Buttons from the Dashboard plugin tiles get forwarded to /settings My guess is that is has something to do with the routes in the theme not the dashboard. The buttons are sending people to a link like `/contacts?list-tab=update_needed` but that is getting redirected to /settings.

**Comment by micahmills** [comment]
I think this was a problem because we had an old version of the Dashboard that wasn't updating.

**Comment by corsacca** [comment]
👍 The dashboard did have links to certain filters on the contacts list. V1 broke that and we removed the links,
