### ISSUE TITLE
Create new groups when creating a new contact

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1161]
When a contact is being created [/contacts/new](url) there will be times that the contact is in a group but that group does not have a record so it can't be added to the details for the contact. Being able to create a group quickly so that the field of what group the new contact is in would help the new contact record be completed on first creation and not having to go and edit the record later.

Adding the functionality that already exists on a record page should be sufficient.

**Comment by micahmills** [comment]
This could create some interesting UI problems by having fields for a new group mixed with new contact fields. Can you give us some more details on how you are envisioning this?

**Comment by mikeallbutt** [comment]
This is how the group field looks on a record page. The same add group box on the right side could be added to the group field on the new record page. 
![Screen Shot 2021-02-09 at 21 00 13](https://user-images.githubusercontent.com/43966676/107458718-3fe18c80-6b1a-11eb-966e-87af43ed1e8f.png)

This then opens the following modal.

![Screen Shot 2021-02-09 at 21 00 41](https://user-images.githubusercontent.com/43966676/107458721-407a2300-6b1a-11eb-804a-52d98870de8b.png)

**Comment by corsacca** [comment]
Good idea, but unfortunately the API only supports adding connections for existing records. The contact does not exist yet, so the group can't be added to the contact.
