### ISSUE TITLE
Don't display in admin area the Four Fields fields when it is not enabled

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1162]
On the /wp-admin/admin.php?page=dt_options&tab=general in the `Group Tile Preferences` the `Four Fields` (and `Church Metrics`) can be enabled or disabled.
If it is disabled the references to it should not appear in `Modify an existing field` on the /wp-admin/admin.php?page=dt_options&tab=custom-fields dropdown list.

The references to these fields should also not appear in places like in the `Choose a Field` list on a list page.

**Comment by corsacca** [comment]
Fixed by: https://github.com/DiscipleTools/disciple-tools-theme/commit/a92247902ff45b3ce90061df74697f965145493a
