### ISSUE TITLE
Toggle for `Active` or `Inactive` in list views

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1165]
When filters are made, it lists all the records for the chosen filter topics. Many times it is useful to be able to toggle the records to see or not see the active or inactive records, without adjust the filter. 
This functionality was available and useful pre version 1 of the theme.

**Comment by corsacca** [comment]
This was useful, but also confusing because the user did not realize that the toggle was on and was not seeing the results they expected.
A great work around is simple to sort by status.
