### ISSUE TITLE
Undo icon hover displays code and not text

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1170]
When you hover over the under icon (meeting complete for a contact record) it is incorrectly referencing something so shows code and not a normal phrase.

![Screen Shot 2021-01-30 at 10 29 32 am](https://user-images.githubusercontent.com/43966676/106624556-67918d00-653b-11eb-8eb1-f822d37ac30f.png)

**Comment by micahmills** [comment]
What should it display here?

**Comment by mikeallbutt** [comment]
> What should it display here?

I think it should display the name of the action and the word `reverse`... `"the quick action"`

All these actions have the same issue.
![quickbuttons](https://user-images.githubusercontent.com/43966676/107249030-8b037e80-69f8-11eb-8807-2c04d0c98fa3.png)


@corsacca will know because that's what it used to be previously.
