### ISSUE TITLE
Metrics menu has headings that don't function

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1172]
When signed in as a multiplier, the menu tile on the left side (as seen in the attached image) has some items (Contacts, Groups) that do not actually link to anything. They either need to be removed or be linked to a page.

![Screen Shot 2021-02-02 at 15 25 07 ](https://user-images.githubusercontent.com/43966676/106664833-37fa7900-656b-11eb-951c-87c8f9055e3b.png)

**Comment by micahmills** [comment]
Is this only the case for multipliers or are you seeing this with other user types as well?

**Comment by mikeallbutt** [comment]
> Is this only the case for multipliers or are you seeing this with other user types as well?

When signed in as an admin, the links work - so I guess the issue it only for multipliers. But I did test all types of roles and the role of strategist also has an issue that lists the first item of `Personal` but it doesn't function (has no items).

**Comment by corsacca** [comment]
Those links don't show up for me as a multipliers. Can you retest @mikeallbutt ?

**Comment by micahmills** [comment]
@mikeallbutt were you able to retest this?

**Comment by corsacca** [comment]
This was likely a passing issue. We will close for now.
