### ISSUE TITLE
The HTML & amp; symbol is showing in lists 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1176]
There are places where the & amp; symbol is showing as HTML and it should not.

- the name of a member in the group members list

![Screenshot_20210202-234023.png](https://user-images.githubusercontent.com/43966676/106703776-89792700-65b0-11eb-984d-5ed32030dbc7.png)

- drop down lists

![Screenshot_20210202-234641.png](https://user-images.githubusercontent.com/43966676/106704042-04dad880-65b1-11eb-802a-63f31479ddbe.png)

**Comment by micahmills** [comment]
I believe this is because those contact/group names were saved before we fixed the input bug. I believe that if you were to go in and rename the group using the & it would show up properly in the lists.

Basically the data was saved wrong before because of the bug and now it is showing the malformed data.

**Comment by mikeallbutt** [comment]
I have actually changed them all to fix them because they were formatted wrong previously, but still somewhere they are getting changed back. It may be the dt app so I am investigating that possability.

**Comment by micahmills** [comment]
Hey @mikeallbutt where you able to sort out if this was coming from the mobile app or from the theme?

**Comment by mikeallbutt** [comment]
> Hey @mikeallbutt where you able to sort out if this was coming from the mobile app or from the theme?

@micahmills it is from the app. I have made various adjustments in the app and it automatically changes the names of the contacts.

**Comment by corsacca** [comment]
@mikeallbutt Oh. That is good to know! 
When changing the name on the app does the `&amp;` show anywhere on the app, or just in the typeaheads on the theme?

**Comment by mikeallbutt** [comment]
After having another quick look in the app, I can't see anywhere where the HTML characters are appearing incorrectly. The app is correctly converting all & symbols.
