### ISSUE TITLE
`Gender` should not be changable from the `Your Profile` tile on the /settings/ page

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1180]

**Comment by corsacca** [comment]
@mikeallbutt please provide more detail as to the reason for the issue and the expected outcome.

**Comment by mikeallbutt** [comment]
The info in that tile of the settings page is all static and if someone wants to adjust anything they just click the `Edit` link in the top right side. This `Gender` field is the only one editable - so it seems strange to only have that one changeable without going into Edit mode.

![Screen Shot 2021-02-04 at 01 59 53 ](https://user-images.githubusercontent.com/43966676/106862697-15608100-668d-11eb-9097-7828728b98a8.png)

**Comment by mikeallbutt** [comment]
@micahmills is it possible to have the setting displayed? The gender has been set but not displaying.

![settings-gender](https://user-images.githubusercontent.com/43966676/107253888-65787400-69fc-11eb-9e8f-8eaa86bce81e.png)

![settings-edit](https://user-images.githubusercontent.com/43966676/107254181-ae302d00-69fc-11eb-8ee9-774be65517b3.png)

I suggest the order on the view is the same as the edit list. (Bio, Gender, Language)

**Comment by mikeallbutt** [comment]
There is no option to not set Gender - but should have.
