### ISSUE TITLE
WP Admin `Tiles` tab page has tile layout issues

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1183]
1. There is no space above the first tile (`Edit Tiles`) and the tabs across the top above it.
2. The `Edit Tiles` tile is full width. Instead it should allow for a right column where the `Help` tile can be located.

![Screen Shot 2021-02-04 at 02 34 44 ](https://user-images.githubusercontent.com/43966676/106866813-86eefe00-6692-11eb-8302-6a0c3d11c120.png)

As seen on:
 - OS: Mac 10.14.6
 - Browser: Firefox v85

**Comment by corsacca** [comment]
The help column is in the intended location. The gif is not needed till a post type is selected

**Comment by mikeallbutt** [comment]
Ok. As a user who hasn't used this before, it would have been helpful to have the help column with an explanation of what to do available.

This is the text I was think of adding.

![Screen Shot 2021-02-04 at 12 33 36 ](https://user-images.githubusercontent.com/43966676/106938981-453b7300-66e5-11eb-99bd-5c3548fc9bc1.png)

But I am having trouble placing the help box.

![Uploading Screen Shot 2021-02-04 at 12.35.02 .png…]()

**Comment by mikeallbutt** [comment]
There should be space under the tab like what happens on any of the other tabs.

**INCORRECT**
<img width="798" alt="Screen Shot 2021-05-14 at 12 47 00" src="https://user-images.githubusercontent.com/43966676/118309405-d6737000-b4b2-11eb-87cf-ab3d8c72c220.png">

**CORRECT - with spacing**
<img width="1108" alt="Screen Shot 2021-05-14 at 12 48 09" src="https://user-images.githubusercontent.com/43966676/118309443-e4c18c00-b4b2-11eb-9728-eddfe75d372a.png">

**Comment by corsacca** [comment]
Implemented by https://github.com/DiscipleTools/disciple-tools-theme/commit/33900d427f9c0421af0eabb954f65381b027d4e2
