### ISSUE TITLE
Bulk import of Users

### ISSUE THREAD

**Issue by trip-nine** [DiscipleTools/disciple-tools-theme#1184]
Right now we can only bulk import contacts. 

We cannot bulk import users (80 multipliers for example)

This would be a very helpful feature 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by corsacca** [comment]
@trip-nine We'd suggest looking at worpdress market place for a plugin that lets you import users according to your needs.

**Comment by micahmills** [comment]
It has been awhile since I have used this plugin but it has worked for me in the past. 

https://wordpress.org/plugins/users-customers-import-export-for-wp-woocommerce/
