### ISSUE TITLE
Admin permission to Bulk delete contacts

### ISSUE THREAD

**Issue by trip-nine** [DiscipleTools/disciple-tools-theme#1185]
Right now there is no way to bulk delete contacts. We mistakenly uploaded users as contacts, an ADMIN bulk delete function would be important to quickly resolve this issue. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by corsacca** [comment]
@trip-nine you can delete contacts in bulk from the WP ADMIN > Contacts Tab

**Comment by trip-nine** [comment]
hi @corsacca 
it looks like there is no bulk delete contacts option, rather, only a bulk edit option.. unless I am missing something..

let me know!

![image](https://user-images.githubusercontent.com/37304634/106969811-97968700-6719-11eb-8c0a-a25379faadfd.png)

**Comment by corsacca** [comment]
@trip-nine 
This should now be fixed in 1.0.3
![deleting_contacts](https://user-images.githubusercontent.com/24901539/107197291-fe56c180-69f3-11eb-871b-421d2e6b4d3a.gif)
