### ISSUE TITLE
Translate tags

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1205]
We have a DT instance which is used by users of more than one language. So that we can assign the same tags, it will be useful to be able to translate the tags so that we aren't duplicating the items.

**Comment by corsacca** [comment]
Tags can not be translated.
They same functionality can be accomplished using the multi select field.

**Comment by mikeallbutt** [comment]
> Tags can not be translated.
> They same functionality can be accomplished using the multi select field.

OK. But you have to set up all the fields in admin area. A normal user cannot create translatable fields.
