### ISSUE TITLE
Inconsistent array declaration for quick_buttons

### ISSUE THREAD

**Issue by prykon** [DiscipleTools/disciple-tools-theme#1241]
**Description**
All quick_button arrays have the same indexes except for one that is missing the 'description' index. This triggers an error when looping each quick_button array and attempting to return the value for that index.

**To Reproduce**
1. Go to '/dt-contacts/dmm-module.php'
2. Scroll down to line 198
4. Line 199 is missing `'description' => ''`

**Expected behavior**
All array quick_button elements should have the same indexes.

**Additional context**
If the description index is irrelevant for the quick_button field, it should be removed from all quick_button field arrays.

**Comment by corsacca** [comment]
:+1: 
Can we also fix the spot that is throwing the error with an isset check?

**Comment by prykon** [comment]
Already did ;)
