### ISSUE TITLE
map module update bug, no delete button

### ISSUE THREAD

**Issue by trip-nine** [DiscipleTools/disciple-tools-theme#1246]
DT mapping module..

-No delete function..

-When you change ‘Name’ and ‘Update’ it does not update to the new name

-unsure if ‘Reset’ function works..

![disciple tools map module issues](https://user-images.githubusercontent.com/37304634/112366989-c65bc300-8caf-11eb-96c0-84378192dcdd.png)

**Comment by prykon** [comment]
Reset function works, it's just not updating due to the update bug. I'll keep looking into it.

**Comment by corsacca** [comment]
Thanks @prykon !

**Comment by prykon** [comment]
PR sent

**Comment by corsacca** [comment]
Closed by https://github.com/DiscipleTools/disciple-tools-theme/pull/1337
