### ISSUE TITLE
Web mobile view: align 'add unavailable dates' button 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1251]
On the settings page for a user in the area for setting unavailable dates, the button is set to high and should be in line with the 2 dates fields to the left.

![Screenshot_20210325-213548_Chrome.png](https://user-images.githubusercontent.com/43966676/112574001-048ddb00-8db3-11eb-8ccf-65979f711035.png)

This issue is seen using Chrome browser on a modern Android phone.

**Comment by squigglybob** [comment]
I'm happy to take this one @corsacca

**Comment by corsacca** [comment]
Great. Thanks @squigglybob

**Comment by squigglybob** [comment]
![image](https://user-images.githubusercontent.com/9816214/114737441-ed516600-9d3e-11eb-9f9e-775187c6a3d2.png)
Is this alignment better?
