### ISSUE TITLE
`This contact needs an update` stays visible even after an update is made

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1258]
When an update is made (by writing a comment) to a contact record (in this case it was an access type record) the red coloured tile stayed even though the `requieres no update` activity was logged.

**To Reproduce**
1. Find a record (that your user is assigned to) that needs an update
2. write an update in the comment box
3. note that the tile of `This contact needs an update.` stays

**Expected behavior**
The tile should disappear when the update is made (after clicking submit comment button)

**Comment by corsacca** [comment]
@mikeallbutt are you an administrator or dispatcher making the update or are you a multiplier?

**Comment by mikeallbutt** [comment]
@corsacca the role I was using when this happened was that of an administrator.

**Comment by corsacca** [comment]
Thanks @mikeallbutt for pointing this out!
