### ISSUE TITLE
Duplicate user item in add member modal for a group

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1260]
**Describe the bug**
The signed in user has a duplicate listing in the dropdown list when adding a member to a group.

**To Reproduce**
1. Go to a group that you want to add the signed user to be a member of
2. Click the `Select` tab in the Members list tile to open the modal to add a member.
3. Type in the name of your user (that you are signed in with) and you should see your item listed twice.

**Expected behavior**
You record should only be listed once.

**Screenshots**
<img width="1174" alt="Screen Shot 2021-03-28 at 21 00 41" src="https://user-images.githubusercontent.com/43966676/112781858-ede0c180-9008-11eb-8d4f-ec4157c54fc7.png">

**Additional context**
This might have something to do with the user being a non-english user, because this issue doesn't seem to happen when in English.

**Comment by corsacca** [comment]
Thanks @mikeallbutt for taking the time to report this issue.
