### ISSUE TITLE
Group icon is a single individual and not a group

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1261]
In the header area next to the name of the group record, the icon that is displayed is the normal single person icon like what is shown for a contact record. This icon should be switched to represent a group of people.

<img width="231" alt="Screen Shot 2021-03-28 at 21 12 45" src="https://user-images.githubusercontent.com/43966676/112782638-b83cd800-900a-11eb-96a0-7cf293c88cff.png">

**Comment by corsacca** [comment]
I would like that icon to be configurable by any post_type.

**Comment by corsacca** [comment]
Maybe the details bar should just offer a hook with a default. Contacts, groups, trainings, etc can hook in their own icon.

**Comment by micahmills** [comment]
We do have a hook for that https://github.com/DiscipleTools/disciple-tools-theme/blob/82d4866c9ca210ca38a780556b9d016e8a4aa354/dt-assets/functions/details-bar.php#L70 the facebook plugin is using it.

**Comment by corsacca** [comment]
Oh :), i forgot about that one.
