### ISSUE TITLE
Rest Api `permission_callback` Parameter

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1268]
As of Wordpress 5.5 all rest endpoints need a permission_callback
https://make.wordpress.org/core/2020/07/22/rest-api-changes-in-wordpress-5-5/

They are throwing an error that looks like this:
```
register_rest_route (since 5.5.0; The REST API route definition for <code>dt-metrics/personal/trainings/points_geojson</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback.)
```
Todo: go through each endpoint and add the permission_callback field, making sure we respect the existing permission checking.

**Comment by micahmills** [comment]
We do permission checking in all of our callbacks now so can we just add the `'permission_callback' => '__return_true',` as though they are public endpoints, or should we move that permission checking into the permission_callback?

**Comment by corsacca** [comment]
i think `'permission_callback' => '__return_true'` is ok as long as it does not open anything up unexpected.

**Comment by cwuensche** [comment]
Created the following PR https://github.com/DiscipleTools/disciple-tools-theme/pull/1287
