### ISSUE TITLE
Field Type: Tags

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1269]
Make tags it's own field type to go along side multi_select, key_select, etc
It currently rides off of the multi_select field type.
the multi_select is design to be a finite list of items. 
The tags field is meant to have many options and lets the user add options.

This will let a record have multiple different tag fields. 

Bonus points for also implementing this issue at the same time: #567 
Normal tags are stored in the `postmeta` table.
Private tags would be stored in the `dt_post_user_meta`

**Comment by cairocoder01** [comment]
I'll start looking into this

**Comment by corsacca** [comment]
Thanks @cairocoder01 

Maybe helpful list to places a field type shows up:
list filters + list search api query
list record rows + list data api query
displaying on a record + get_post api query
updating on a record  + update and create api queries
activity messages 
ui for creating fields and updating field options

**Comment by corsacca** [comment]
Updated list for future use:
- list filters + list search API query
- list record rows + list data API query
- displaying on a record + get_post API query
- updating on a record  + update and create API queries
- activity messages 
- new record page
- WP-Admin for creating fields and updating field options
