### ISSUE TITLE
Site Link transferred contacts are not available to assigned user

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-theme#1272]
**Describe the bug**
Given 2 sites that have been connected by 2-way site link where the base user of the receiving site has the role D.T Admin (NOT Administrator), contacts transferred that are assigned to the base user give a permission warning when that user attempts to open them (via direct URL link) and are not visible in their list of all contacts.

**To Reproduce**
1. Create a site link between 2 sites with transfer both ways
2. Set base user of receiving site to a user with D.T admin role but not Administrator
3. Create new contact on one site
4. Using Share dialog, transfer contact to second/receiving site

**Expected behavior**
When logged in as base user on receiving site, transferred contact is visible in all contacts, and going directly to the contact via URL shows contact details.

**Actual Behavior**
When logged in as base user on receiving site, transferred contact does not show in all contacts. When navigating directly to contact by putting ID in the URL, a permission error is shown (see screenshot below).

**Screenshots**
![image](https://user-images.githubusercontent.com/44169599/113573129-ca75d200-9619-11eb-943c-e2fa2db09921.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser Chrome
 - Version 89.0.4389.90

**Additional context**

**Comment by cairocoder01** [comment]
Looking at the source for `DT_Posts::can_view` (as used in single-template.php for the above example), it seems to check the `view_any_contacts` permission, but it seems like only `access_contacts` is given to the dt_admin role. It seems like either `view_any_contacts` permission is missing or there is a mix-up of those two permissions. I'm not clear on which should be used or what the exact difference is.

**Comment by cairocoder01** [comment]
Or this could be an issue on the contacts transfer endpoint. The endpoint to receive contacts in `dt-contacts/contacts-transfer.php` uses `wp_insert_post` to create the contact, whereas the API endpoint for creating new posts in `dt-posts/dt-posts-endpoints.php` uses `DT_Posts::create_post`, which automatically shares the new post with the user who created it. I think that step of sharing the contact is missing from the contact transfer process.

**Comment by corsacca** [comment]
No user role currently has the `view_any_contacts` permission. 
The D.T admin should have the `dt_all_access_contacts` cap which would give them permission to see the contact if it is an access contact. (is `access` the contact type @cairocoder01?)
https://developers.disciple.tools/theme-core/capabilities#post-types

I agree that we should make sure the transferred contact is shared properly with the user it is assigned to.

**Comment by cairocoder01** [comment]
Good to know. I see in the code that that cap should be applied and the filter should be recognizing that. I'll do some debugging since the DT admin definitely is not seeing all access contacts.

**Comment by cairocoder01** [comment]
I think I just needed to update the theme. I was on 1.0.x something, but after upgrading to 1.2.0, it seems to work as expected.
