### ISSUE TITLE
tags not showing up on refresh of contact/group page

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-theme#1296]
**Describe the bug**
When navigating to a record with tags, the given tags are not showing up in the tags multiselect box

**To Reproduce**
1. Go to any contact
2. Add any tags (you should see them appear and be in the activity list)
3. refresh the page
4. the tags now no longer appear

**Expected behavior**
The tags should always be visible

**Additional context**
Having traversed the history to find the cause of this bug, it has been traced to commit 6bb0c308 Don't return hidden multi_select values. Closes #1253

**Comment by corsacca** [comment]
Thank you for spotting this one and finding the culprit!

**Comment by squigglybob** [comment]
I think I need this one in order to carry on with #863 as I can't see the tags to do the links :)

**Comment by corsacca** [comment]
@squigglybob merged :)
