### ISSUE TITLE
Deleting a location is not getting logged

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1309]
If a location is set in the `Location or Address` field in the `Details tile` and the location is removed (by clicking on the red X on the right side of the field), 
<img width="383" alt="Screen Shot 2021-04-22 at 22 34 11" src="https://user-images.githubusercontent.com/43966676/115814860-80337580-a3bb-11eb-99f6-5b0483ce7e7c.png">
then the information is correctly removed and the field becomes empty. When this type of thing is done with other fields (ie. data being removed or updated - like a phone number) then that activity is logged and appears on the right site in the `Comments and Activity` tile.

When a location is set, then it does get logged and appears in the `Comments and Activity` tile. The same should happen when a location is removed.

**Comment by squigglybob** [comment]
Hi @corsacca , i'm happy to take this one...

**Comment by corsacca** [comment]
Thanks @NathTech

**Comment by squigglybob** [comment]
Hi @corsacca  or @mikeallbutt I have had a look under Contacts and Groups, and can't find anything matching the above screenshot...

The location or address inputs work as expected for those two pages.

Could you give some more information please as to where this issue is being found?

Thanks

**Comment by corsacca** [comment]
@squigglybob For this one you'll need to add a mapbox key from WP Admin > Mapping > geolocation

**Comment by squigglybob** [comment]
i'll get one now. I've also noticed that this field is hidden now from the code side,
![image](https://user-images.githubusercontent.com/9816214/116884241-6ba67700-ac1e-11eb-8257-67a14a41f3e0.png)

**Comment by squigglybob** [comment]
No problem, I've managed to get it showing, and can see the problem :) i'm on it
