### ISSUE TITLE
List Filters: written dates and old dates.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1312]
1. The date selector has a limit to how far back you can select a year (10 years ago).
![image](https://user-images.githubusercontent.com/24901539/115846071-70e31500-a419-11eb-8cc1-e35e128cd7f3.png)

We can increase this to 20 years.

2. When the user updates the text of the date in the input, this change is not saved and so does not reflect in the filtered records.

**Comment by squigglybob** [comment]
@corsacca I've tried to replicate point 2. and this only occurs if you don't press enter after manually typing in the date.  Would you want it to update the date onBlur as it were?

**Comment by corsacca** [comment]
Yes. That sounds good.
