### ISSUE TITLE
Comment Reactions Enhancements

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1324]

**Comment by corsacca** [comment]
Hover over the icon to see a tooltip text of the icon. (hear, laugh, etc)
![image](https://user-images.githubusercontent.com/24901539/116367245-0d812a80-a7ff-11eb-8e33-da5fec2382dc.png)

**Comment by corsacca** [comment]
Existing icons: thumbs up, heart, laugh, wow, sad, angry

WIP icons to swap:

**remove:**
- angry

**add:**
- Prayer
- Praise

**Comment by prykon** [comment]
@corsacca I finished the code for this. As soon as I finish wrestling with git conflicts I'll create the PR.
