### ISSUE TITLE
contact tiles order bug

### ISSUE THREAD

**Issue by trip-nine** [DiscipleTools/disciple-tools-theme#1326]
hey DT dev team,

I found an issue with re-ordering contact tiles (testing on 1.5.0),

if I try to move the 'Tags' tile from 'Other' to 'Details', and order it towards the bottom of details (next to 'age' & 'sources'), 

![image](https://user-images.githubusercontent.com/37304634/116443714-f9025980-a821-11eb-9f53-d577e0853dac.png)

it will not order correctly on in the contacts dashboard,

![image](https://user-images.githubusercontent.com/37304634/116444351-a2494f80-a822-11eb-95f0-caaeafec3b80.png)

could someone please investigate / fix this?
thanks!

**Comment by corsacca** [comment]
Thank for submitting this issue @trip-nine .
@cairocoder01's recent pull request (https://github.com/DiscipleTools/disciple-tools-theme/pull/1321) makes the tags field more dynamic and will allow the tags field to be move to other tiles and show up in the correct order.
This will be available in the next release (v1.6).
