### ISSUE TITLE
WP Admin. Settings: Upgrade Fields tab

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1331]
The current UI for creating a new field and updating an existing field needs some love.
![image](https://user-images.githubusercontent.com/24901539/116573359-a2ba1700-a904-11eb-903f-9ca411aacd67.png)
The select has a huge list of fields from all post types, making it hard to find what the user is looking for.

Creating an new field has some similar mixing of post types:
![image](https://user-images.githubusercontent.com/24901539/116573787-047a8100-a905-11eb-971e-f8390874eaa1.png)

Easy starting place, copy **post type** selection from the logic from the Tiles tab:
![image](https://user-images.githubusercontent.com/24901539/116573630-e1e86800-a904-11eb-839a-730a1c194ec3.png)

Then only display fields from that post type in the field selection dropdown
And remove the other post type tiles from the create new field dropdown.

**Comment by prykon** [comment]
Development and initial testing complete. Will test a bit more and create the PR.
