### ISSUE TITLE
Missing help and tutorials links on mobile devices views

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1342]
When using DT on a desktop, then the menu has the links to help and tutorials but on a reduced screen on a mobile device those menu items are not available.

**Desktop**
<img width="213" alt="Screen Shot 2021-05-05 at 07 45 04" src="https://user-images.githubusercontent.com/43966676/117143824-dc60a700-ad76-11eb-886f-f6871ded927b.png">

**Mobile**
<img width="360" alt="Screen Shot 2021-05-05 at 07 47 42" src="https://user-images.githubusercontent.com/43966676/117143891-eedae080-ad76-11eb-9fcf-977ea673d988.png">

**To do**
Have the missing links appear in the menu when using mobile devices.

**Comment by micahmills** [comment]
I added the Help link to the mobile menu. I think the Tutorial link comes from a plugin.
