### ISSUE TITLE
Assign icons to custom field items

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1346]
It is possible to create new options for all of the fields. Some fields like `faith milestones` come with icons. It would be nice to be able to add an icon to the custom item that has been created. It might be good to be able to change the existing icons to the default fields too.

**Example of the `faith milestones` field and the options**
The milestone `milestone_Praying` is custom to this instance.
<img width="1099" alt="Screen Shot 2021-05-06 at 13 58 40" src="https://user-images.githubusercontent.com/43966676/117353155-67c06200-ae75-11eb-919c-6e1ed343ac01.png">

**examples**

 These following images display ideas of what already is done in other parts of DT.

<img width="780" alt="Screen Shot 2021-05-06 at 13 59 35" src="https://user-images.githubusercontent.com/43966676/117353346-a0603b80-ae75-11eb-9543-94353aa91a55.png">

another option os how links to images could be done.

<img width="771" alt="Screen Shot 2021-05-06 at 13 59 50" src="https://user-images.githubusercontent.com/43966676/117353446-bd950a00-ae75-11eb-9e68-c99eedaaed7e.png">

**Comment by corsacca** [comment]
This only applies to `multi_select` values
