### ISSUE TITLE
Navigation Bar: Too many tabs

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1373]
Sometimes space is limited on the navigation bar and there are many items:
![image](https://user-images.githubusercontent.com/24901539/118647075-d76d1000-b7d8-11eb-9b44-75932d27f665.png)

Collapse the extra tabs under a "More" drowdown to keep the tabs from wrapping.

**Comment by prykon** [comment]
Is there a specific way we want it to appear?

**Comment by corsacca** [comment]
There is code already there for the dropdown, so here we can reuse it and nest the overflow in the dropdown.
