### ISSUE TITLE
List Page: allow the list table to horizontally scrolled

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1387]
Allow the list table to horizontally scrolled to allow for more columns and so that columns don't squished.
Keep the name (and other columns?) sticky on the left.

**Comment by mikeallbutt** [comment]
This is a good idea and it would be helpful to have the filters tile on the left be collapseable so that without it, more columns can be shown too.

**Comment by micahmills** [comment]
I ran across this today and I think it could work well with our list layouts. I will try to take a look at making an implementation. But this is just a note so I can find it later. https://codepen.io/scottjehl/pen/abJrPOP?editors=1100

**Comment by corsacca** [comment]
The `/user-management/users/` page is horizontally scrollable and could be used as a base.
