### ISSUE TITLE
Integration Request: Twillio

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1392]
Plugin to set up the connect with twillo so that D.T can send SMSs.
Use cases
- Notifications (though sms might not be the best for this).
- Batch sending of form (magic url) to users/contact to request updates
- Batch sending of tool (magic url) to users/contact during an event with tool link.

**Comment by prykon** [comment]
Would a WhatsApp integration plugin be a good second choice for Twilio? Their API is pretty straightforward.

**Comment by corsacca** [comment]
https://github.com/DiscipleTools/disciple-tools-channels-twilio
