### ISSUE TITLE
Magic Link: batch send link to list of contacts

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1393]
Send each member of a list of contacts their individual magic link urls.
Start with email sending. Could be upgrading with sms sending via the Twillio integration: #1392 

Message could be something like this:
Here is the link for this month's Saturation Reporting Tool [link]

**Comment by squigglybob** [comment]
this is potentially related to [Job Queue PR](https://github.com/DiscipleTools/disciple-tools-theme/pull/1395) as the job queue could process emails to be sent

**Comment by corsacca** [comment]
### Use cases where we would want to send magic links to users/contacts.
- Outreach counter: at an event, send a magic link to all the participants to easily track shares/progress
- Updates: asking each coach/leader for updates on their group
- Updates: asking member for updates on their group

To get started with all the structure pieces lets:

### Tile
Add a tile to the groups record (dt_details_additional_tiles hook)
- the tile will list out the magic link types available for that group (added via a filter)
- for each magic link type have a button to send the magic links. Ex
![image](https://user-images.githubusercontent.com/24901539/129604443-e6b6ad53-b657-402d-843d-e8c0d5179e72.png)
- only add the tile to the groups page if there are available magic link types for the displayed group

### Endpoint
- new file class in dt-reports
- called when the send button is pressed
- params: magic link type, post_type, record id

### Sending the notifications
- From the endpoint use a filter to go the records the magic links should be send to
``$contacts = __(`dt_send_magic_link_to_records`, [], $magic_link_type, $post_type, $post_id)`
The returned contacts should include the contact ID (or whole record?) and the notification type.
The notification type will be email by default. We can add more later.
- Send out the notifications based on the notification type and the magic link type.
- Let each magic link type provide the notification message: ie "message text: magic link url"

Resources:
- Dev docs: https://developers.disciple.tools/
- Adding a tile: https://developers.disciple.tools/theme-core/customization/field-and-tiles
- Magic link example: https://github.com/DiscipleTools/disciple-tools-plugin-starter-template/blob/master/magic-link/magic-link-post-type.php

**Comment by corsacca** [comment]
https://github.com/DiscipleTools/disciple-tools-bulk-magic-link-sender
