### ISSUE TITLE
Indicate if a contact is a leader of a group 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1397]
As a disciple maker it is important to invest in the right people like leaders. Creating a filter to find leaders is possible but being able to see in lists who are leaders would be better.

In the attached image, the contact Chris is a leader in one of the groups, but which one? The only current way to find that out is to go to each group and look for the footprint icon in members list tile next to his name. 

![Screenshot_20210526-071111_Firefox.png](https://user-images.githubusercontent.com/43966676/119704800-aebec900-be1d-11eb-8fb5-926964ecb2d8.png)

I suggest the footprint icon be displayed at the before the group name if the contact is designated as a leader of that group.

**Comment by corsacca** [comment]
@mikeallbutt  you can enable/ un-hide the "Leader of group" field and get the same data.

**Comment by mikeallbutt** [comment]
Thanks @corsacca I found the setting.

![Screen Shot 2021-05-27 at 07 51 04](https://user-images.githubusercontent.com/43966676/119829041-6efced80-bec0-11eb-9ddb-f57236b9d7dc.png)

It would still be useful to have the icon displayed in the list IMO.
