### ISSUE TITLE
Group leadership icon

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1398]
As seen in the attached image, the leadership icon (the black footprint) blends in too much in the members list of a group record. Also, having all the grey footprints on the right side is a bit confusing too.

![Screenshot_20210506-072023_Firefox](https://user-images.githubusercontent.com/43966676/119712144-eaf62780-be25-11eb-9913-db5dbcd296f4.png)

The suggestion is to move the grey footprints to the far left of the row - which leaves just the X icon on the far right - and remove the black footprint from the icons (representing bible and baptism) and if a member is a leader, then the footprint next to their name becomes black.

**Comment by corsacca** [comment]
How about keeping the leader icon next to the x, but changing it to black if it is selected?

**Comment by prykon** [comment]
> How about keeping the leader icon next to the x, but changing it to black if it is selected?

This, then?
