### ISSUE TITLE
DT Metrics Maps are not loading or populating data

### ISSUE THREAD

**Issue by trip-nine** [DiscipleTools/disciple-tools-theme#1433]
**Describe the bug**
DT Metrics Maps are not loading or populating data in the web version of 1.10. There appears to be a 404 error on the **combinedpoints_geojson** API request in this version (only one I tested)

**Desktop (please complete the following information):**
 - OS: [Web]
 - Browser [Chrome]
 - Version [1.10]

**To Reproduce**
1. Go to 'Disciple Tools Metrics'
2. Click on 'Combined Maps (or any map metrics tab)'
3. See error - the map never loads

**Expected behavior**
What should happen is all contacts should load and plot on the map.

**Screenshots**

![image](https://user-images.githubusercontent.com/37304634/129947627-98e67460-75e9-46cd-921b-d0dfeae4cb36.png)

![image](https://user-images.githubusercontent.com/37304634/129946799-1a473032-6917-4c6f-91ab-e9b976431891.png)
 
![image](https://user-images.githubusercontent.com/37304634/129946527-30b276be-b7f0-4f1a-9fa2-dbc03c652fff.png)

![image](https://user-images.githubusercontent.com/37304634/129946570-b565bf9c-9188-4c36-bbad-0b24c9936df2.png)

![image](https://user-images.githubusercontent.com/37304634/129946603-7690a2ea-ae38-46eb-83d8-b164a3a00584.png)

**Additional context** 
slack me for further info on the DT slack channel

**Comment by corsacca** [comment]
Thanks @trip-nine !
Fixed in 1.10.1
