### ISSUE TITLE
Collect DT Plugin Usage Telemetry Data

### ISSUE THREAD

**Issue by prykon** [DiscipleTools/disciple-tools-theme#1447]
It could be useful to collect usage telemetry data from active DT plugins so that we can see what kind of plugins the community finds useful and take that insight into account for future ideas and developments.
Also, this could show if plugins that actually are known to be useful aren't having the visibility that we'd like.

**Comment by ChrisChasm** [comment]
Also, to confirm, that we could track if the mapbox key is present.

**Comment by corsacca** [comment]
Done
