### ISSUE TITLE
Add icons to filter fields 

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1451]
In the left blue menu section: Show the field icons next to the field names.

![image](https://user-images.githubusercontent.com/24901539/131577292-a4ea0487-8857-4c7b-b755-b1a2906cd097.png)

**Comment by NathTech** [comment]
Does this look ok?

![image](https://user-images.githubusercontent.com/65535375/132312397-9591d19c-c7fa-4e13-9640-8b7a34f43074.png)
