### ISSUE TITLE
"adding sample content" does not work as documentation and YouTube video suggest

### ISSUE THREAD

**Issue by MichaelKentBurns** [DiscipleTools/disciple-tools-theme#1479]
**Describe the bug**
When viewing the (How to Launch a Demo Site) video at 1:43, it says "in the beginning you will have the option of adding sample content" and shows a blue button saying Install Sample Content.   

**To Reproduce**
1. Go to 'create a new demo site'
2. Login to your site.
3. Select the 'Contacts' tab.
4. The popup window 'Do you want to add sample content?' does not appear.  

or 

1. Extensions (D.T) 
2. Demo content 
3. Install

**Expected behavior**
My Contacts page to have a number of new contacts.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser Safari
 - Version 14.1.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by corsacca** [comment]
Thanks for the notice @MichaelKentBurns!
We had some hosting issues last week and some plugins got disabled.
We've re-enable the plugin and you should get the modal and/or be able to create demo contacts from the WP Admin now.

**Comment by MichaelKentBurns** [comment]
Thanks!   Worked fine.   Now, I can begin to learn how the tools are intended to be used.
