### ISSUE TITLE
Data Studio Connector

### ISSUE THREAD

**Issue by prykon** [DiscipleTools/disciple-tools-theme#1482]
As a Disciple.Tools user, I want a Data Studio Connector so that I can slice and dice my data and create my own graphics.

The connector would require the user's WP password in order to access the read-only data. Data Studio is as secure as any other Google product and so are connections to it. All Google products can be integrated to it including Google Drive, Google Ads, etc.

**Comment by prykon** [comment]
Some documentation: https://developers.google.com/datastudio/connector/build

**Comment by micahmills** [comment]
Does this plugin do what you need? 

https://disciple.tools/plugins/data-reporting/
