### ISSUE TITLE
"Create a new field" saves but no result

### ISSUE THREAD

**Issue by rdai** [DiscipleTools/disciple-tools-theme#1484]
**Describe the bug**
"Create a new field" says "Field added successfully" but then that field is not in the drop down of existing fields, nor on tile.

**To Reproduce**
1. admin->settings->fields-contacts
2. Click on "create a new field" button
3. fill out "test1" "text" "no tile" (or chose a tile)
4. Click on "create field" button
5. receive message "Field added successfully"
6. click on drop down "Modify an existing field", new field not there.
7. go to tiles->contacts, new field not there.

**Expected behavior**
expect new field to show up in "Modify an existing field" and tiles

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 
 - Chrome
 - 94.0.4606.61

**Smartphone (please complete the following information):**

**Additional context**

**Comment by corsacca** [comment]
@rdai this sounds like an issue we recently fixed, is this using the latest theme version?

**Comment by rdai** [comment]
Thank you, you were right, my bad. Verified as fixed in the new version.

BTW, I wrote on the DT site via contact form asking about if there are some small issues we can try to tackle in our coming Hack with Indigitous. Not sure how many people will show or if we can learn DT in time but I thought I ask. I can be reached at raydai gmail, thanks.
