### ISSUE TITLE
List page filters in url parameters

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1503]
It would be really nice to be able to build an filter strings url to send to other users so they can see the same filter you do.
Examples:
- `example.com/contacts?tags={one,two,three}&overall_status=active` // get all active contact that have one of these tags
- `example.com/groups?assigned_to={12,43}` // groups assigned to user 12 or user 43

To work with the default field types: https://developers.disciple.tools/theme-core/customization/fields#field-types
Except location_meta and array

Also the ability to set what columns to show in this list table  
`?table={name,assigned_to,my_awesome_cool_field}`

**Comment by squigglybob** [comment]
Hi @corsacca, how come not array's or location_meta?

**Comment by squigglybob** [comment]
doing some research on what characters are allowed in urls  from the rfc

[RFC 3986](https://www.rfc-editor.org/rfc/rfc3986)                   URI Generic Syntax               January 2005

      query       = *( pchar / "/" / "?" )

where
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

looking up all these things leads to a list of

alpha  digits  - . _~!$)&'()*+;=

that are allowable in the query portion of the URI

**Comment by squigglybob** [comment]
- [ ] decide format of query param for queries
- [ ] parse url for query params (shared functions)
- [ ] create filter from query params
- [ ] when filter is changed, update url query params (create url params in shared functions)
- [ ] on load update url query params
- [ ] update tag link on record to match new filter
