### ISSUE TITLE
Ampersand in Display Names not escaped properly

### ISSUE THREAD

**Issue by yeshu-davit** [DiscipleTools/disciple-tools-theme#1522]
**Describe the bug**
If you use an ampersand ( `&` ) in a Display Name (such as if a couple is sharing an account, with the display name `Jane & John`), the ampersand will rightly get stored as its escaped version - `&amp;`.  

However, in several places, when that name gets shown, it is displayed without un-escaping the ampersand.

**Example:** 
in `example.tools/user-management/users/` a user with the display name  `Jane & John` will have their name displayed properly in the Display Name field in the Users' table. 

However, if you click on their name in that table to open the _edit_  dialog, the title of that dialog will be `Jane &amp; John`. 

Further, while still in the _edit_ dialog, in the field where their Display Name can be edited, the default value for their display name will show as `Jane &amp;amp; John`

Another place this behavior shows up is in **@ mentioning** a user in a contact comment. When writing a comment, and mentioning the above name, `Jane &amp; John` gets recommended, and eventually added to the text of the comment.

In place of `Jane &amp; John` and `Jane &amp;amp; John`, the name should always simply display as `Jane & John`

**Disciple.Tools Theme:**
- version: 1.17.0
- setup: multisite

**Device and browser (please complete the following information):**
 - Device: Laptop, Smartphone
 - OS: Manjaro, Android, All tested platforms
 - Browser: Brave/Chrome/All

**Additional context**
As a temporary workaround, `+` can be used instead of `&` as it doesn't have the same escaping issue.

**Comment by corsacca** [comment]
Thanks for the feedback @yeshu-davit 
We've fixed this issue in other areas and will do the same for the users section:
Places to fix:
Users section
![image](https://user-images.githubusercontent.com/24901539/142843066-c5841fde-e4bb-4ae5-8419-89bc9283bb34.png)
![image](https://user-images.githubusercontent.com/24901539/142843095-f810da71-9a2c-47d5-9d78-ce85d2114dbd.png)
![image](https://user-images.githubusercontent.com/24901539/142843206-36250011-e83d-4561-98de-9153dab2e7de.png)

Record comments @mention:
![image](https://user-images.githubusercontent.com/24901539/142843332-3617573d-afa0-47b3-b210-460e64d6b5af.png)
