### ISSUE TITLE
Add "Uninstall" button on D.T Extensions

### ISSUE THREAD

**Issue by yeshu-davit** [DiscipleTools/disciple-tools-theme#1530]
**Is your feature request related to a problem? Please describe.**

If a plugin for some reason gets corrupted, or needs to be uninstalled for some reason, there doesn't currently appear to be a simple way to do that from the admin interface.

**Describe the solution you'd like**

Next to the "Activate"/"Deactivate" button, a "Uninstall" button would be wonderful:

![image](https://user-images.githubusercontent.com/81078105/143578224-b775f86b-90a7-4269-abe6-3fbe8cfaca40.png)

**Describe alternatives you've considered**

As far as I can tell, the only other option is going into the file-system WP is installed on, and just deleting the folder with the Extension in it. (Unless there's some other button on the interface I'm not seeing.)

**Comment by corsacca** [comment]
@yeshu-davit 
You can uninstall and deactivate plugins from the plugins menu if your have the administrator role. If you are on a multisite, then you need to be a super admin to uninstall plugins and you can only do so from the network-admin area.

**Comment by yeshu-davit** [comment]
Oh! Good to know! I thought that plugins for D.T were dealt with differently than WP plugins. Maybe, then, in place of a uninstall button, a little explainer that those things can be found in the main WP Plugins section might be in order?

Regardless, thanks! Super impressed with how you guys are building all this out. Keep up the good work!

**Comment by prykon** [comment]
Covered in https://github.com/DiscipleTools/disciple-tools-theme/pull/1601
