### ISSUE TITLE
Recreate toggle filter to hide/show archived records

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#1578]
Prior to Version 1 modularization, contact and group records had a toggle that could hide or display archived contacts.  Being able to filter out archived records at a glance is a super helpful feature.

**Comment by corsacca** [comment]
Create on a post type a way to indicate a closed status
On contacts "overall_status" -> "closed"
On groups "group_status" -> "inactive"
Investigate other post types (trainings)

Add the "hide archived" filter to the lists page
Which will add the 
`overall_status: ['-closed']` to the rest query
