### ISSUE TITLE
Quick Actions Translatable

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#1608]
The Default and Custom Quick Actions are not currently user translatable. We do this for other fields, but somehow missed the custom quick actions.

**Comment by micahmills** [comment]
Yes please take a look. The standard quick actions are translatable in the .po files, but custom quick actions that you create in the admin are not translatable. On other fields we have the option to add a translation for each custom field, but not in the quick actions.

**Comment by prykon** [comment]
Roger that.

**Comment by mikeallbutt** [comment]
@prykon please add the `key` field so that users create new items they can easily see what the key is. (this is what happens with other fields too)

**Comment by mikeallbutt** [comment]
It would be good to improve the `Contact Communication Channels` list also so that it shows the icon that each item is using.

**Comment by prykon** [comment]
> It would be good to improve the `Contact Communication Channels` list also so that it shows the icon that each item is using.

Hey, Mike! This falls outside the scope of this feature and would need its own issue.

**Comment by prykon** [comment]
> @prykon please add the `key` field so that users create new items they can easily see what the key is. (this is what happens with other fields too)
> 
> Key | Default Label | Custom Label | Link Icon | Translation

@corsacca Thoughts?

**Comment by prykon** [comment]
Got the green light from @corsacca. Key column added.
