### ISSUE TITLE
Emojis as Icons

### ISSUE THREAD

**Issue by prykon** [DiscipleTools/disciple-tools-theme#1620]
Aside from uploading a custom icon, it could be nice to use emojis for certain buttons, like quick actions.

<img width="692" alt="Screen Shot 2022-04-12 at 09 20 02" src="https://user-images.githubusercontent.com/36511666/162961171-ef320031-5da9-4515-b992-7854daa8b828.png">

**Comment by corsacca** [comment]
@prykon this sounds similar to: https://github.com/DiscipleTools/disciple-tools-theme/issues/1106

**Comment by prykon** [comment]
This gets covered in https://github.com/DiscipleTools/disciple-tools-theme/pull/1732
