### ISSUE TITLE
Group Tile Preferences not being respected in tiles

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1626]
The option to not use and show the `group tile preferences` of `church metrics` and `four fields` are not being respected.

As seen in the image, the option is deselected but the fields and tiles still appear in the back and front end.
![Screen Shot 2022-04-19 at 22 18 17](https://user-images.githubusercontent.com/43966676/164144005-de64da5d-be81-4c2e-a447-10e18989bf0f.png)
![Screen Shot 2022-04-19 at 22 19 12](https://user-images.githubusercontent.com/43966676/164144011-d78326f2-175c-4460-827e-d8f1fdc47231.png)
![Screen Shot 2022-04-19 at 22 20 18](https://user-images.githubusercontent.com/43966676/164144012-1880bed0-c2f1-4fc2-8795-16c505a10d12.png)

The only way to hide the tile is to do it as seen in the next image. But IMO these tiles should not be being offered if the `group tile preferences` were being respected.
![Screen Shot 2022-04-19 at 22 50 04](https://user-images.githubusercontent.com/43966676/164146764-a5347f41-8465-49f8-8cdb-3fababdf59aa.png)

**Comment by corsacca** [comment]
@todo. 
Option 1: Change the these settings to update the "hidden" param of the 4 fields tile and the Group Health tile
![image](https://user-images.githubusercontent.com/24901539/166427523-7dac93fc-5e9a-4394-aa80-89a836abee50.png)
Option 2: only display the tiles if they are not hidden and enabled in the group_preferences.
