### ISSUE TITLE
Favorite {Contacts/Groups} being used instance wide in certain roles

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1627]
When a user is assigned to be `administrator` or `dispatcher` or `disciple.tools admin` then they will see all the favorites that anyone with those privileges have assigned to be a favorite.

They should only see the ones that they as their user profile marked to be their favorite.

**Comment by corsacca** [comment]
@mikeallbutt Corsac B is an admininistrator and Corsac is an Administrator. Corsac B's favorite contact does not appear as favorite for the other Administrators. 
Ideas on how to reproduce the issue?
![image](https://user-images.githubusercontent.com/24901539/164186225-8239f9b1-5d3e-4ea0-94f4-04031eb5de91.png)

**Comment by corsacca** [comment]
This issue happened when the favorite field was change from "private" and then contacts marked as favorite.
To fix:
- make sure the favorite field is marked as private.
- delete all "favorite" records from the postmeta table.
