### ISSUE TITLE
Less versions of the Spanish language

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1628]
There are currently 5 versions of Spanish.  
![Screen Shot 2022-04-20 at 00 01 22](https://user-images.githubusercontent.com/43966676/164154729-2d96af92-e524-4973-9f19-26ff7fb93440.png)

For the most part, there is not much difference between the Spanish used in the Latino countries so they don't need to have their own version. Having their own version (like per country) means that someone has to translate it every time modifications are made to the theme. This becomes burdensome.

Now that it is possible to change most text in the admin area, if an instance wants to adjust a few phrases, then they can do it to suit their instance.

![Screen Shot 2022-04-20 at 00 02 26](https://user-images.githubusercontent.com/43966676/164154738-f288dc5b-c8ac-4018-bf21-0964e65bc1b2.png)
![Screen Shot 2022-04-20 at 00 03 00](https://user-images.githubusercontent.com/43966676/164154741-28f98b89-09aa-43c4-bd45-4c7d903c3549.png)

I suggest we have only one or two at the most. Those would be `Spain` and `Latin America`.

**Comment by prykon** [comment]
+1 on having only `Spain` and `Latin America` Spanish.
Just one caveat: I would use the

**Comment by mikeallbutt** [comment]
So lets remove 3 (just the country specific) translations of Argentina, Colombia, Mexico; 
And leave 2 - Spain and Latin America.

> +1 on having only `Spain` and `Latin America` Spanish. Just one caveat: I would use the `tú` and not the `usted`.
