### ISSUE TITLE
Sort dropdown icons

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1643]
This sort dropdown could use some icons.
Suggestions?
![image](https://user-images.githubusercontent.com/24901539/166421944-a2cdfe28-90f7-445d-9512-d0e79faa8560.png)

**Comment by corsacca** [comment]
Look for icons in https://materialdesignicons.com/

**Comment by EthanW96** [comment]
@corsacca should this issue be closed now that #2286 has been merged?

**Comment by corsacca** [comment]
Yes! Thanks.
