### ISSUE TITLE
Field explorer upgrades

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1654]
To this page /wp-admin/admin.php?page=dt_utilities&tab=fields
- add field icons
- add field options icons
- add link to edit field ( opens D.T settings > Fields > Field ).

**Comment by squigglybob** [comment]
@corsacca do you want the edit link to go straight to e.g. /wp-admin/admin.php?field_select_nonce=ebea1bf42f&page=dt_options&tab=custom-fields&post_type=contacts&field-select=contacts_baptism_date&field_selected ?

or just to /wp-admin/admin.php?page=dt_options&tab=custom-fields
