### ISSUE TITLE
Link field type

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1659]
Build i like field type.

Links
[Link type] : link
[Link type] : link

Ability to choose the link type or to add one.
A bit like the contact_x fields, but one field.

**Comment by squigglybob** [comment]
@corsacca I might need to have a quick connect on this one. I can't find any reference to contact_x in the code

**Comment by squigglybob** [comment]
## Use case
tracking prayer initiatives 

A post has many links
initiative link
campaign link
campaign data link
with future campaign links added later.

## implementation
Could have the field creation UI, have an add button within the field to add multiple urls and labels within the field.

## Benefits

Having one field that contains many link fields, would reduce the number of fields on the backend to create for one thing, e.g. communication channels field, with multiple types within it, facebook, twitter, etc.

It would also make frontend UI a bit cleaner too.

## Technical details
label, name icon etc. would be under default object.
meta_keys would be {field_name}_{link_label}
allow icon selection. (copy multi and key select)

**Comment by squigglybob** [comment]
@corsacca i've just been looking at the field options for the multi select field type, and I think that the link field will basically use exactly the same table as we have for the multi select which is handy, as all that will need to be done is to output these options as link inputs on the frontend rather than multi select buttons...

**Comment by squigglybob** [comment]
- [ ] add dev docs for link field
- [ ] create backend ui to create link fields
- [ ] create frontend ui to create link inputs
