### ISSUE TITLE
Language Flags

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1661]
Add flags to the D.T language selector 
![image](https://user-images.githubusercontent.com/24901539/166958622-49dc420f-390a-4535-a9d1-c9b18ec4ef89.png)
Like these:
![image](https://user-images.githubusercontent.com/24901539/166958753-ebc8c4cd-8023-4dc7-9393-4040f69d8741.png)
Example code:
https://github.com/Pray4Movement/pray4ramadan-porch/blob/40dd1dfc56a7aabf571bf1b0e08888646273fc07/site/functions.php#L4

**Comment by micahmills** [comment]
Just a note on this, I understand the reason for the flags but I think it can cause confusion a little bit when one language is spoken in many countries. For instance, in the example English has a US flag but what about Britain, Singapore, or Australia? We have a similar problem with Persian. The Iranian flag doesn't take into account Afghans, or Tajiks, or Persians who live in India or Europe.

**Comment by kodinkat** [comment]
I guess multiple locale/region language entries could be created; with corresponding flag - However, I'm guessing similar locales would make use of the same backend translation file?

So maybe a case of first identifying sibling locales?

**Comment by corsacca** [comment]
We like having the flags vs not having the flags.
We can update the flag for specific languages if we find better alternatives.
For English the language option does say: English (United Status). So it makes sense to have the US flag.
![image](https://user-images.githubusercontent.com/24901539/170242856-bfb402b5-c545-474c-bfd1-8fddff133119.png)
