### ISSUE TITLE
Hover over magic link apps button to show text

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1664]
![image](https://user-images.githubusercontent.com/24901539/167100476-eb89cd20-7663-4585-a0e9-31a129c8475a.png)
Hovering over the "send" button should popup "Send"
---
Also add icon descriptions to help modal.

**Comment by squigglybob** [comment]
is this becoming a standard for all buttons around the site?  Or is it just for buttons that could seem more obscure?
A quick search shows only 6 other places around the theme that have tooltips implemented
