### ISSUE TITLE
Activity Log shows trashed items

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1676]
As seen in the attached image, the `Activity Log` is currently displaying results from records from updated fields that were updated when the records were sent to the trash.

<img width="893" alt="Screen Shot 2022-05-01 at 17 11 41" src="https://user-images.githubusercontent.com/43966676/167692283-a78800ae-1da0-425e-899b-cb74728b85ee.png">

**Comment by corsacca** [comment]
Were the trainings deleted?

**Comment by corsacca** [comment]
@mikeallbutt 
Were the trainings deleted?
