### ISSUE TITLE
Link type upgrades

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1775]
Suggestions for maybe separate Issue/PR

- Add button could be a dropdown with the types. 

- If there are no types should there be a message saying to create one?

- Auto add if there is only one selection
![2022-08-29_18-18](https://user-images.githubusercontent.com/24901539/187259512-73bf7eba-da88-491a-b635-c7185ed766f2.png)

- Combine inputs under one label:
![image](https://user-images.githubusercontent.com/24901539/187259357-78ebb509-c2e0-44f2-a3fb-affba3b1c82a.png)

_Originally posted by @corsacca in https://github.com/DiscipleTools/disciple-tools-theme/issues/1687#issuecomment-1230640792_

**Comment by corsacca** [comment]
- Create link field with a default option type
- hide field label if only one type is available

**Comment by squigglybob** [comment]
* [ ] make links in collapsed details tile be links

**Comment by squigglybob** [comment]
- [ ] close dropdown on click
- [ ] make entire header into a hover
- [ ] show subtitles traigt away
- [ ] work on create record page

**Comment by squigglybob** [comment]
@corsacca I think this one is done now
