### ISSUE TITLE
The latest version of D.T. (1.31.0) has an issue populating data in Metrics -> Projects -> Combined Maps view

### ISSUE THREAD

**Issue by trip-nine** [DiscipleTools/disciple-tools-theme#1805]
**Describe the bug**
The latest version of D.T. (1.31.0) looks to have an issue populating red dot / blue dot combined data..

<img width="1585" alt="image" src="https://user-images.githubusercontent.com/37304634/191632166-e0b8bdca-f7b8-4816-8606-43e21052543a.png">

**To Reproduce**
Steps to reproduce the behavior in 1.31.0:
1. Go to **Metrics**
2. Click on **Projects**
3. Open **Combined Maps**

**Expected behavior**

Active Contacts & Groups should be populating the map (v1.30.1 below), they are not.

![image](https://user-images.githubusercontent.com/37304634/191632652-3076a3f2-e835-4997-abe0-b688746f73f1.png)

**Screenshots**

<img width="1585" alt="image" src="https://user-images.githubusercontent.com/37304634/191632663-e9c0b29a-d85c-46e2-a695-76f12818f3c0.png">

**Disciple.Tools Theme:**
- version: 1.31.0
- setup: Single site

**Device and browser (please complete the following information):**
 - Device: Macbook Pro
 - OS: Monterey
 - Browser: Chome
 - Version: Latest

**Additional context**
N/A

**Comment by corsacca** [comment]
Thanks @trip-nine !
1.31.1 should fix this issue
