### ISSUE TITLE
DT 1.32.2 Metric Maps not populating

### ISSUE THREAD

**Issue by trip-nine** [DiscipleTools/disciple-tools-theme#1828]
**Describe the bug**
DT 1.32.2 Metric Maps not populating

**To Reproduce**
1. In DT 1.32.2 go to /metrics/combined/mapbox_combined_maps
2. Metrics do not populate

I have tried various DT instances, multiple browsers, multiple systems, and multiple networks.

Something is still wrong

**Expected behavior**
-Metrics should be populating

**Screenshots**
Illustration of issue
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/37304634/196965949-29a5c32e-5ba7-4d6f-9df4-c9b69e82e9af.png">

**Disciple.Tools Theme:**
- version: 1.32.2
- setup: single site

**Device and browser (please complete the following information):**
 - Device: macbook pro & macbook air (tested both)
 - OS:  Monterey
 - Browser Chrome (lastest) and Safari (latest) - tested both

**Comment by cairocoder01** [comment]
No errors in the console. I turned on WP error logging and didn't see any server errors either.

**Comment by corsacca** [comment]
Fixed by https://github.com/DiscipleTools/disciple-tools-theme/pull/1831
