### ISSUE TITLE
Location/Address not save

### ISSUE THREAD

**Issue by philipyuen** [DiscipleTools/disciple-tools-theme#1837]
Hi,
After I added mapbox api token, location/address of contacts cannot be saved. Please advise.
Thanks,
![Screenshot 2022-10-26 134656](https://user-images.githubusercontent.com/116542371/198134346-d5c31821-d597-49af-b756-73ef842bb7e4.jpg)

Philip

**Comment by corsacca** [comment]
Hey @philipyuen ,
Do you see an error message on the Mapping Settings page?
like this: 
![image](https://user-images.githubusercontent.com/24901539/198988353-7205a6d4-97c8-46e2-8fd8-66d96a4d1532.png)

If the mapbox api token is restricted to a certain domain, then there is currently an issue with that. 
I've created a potential solution to fix the issue: https://github.com/DiscipleTools/disciple-tools-theme/pull/1846

**Comment by corsacca** [comment]
To test the fix you can uncheck the `Referrer-Policy` option and click save:
![image](https://user-images.githubusercontent.com/24901539/198998021-c4e14610-0dad-4302-a0f6-bf63cd98bae1.png)

**Comment by philipyuen** [comment]
No error on geocoding tab.
<img width="879" alt="Screen Shot 2022-10-31 at 8 12 40 AM" src="https://user-images.githubusercontent.com/116542371/199042821-6c88a16e-b277-46d0-a282-090929b94546.png">

Unchecked referrer-policy > refresh > same issue.

Thanks.

**Comment by philipyuen** [comment]
I just checked on linux. Curl version 7.58.0 was installed. But that line 'CURL is not installed' appeared on the geocoding tab page.

**Comment by corsacca** [comment]
Hey, Geocoding should still work without this. But Curl might be the issue.
do you have the php-curl version installed? 
See https://stackoverflow.com/questions/41058055/wordpress-plugin-curl-is-not-installed-on-this-server

If Curl is not installed some of the migrations might not worked. 
Would you be able to check the WP Admin > Utilities (D.T) tab. It has a list of the migration numbers and should look like:
![image](https://user-images.githubusercontent.com/24901539/199197433-5efc88e7-0c12-45a1-99df-38adaf1397f6.png)

**Comment by philipyuen** [comment]
<img width="723" alt="Screen Shot 2022-11-01 at 7 49 44 AM" src="https://user-images.githubusercontent.com/116542371/199262608-98674ccb-1abb-4d24-981e-11ea24cd284d.png">

**Comment by philipyuen** [comment]
Php 8.1 curl was installed and service apache2 restarted. Still showing Curl is not installed.

<img width="590" alt="Screen Shot 2022-11-01 at 8 16 51 AM" src="https://user-images.githubusercontent.com/116542371/199269152-e6ef3d74-715c-4b6b-a543-e70901e7d44e.png">

**Comment by philipyuen** [comment]
Clicked 'unlock and rerun migrations' and got an error warning.

![Screenshot 2022-11-01 123641](https://user-images.githubusercontent.com/116542371/199323107-d04042a7-374a-4f6e-be6d-85d5f252c251.jpg)

**Comment by corsacca** [comment]
@philipyuen the utilities screenshot is showing that wordpress is using php7.4.32.
Would you be able to try installing php7.4-curl ?
Or switching which php apache uses to php 8.1

**Comment by philipyuen** [comment]
After updating php to 8.1 and unlock & rerun migrations, it fixed the address saving issue. Thank you for your recommendation.
