### ISSUE TITLE
Delete Report button

### ISSUE THREAD

**Issue by philipyuen** [DiscipleTools/disciple-tools-theme#1838]
**Describe the bug**
'Delete Report' button did nothing. 

**To Reproduce**
1. Wordpress Admin
2. Reports (D.T.)
3. List tab
4. Click Edit generated report: January 2022
5. Click Delete Report button

**Expected behavior**
Delete generated report

**Screenshots**
See attached

**Disciple.Tools Theme:**
- version: 1.32.3
- setup: single site

**Device and browser (please complete the following information):**
 - Browser Chrome
![Screenshot 2022-10-26 134756](https://user-images.githubusercontent.com/116542371/198135193-cda6d1b6-920f-4daa-b4ba-de753a3fef36.jpg)

**Comment by corsacca** [comment]
Thanks @philipyuen!
