### ISSUE TITLE
Workflows: Ability to archive a record

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-theme#1839]
**Is your feature request related to a problem? Please describe.**
I would like to archive a record when a given post type change happens. Currently, the archive field is not accessible in the workflow setup.

**Describe the solution you'd like**
Add the Archive field (or however it is tracked) to fields that can be edited in step 3 of workflows.

**Describe alternatives you've considered**

**Additional context**

**Comment by cairocoder01** [comment]
@corsacca Does that apply to groups too? I need to be able to archive groups. I don't even see archive in the admin actions in the front-end UI now that I look for it.

**Comment by corsacca** [comment]
The current setting for archived for groups is setting them to inactive in the status.
Each post type has setting to specify the archived field and key:
https://github.com/DiscipleTools/disciple-tools-theme/blob/470350a738e4cd74f3cf4dfc8dbe5c77d70543a0/dt-groups/base-setup.php#L65

**Comment by cairocoder01** [comment]
Cool. This probably isn't an issue then
