### ISSUE TITLE
Sync User languages and the languages available in the languages select field

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1902]
Some use case would benefit from this sync, like the dispatcher assignment tool.

The contact languages field has user defined values, ie "es"

The user languages uses "es_ES"

**Comment by himayrunner** [comment]
Here's another example: 
https://www.loom.com/share/4f965b9b8a15407c95e61baa495022c7

**Comment by corsacca** [comment]
The instance has a custom `language_preference` field instead of using the `languages` field.
