### ISSUE TITLE
Upgade User from Contact Dropdown Option for those without permission

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools-theme#1938]
**Describe the bug**
On role like multiplier where I do not have permission to upgrade a contact to a user, the option for upgrading is available in the admin dropdown.

**To Reproduce**
1. Sign in as a multiplier user
2. Create a contact
3. In the admin options at the top of the contact details page where you can delete the contact, there appears the option for upgrading the contact as a user. 
4. This option is not possible and goes to a permission denied page,

**Expected behavior**
The upgrade contact to user option should be removed if the permission is not available.

**Screenshots**
[ but the option should be removed if the permission is not available.](https://www.loom.com/share/a226f51ff65f4124a6a8821bf2fdfdf7)

**Disciple.Tools Theme:**
- version: 1.35.1
- setup: multisite

**Device and browser (please complete the following information):**
 - Device:Macbook
 - OS:MacOS
 - Browser Chrome
 - Version

**Comment by kodinkat** [comment]
Hey @ChrisChasm I'm just trying to recreate, however, logic appears to be holding true; as both make & link user options are hidden for multiplier with no `create_users` capabilities.

![Screenshot 2023-02-15 at 10 39 39](https://user-images.githubusercontent.com/19330800/219005639-0baf6a9b-f4b3-4692-91c9-83ea43ac4b31.png)

![Screenshot 2023-02-15 at 10 40 34](https://user-images.githubusercontent.com/19330800/219005691-a4766769-4f7b-4527-9c93-befa0ca10fb8.png)

**Comment by corsacca** [comment]
@kodinkat what happens as a multiplier we the `non_admins_can_make_users` option updated to true?

**Comment by kodinkat** [comment]
Hey @corsacca, enabling `dt_user_invite_setting` flag, subsequently displays the `Make a user from this contact` admin option; which then takes me through to `Add New User` view when clicked. See screenshots below....

![Screenshot 2023-02-15 at 14 53 40](https://user-images.githubusercontent.com/19330800/219063492-296bee37-ae89-41b5-912d-f1d53a2c449d.png)

![Screenshot 2023-02-15 at 14 54 01](https://user-images.githubusercontent.com/19330800/219063558-b57cc726-ab57-4019-9b2d-f386f92e72c2.png)

![Screenshot 2023-02-15 at 14 54 14](https://user-images.githubusercontent.com/19330800/219063615-65007847-1a63-4146-8b24-266d928b8016.png)

**Comment by corsacca** [comment]
@ChrisChasm We could not replicate this for a multiplier. Can you confirm?

**Comment by corsacca** [comment]
Could not replicate issue. @ChrisChasm let us know if it shows up again.
