### ISSUE TITLE
Settings not saving with key_select and multi_select field

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1958]
When editing a custom field option (for a field like `Reason Paused`), the translation string is not being saved.

Steps:
Create a new field option
Once the page reloads with the new option (listed last), click the translation button, type a phrase, click update. 
The page will reload but the translation will have not been saved.

**Comment by corsacca** [comment]
Issue:
The label and description translations add too many fields to form for it to submit properly with some server setups
