### ISSUE TITLE
Bulk Edit: Ability to un-share contacts

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-theme#2062]
**Is your feature request related to a problem? Please describe.**
When contacts have been assigned to the wrong user, we can bulk edit to assign them to the correct user. However, the contacts are still shared with the first user and they continue to see notifications for them.

**Describe the solution you'd like**
In the Bulk Edit feature, it would be great to be able to un-share posts with a given user. It could be a checkbox next to the Share field to indicate that these users should be removed instead of added.

**Describe alternatives you've considered**
Open to other options as long as it can un-share with many posts at once

**Additional context**

**Comment by corsacca** [comment]
Implemented: 
![image](https://github.com/DiscipleTools/disciple-tools-theme/assets/24901539/a4fc9623-1a3f-45fa-ab56-a68f0a40a870)
