### ISSUE TITLE
Customization Beta: Can't drag/assign fields to new tile

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-theme#2072]
**Describe the bug**
When I create a new tile in the Customizations Beta, I'm unable to then drag an existing field into that tile. I'm also unable to click the plus to expand it.

**To Reproduce**
1. Go to Customization Beta in admin
2. Add a new tile
3. Attempt to click plus to expand new tile (won't work)
4. Attempt to drag an existing field to new tile (won't work)
5. Edit an existing field and attempt to set tile to new tile and save (unresponsive)

**Expected behavior**
Expect to be able to move existing fields to a new tile - either by dragging or by setting tile in the field's edit dialog

**Screenshots**

**Disciple.Tools Theme:**
- version: 1.40.0
- setup: local

**Device and browser (please complete the following information):**
 - Device: MacBook
 - OS: MacOS 13.3.1
 - Browser: Chrome
 - Version: 113.0.5672.92

**Comment by cairocoder01** [comment]
It does seem that setting the tile from the field's edit dialog did work after refreshing the page. But after the save button is pressed initially, the page doesn't respond or show the change.

**Comment by corsacca** [comment]
Thanks @cairocoder01. Expanding the new tile should be fixed in 1.40.1

Dragging fields between tiles is currently not supported. But possible to change it from the modal as you found.
We'll probably get to that one at some point. At the moment we're prioritizing feature parity.
You can see the Customizations planning board if you want: https://github.com/orgs/DiscipleTools/projects/13/views/1

**Comment by cairocoder01** [comment]
Dragging between tiles isn't super important to me. I just saw the drag handles and thought it might work. It was my first guess at moving a field to a new tile. If you have to switch the tile dropdown to move it, that's sufficient. After feature parity, that could be something to consider for enhancements that could be intuitive to users.

I'm happy for this issue to just be the need to refresh when moving to a new tile. So once that's fixed, feel free to consider this issue fixed.
