### ISSUE TITLE
sso login options are disabled on subsites on a multisite instance

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-theme#2160]
This means that you can only change the sso login options on the main site of a multisite instance.

But what if the main multisite instance isn't running DT, then you can't change them at all!

## Expected behaviour

1. On a subsite running DT, you should be able to edit the firebase options, only if you are a super administrator
2. Options on the general tab, should be editable by any subsite administrator, as they may want to have different redirect_urls etc. or they may not want to use the custom login at all.
3. On a subsite the available identity providers should be disabled, as the multisite admin will have turned on only the ones that the firebase project is setup to deal with.

## To reproduce

1. On a multisite instance, go to the subsites dashboard and go to /wp-admin/admin.php?page=dt_options&tab=sso-login&sub_tab=general on that subsite.
2. All of the inputs are disabled even for a super admin

**Comment by corsacca** [comment]
I think this one is done.
