### ISSUE TITLE
Better Log In failed:

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#2178]
Reenable this function in a way that does not break core funcionality.

It keeps the error message from showing:
![image](https://github.com/DiscipleTools/disciple-tools-theme/assets/24901539/c4f57168-ccbd-4b07-bfcb-4203e56d7803)
 

```
/* Where to go if a login failed */
add_action( 'wp_login_failed', 'dt_login_login_failed' );
function dt_login_login_failed() {
    if ( !dt_is_rest() ){
        $login_page  = dt_login_url( 'login' );
        wp_redirect( $login_page . '?login=failed' );
        exit;
    }
}
```

**Comment by corsacca** [comment]
Fixed in: https://github.com/DiscipleTools/disciple-tools-theme/commit/e59a659c7a397423cb15cf287f446dde71ea055a

**Comment by squigglybob** [comment]
is this done then @corsacca ?
