### ISSUE TITLE
Activity Field specific day report always returns a total of 0

### ISSUE THREAD

**Issue by TheManuka** [DiscipleTools/disciple-tools-theme#2230]
If you search for any "seekers path" activity (or any type of activity) on a specific date you will always get a return value of 0.

![780d69ff-f32d-474a-bd6b-3faff9c7dedd](https://github.com/DiscipleTools/disciple-tools-theme/assets/136607942/dd0ab907-b9be-46c0-a0ba-82e38596f41e)

![1e77acac-c762-49c6-9250-bb321635baa1](https://github.com/DiscipleTools/disciple-tools-theme/assets/136607942/4e481a95-6e39-4d50-8aaf-6e002bce93e2)

But if you search with a larger timeframe than 1 specific date you will get values:

![image](https://github.com/DiscipleTools/disciple-tools-theme/assets/136607942/d2ed29fa-a7df-4f3d-8ab6-ffc1fe366627)

**Comment by corsacca** [comment]
Thanks @TheManuka , we'll have a look.
