### ISSUE TITLE
Metrics: Basic Reports to Create

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#226]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrisChasm](https://github.com/ChrisChasm)**
_Thursday Sep 14, 2017 at 17:09 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/146_

----

We need a working list of the basic reports we need to create for the MVP.

- [x] Critical Path report
- [x] Pace
   - [ ] Contacts
   - [ ] Groups
- [ ] Workers
- [x] Groups
   - [x] Bible Studies
   - [x] Churches
   - [x] Generations
- [x] Contacts
   - [x] Seeking
   - [x] Training
   - [x] Generations
- [x] Outreach
   - [x] Media by Sources
   - [x] Generations
- [x] Prayer
   - [x] Prayer Network
   - [x] Prayer Interactions
   - [x] by Channels
- [ ]  Locations
- [ ] People Groups
   - [ ] Overview
   - [ ] Joshua Project
   - [ ] Languages

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Thursday Oct 05, 2017 at 21:14 GMT_

----

Added framework for the tabbing and chart loading:
https://github.com/DiscipleTools/disciple-tools-theme/pull/66

**Comment by corsacca** [comment]
@ChrisChasm what are your thoughts for this card. It seems we have shifted some from that initial list.

**Comment by ChrisChasm** [comment]
Version 1 of this is created. This list is no longer an accurate description of next steps, so I am closing the issue.
