### ISSUE TITLE
Login: reset password flow

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#2281]
Custom login lets a outside agent check if an email is in the system:
<img width="422" alt="image" src="https://github.com/DiscipleTools/disciple-tools-theme/assets/24901539/06869154-ba35-4689-b335-1afae323bc75">

This  is not great for privacy/security.

The core behavior with D.T just tells the user to check their email:
<img width="451" alt="image" src="https://github.com/DiscipleTools/disciple-tools-theme/assets/24901539/4fec2aec-7f38-44cc-b8b8-8d30eb9e9e58">

**Comment by squigglybob** [comment]
I'm getting.
Is there a setting i need to switch to turn this behaviour off?

![image](https://github.com/DiscipleTools/disciple-tools-theme/assets/9816214/13ac38b2-0beb-4f61-85a9-36d9e5be4818)

**Comment by squigglybob** [comment]
In `users.php > retrieve_password()`
Have tried using the `lostpassword_errors` filter to flush out the errors, but unflushable errors come in later when the $user_data is not a `WP_User` object.
