### ISSUE TITLE
customizable magic link email subject lines

### ISSUE THREAD

**Issue by iThunk** [DiscipleTools/disciple-tools-theme#2297]
When I send a magic link to all of my Disciple.Tools contacts the default subject line is: Disciple.Tools: Update Request. 

It would be more powerful/engaging if we could choose the subject line: e.g. Hey friend, please make sure we've got your details right!

**Comment by corsacca** [comment]
Add a subject input populated with the default subject text
<img width="1039" alt="image" src="https://github.com/DiscipleTools/disciple-tools-theme/assets/24901539/2129e272-8fc6-4941-9fe5-9011e42a9354">
