### ISSUE TITLE
comment type @mentions notifications

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#2309]
insert_notification_for_comment only sends a notification to @mentioned users if the comment is of type 'comment'

**Comment by kodinkat** [comment]
It would seem it's a size restriction issue; as the wp_comments table currently has a column comment_type `varchar(20)` size constraint; which will fail for longer types.

![Screenshot 2024-05-09 at 13 12 53](https://github.com/DiscipleTools/disciple-tools-theme/assets/19330800/b651dd18-eb6c-4307-b693-a047755d12ac)
