### ISSUE TITLE
Ability to upload media to be stored securely.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#2395]
For profile pictures, voice messages, pictures in comments, etc.

Ideally media would not be stored on wordpress. (we think this is not secure).
Media would be stored in S3, or backblaze.

**Comment by cairocoder01** [comment]
Another cloud storage provider to consider is Cloudinary. I think they have a pretty decent free plan that would let a lot of people use it who don't have a lot of resources.
