### ISSUE TITLE
Adding 40 languages to custom list failed in admin area

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-theme#2417]
@corsacca  Trying to add 40 languages for zume to the languages list on wp-admin/admin.php?page=dt_options&tab=custom-lists

failed at around 18

![image](https://github.com/DiscipleTools/disciple-tools-theme/assets/9816214/20bbf1f0-46bd-4909-b01c-a62384e46d3e)-

**Comment by corsacca** [comment]
We'll want to update this to be a ajax post requestwith the changes instead of a php post.
Each translation adding ~100 fields to the post request and going over the max 1000 fields in the PHP POST

**Comment by corsacca** [comment]
Files to update:
- dt-core/admin/menu/tabs/tab-custom-lists.php
- dt-core/admin/js/dt-options.js
- dt-core/admin/menu/tabs/admin-endpoints.php

The _POST for adding a language contains the whole form and the updates for translations on each language:
![image](https://github.com/DiscipleTools/disciple-tools-theme/assets/24901539/257aebaf-43d1-455d-8df1-74a0f300300f)

Once ~1000 fields is reached, some hosts trim the _POST request.

Todo:
- Remove the Table from inside the <form>. this will let adding languages work.
- transform the "save" button to submit an ajax request to a new rest endpoint to update the languages and translations.

How we've fixed it in the past:
https://github.com/DiscipleTools/disciple-tools-theme/pull/2067

**Comment by CptHappyHands** [comment]
@corsacca @squigglybob I am still working on implementing an ajax solution, but may have found a way to cut down on the huge requests in the mean time: https://www.loom.com/share/fa2486ca60cd486db30907dba3bdb88b?sid=38186f73-51ec-464b-aad1-1f148628d71c

**Comment by squigglybob** [comment]
I think that's not a bad idea as it will make any POSTs more efficient when the translations aren't being used.

You can see where the translations get used by navigating to /settings and scrolling down to the section "Languages you are comfortable speaking" The translations will show up here.

We have to assume the worst (best?) case, of these sections being fully translated. So while stripping out the empty translations will reduce POST size when they aren't there, the system still needs to be able to cope when the array is full of translations.

**Comment by CptHappyHands** [comment]
I think adding that last commit finishes this @corsacca. Unless I'm missing something.
