### ISSUE TITLE
Develop D.T's eslint

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#2423]
D.T does not yet have a very opinionated js linter. 
So some PRs come with a wide range of linter improvements.

The IDE should pick up on the theme's .eslintrc.cjs and .editorconfig

Todo: Propose a standard.

When approved: refactor all js files to adhere to the standard.

**Comment by cairocoder01** [comment]
I agree with prettier. It's quite opinionated and not super configurable, but for that reason it has become fairly standard. I'll setup a PR to implement it so it can be reviewed.

**Comment by corsacca** [comment]
Awesome. Thanks guys!

**Comment by corsacca** [comment]
Is this part standard? Feels weird, but probably will get used to it.
<img width="1405" alt="image" src="https://github.com/DiscipleTools/disciple-tools-theme/assets/24901539/5f515713-45a8-4308-8d6c-789406d144f2">

**Comment by micahmills** [comment]
> Is this part standard? Feels weird, but probably will get used to it. <img alt="image" width="1405" src="https://private-user-images.githubusercontent.com/24901539/317715271-5f515713-45a8-4308-8d6c-789406d144f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Mzg1NjcsIm5iZiI6MTcxMTYzODI2NywicGF0aCI6Ii8yNDkwMTUzOS8zMTc3MTUyNzEtNWY1MTU3MTMtNDVhOC00MzA4LThkNmMtNzg5NDA2ZDE0NGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE1MDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZjk5ZWFkYThlZWYzNzZhYWIzN2JmZDlmZTUxYzVjZjM0NzliYmUzMTMzZTQ3OWI4ZGU4MDU3NDFlMDQwM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mi2mQfG1vfc5fHqTZA60qFloBXNz5B2NN1vvCv6kktk">

Yes in theory it makes it harder to miss a conditional because they are all on their own line.

**Comment by cairocoder01** [comment]
@corsacca It's most likely because of line length. You can adjust max width (https://prettier.io/docs/en/options#print-width) in prettier, or it says you can set `max_line_length` in the `.editorconfig`. Default value seems to be 80 characters.

**Comment by squigglybob** [comment]
Yeah I like the things being on seperate lines like prettier does it, like @micahmills says it makes it easier to see each conditional, and if one of them is changed in a PR, it's easier to pick out the diff when it's on it's own line
