### ISSUE TITLE
Unexpected display_name change

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-theme#2506]
**Describe the bug**
When a user goes to edit their own profile, they are shown a "Nickname (Display Name)" field. This displays the `nickname` from their profile (which defaults to a user's email for new users). However, when it is saved, it overwrites the `display_name` field on the user's account, which changes how their name is displayed throughout the system.

**To Reproduce**
1. Create a new user via User Management with display name "test" and email "test@test.com"
2. View user record in admin and confirm that `display_name` is "test" and `nickname` is "test@test.com"
3. Login as new user
4. Confirm in header that their profile link shows as "test", which is their display name.
5. Open user profile
6. See that "Nickname (Display Name)" field shows "test@test.com", which is not their display name.
7. Click "Edit" to edit profile
8. Save form without changing anything.
9. Confirm in header that their profile link has changed to "test@test.com" when they didn't actually change any form field.

**Expected behavior**
When a user edits their profile, they should see their actual current display name. If they open the edit form and don't change anything, their display name should not change.

**Disciple.Tools Theme:**
- version: [e.g 1.63]
- setup: local

**Device and browser (please complete the following information):**
 - Device: MacBook
 - OS: macos 14.4.1
 - Browser: Chrome
 - Version: 125.0.6422.77

**Additional context**
It might make sense for the `nickname` of new users to be set to the display name. It feels like that could make more sense than the email. However, I don't notice this field being used anywhere else in the system, so maybe it should be ignored.

**Comment by corsacca** [comment]
@todo
makes sure this field pulls from the display name instead of the Nickname user field. We don't use the nickname field anywhere.
![image](https://github.com/DiscipleTools/disciple-tools-theme/assets/24901539/cf718f75-03ac-423a-ac50-13b7e1975179)
