### ISSUE TITLE
Customizations Beta - can't add option translation

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-theme#2507]
**Describe the bug**
When trying to add a translation of a dropdown option in the Customizations Beta admin, it seems to show that it saves, but after refreshing the page it is gone.

**To Reproduce**
1. Go to D.T Customizations Beta admin
2. Expand a tile with a dropdown field
3. Expand the options for a dropdown field (e.g. Faith Status)
4. Click pencil to edit option (e.g. Seeker)
5. Click translate icon next to name
6. Add English translation of "Seeking"
7. Click Save to close translation dialog
8. Confirm translate icon shows a "(1)" next to it indicating the translation was added.
9. Click Save to close option dialog
10. Check on value and see it's gone (multiple options from this point)
    a. Immediately open option again and see that the translate icon is back to "(0)"
    b. Refresh page and option tile, field, option again. See that translate icon is back to "(0)"
    c. View contact record page, open Faith Status dropdown, and see that value is not translated

**Expected behavior**
Translations should persist when saved.

**Disciple.Tools Theme:**
- version: [e.g 1.63]
- setup: single site, local

**Device and browser (please complete the following information):**
 - Device: MacBook
 - OS: macos 14.4.1
 - Browser: Chrome
 - Version: 125.0.6422.77

**Additional context**
This seems to work correctly in the old field editor UI.

**Comment by corsacca** [comment]
Fixed by: https://github.com/DiscipleTools/disciple-tools-theme/pull/2513
