### ISSUE TITLE
Quick Action: Contact attempted

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-theme#2549]
**Is your feature request related to a problem? Please describe.**
When attempting initial contact, the seeker ish field had both contact attempted and contact established. The quick actions have no answer and contact established. If you don't change any fields in the record and maybe just write a comment, the update required automation may still be triggered to say an update is needed, even though a comment was written saying something like "sent initial message and waiting for response." There isn't a matching quick action for having sent a message and waiting for a response.

**Describe the solution you'd like**
Add a quick action that matches the seeker path of Contact Attempted.

**Describe alternatives you've considered**
Alternately, it seems like comments should reset the update needed timer. It's possible it already did and our timer is just a bit short.

I also wonder about spring quick actions as a floating action button on mobile devices to making it more easily accessible.

**Comment by corsacca** [comment]
@cairocoder01 It seems to me the "No answer" is the quick action that you are looking for.
It triggers the "contact attempted" seeker path.

Maybe the "No answer" could be renamed to "Contact Attempted"

**Comment by corsacca** [comment]
Here is an issue for comments affecting the update needed trigger: https://github.com/DiscipleTools/disciple-tools-theme/issues/2415

**Comment by cairocoder01** [comment]
@corsacca Sorry for the delayed response on this. I think that changing the semantic meaning of No Answer would work. It currently gives the indication that it's only for phone communication, but changing it to "Contact Attempted" would make it more generic and applicable to various messaging options. I think that would be a good option and resolution to this issue.
