### ISSUE TITLE
New feature: Add group dummy group members 

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#323]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [corsacca](https://github.com/corsacca)**
_Thursday Oct 26, 2017 at 09:59 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/242_

----

Add the ability to quickly add group members from a group record.
These group members could be contacts or be easily turned in to contact.

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Friday Oct 27, 2017 at 11:58 GMT_

----

@corsacca One thought I think we need to consider is having both named and unnamed members of a group. 
https://github.com/DiscipleTools/disciple-tools/issues/104

I don't have firm ideas on this, but thinking of something as simple as a numeric field on the group record that could track unnamed members. So a group could have 3 contacts and 4 'unnamed' members.

We would have to add a total of these meta fields to the total counts for certain reports. As we get into building the larger movement tracking side of the system, I wonder if building a contact for every known member generations away from the projects team, is feasible. 

I think we can still have groups as a created records, but I wonder about the "trackable limit" to a system like this. At what point does it transition from being a CRM to something like iShare that is a high-level statistic tool?

**Comment by corsacca** [comment]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [corsacca](https://github.com/corsacca)**
_Monday Oct 30, 2017 at 10:01 GMT_

----

They can be represented by a number, or by groups blank rows in the members list. For usability it needs to be clear which contacts are in the group and how many other members there are. It also need to be easy to add information like name, baptism date, etc on a blank member when that info becomes available. At this point i think the record would become a real contact.
Here is our current mockup:
![image](https://user-images.githubusercontent.com/24901539/32165031-a8a13bfe-bd61-11e7-8ec1-02ca7bcc8763.png)

**Comment by corsacca** [comment]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [corsacca](https://github.com/corsacca)**
_Monday Oct 30, 2017 at 10:02 GMT_

----

@ChrisChasm, i don't follow what you mean by "trackable limit"

**Comment by mikeallbutt** [comment]
I think this is now possible by adjusting the number of members field. But what does one do with a visitor to a group?

**Comment by corsacca** [comment]
Extra members are tracked using the member count field:
![image](https://user-images.githubusercontent.com/24901539/105694410-3b558b00-5f01-11eb-8586-e0637e235b52.png)
