### ISSUE TITLE
Metrics: Critical Path Report

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#326]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrisChasm](https://github.com/ChrisChasm)**
_Thursday Oct 26, 2017 at 15:08 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/245_

----

We need to have either a working Critical Path report, or hide the section for MVP. 

- [x] Prayers Network
- [ ] Social Engagement
- [ ] Website Visitors
- [x] New Contacts
- [x] Contacts Attempted
- [x] Contacts Established
- [x] First Meetings
- [x] Baptisms
- [x] Baptizers
- [x] Active Churches
- [x] Church Planters

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Thursday Oct 26, 2017 at 15:08 GMT_

----

https://github.com/DiscipleTools/disciple-tools/issues/146

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Friday Oct 27, 2017 at 11:22 GMT_

----

493270862981e62aa44e1439e865d4af45f024f3

**Comment by corsacca** [comment]
<a href="https://github.com/burntsun"><img src="https://avatars3.githubusercontent.com/u/20836899?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [burntsun](https://github.com/burntsun)**
_Wednesday Nov 15, 2017 at 14:53 GMT_

----

@ChrisChasm What's the current status of this issue?

**Comment by ChrisChasm** [comment]
This issue is done. I finished it for MVP. I opted out of the social and website stats because of the new direction we're going to take that development.
