### ISSUE TITLE
Roles: Strategist Role

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#335]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrisChasm](https://github.com/ChrisChasm)**
_Friday Oct 27, 2017 at 15:54 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/254_

----

Question:
Have we created/implemented a strategist role that lets them see the back end and edit some custom lists… i.e. locations, sources, etc?

Answer: 
The plugin config menu in the admin is governed by the 'manage_dt' capability, whereas the other settings for the admin are governed by the 'manage_options' capability. So we have an easy separation from Strategist vs Administrator. But I have to check / test the strategist role that it is configured for this.

- [ ] Review the strategist role and make sure it has access to the wp-admin, 'manage_dt' capability, and all the post types.

**Comment by corsacca** [comment]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [corsacca](https://github.com/corsacca)**
_Monday Oct 30, 2017 at 16:10 GMT_

----

The current strategist role is able to modify the sources, locations and people groups.

**Comment by corsacca** [comment]
<a href="https://github.com/burntsun"><img src="https://avatars3.githubusercontent.com/u/20836899?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [burntsun](https://github.com/burntsun)**
_Wednesday Nov 15, 2017 at 14:49 GMT_

----

What's the difference between a strategist and a dispatcher?

Could @ChrisChasm or @corsacca update [this help article](http://help.disciple.tools/knowledge_base/topics/what-are-the-different-user-roles-what-does-multiplier-dispatcher-dot-mean)?

**Comment by corsacca** [comment]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [corsacca](https://github.com/corsacca)**
_Thursday Nov 16, 2017 at 15:45 GMT_

----

The strategist is currently not implemented.
@ChrisChasm also created a DT-admin for user management and settings configuration.

**Comment by ChrisChasm** [comment]
Strategist does have the manage-dt capability. 

A: Strategist is a role that allows leadership to view and think through the statistics and where the coalition is going. He/she is not necessarily receiving and routing contacts.
