### ISSUE TITLE
Mobile layout issue: Prevent options handle form wrapping

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#341]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [corsacca](https://github.com/corsacca)**
_Friday Oct 27, 2017 at 16:26 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/260_

----

![screenshot_20171027-111603](https://user-images.githubusercontent.com/24901539/32114576-d4ba066c-bb3b-11e7-83c1-b2e149e2f561.png)

**Comment by grantholle** [comment]
Mine isn't wrapping like this

**Comment by corsacca** [comment]
It does in certain cases.
But let's hold on this one till I do https://github.com/DiscipleTools/disciple-tools-theme/issues/425

**Comment by corsacca** [comment]
Editing now happens in a modal, removing the need for the options handle in the details section.
