### ISSUE TITLE
New feature: Merging two contacts

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#356]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [corsacca](https://github.com/corsacca)**
_Monday Nov 06, 2017 at 09:46 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/275_

----

Aided or prompted by the duplicate checker #248 the dispatcher needs a easy way to merge two contacts. 
The tools needs to take two contacts, merge the fields and delete the duplicate contact. We need to be able to specify which contact will be deleted. Matching or new fields can be merged automatically. Fields with different data need to be combined manually (in a third input/list?)
The tool can be located in the admin panel, but the link needs to be accessible by the dispatcher from the theme.

**Comment by corsacca** [comment]
<a href="https://github.com/burntsun"><img src="https://avatars3.githubusercontent.com/u/20836899?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [burntsun](https://github.com/burntsun)**
_Wednesday Nov 15, 2017 at 14:39 GMT_

----

I would also want to consider a different design that does not delete merged contacts. Instead, it would keep the old merged contacts around, but it would be linked somehow to the canonical contact.

**Comment by bezcreative** [comment]
Mock-up: 
![image](https://user-images.githubusercontent.com/32961877/38723939-98631a26-3efa-11e8-8456-1861b6db4801.png)

https://www.figma.com/file/jlr4RiXe16JTrlSOCHb4bh/Disciple.Tools-use-this-one

**Comment by corsacca** [comment]
Dispatcher page:
![image](https://user-images.githubusercontent.com/24901539/41294680-8cfcf5aa-6e50-11e8-8727-0f8a2caff71e.png)
Link to this page will be in the white bar on the contact details page. Viable only by those that can see all contacts.

**Comment by ChrisChasm** [comment]
This project has been outsourced.
