### ISSUE TITLE
Adding a contact to a group could trigger automatic ticking of “In Church/Group” under progress

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#373]
<a href="https://github.com/burntsun"><img src="https://avatars3.githubusercontent.com/u/20836899?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [burntsun](https://github.com/burntsun)**
_Monday Nov 20, 2017 at 14:06 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/293_

----

> If a contact is listed in a group (under Connections) would it be possible to automatically tick the “In Church/Group” button under Progress?

This is an interesting idea that is worth considering.

**Comment by mikeallbutt** [comment]
For me, and how I use who is in a group, this wouldn't be a good thing. I add people to a group to remind or suggest that they join that group, and not that they are actually in the group. I also use who is in a group lists as I try to form groups.

**Comment by corsacca** [comment]
@mikeallbutt in a collaborative environment it would make it hard for another user to come to that group record and know who was in the group.
I like the idea of a `potential members` field. Would that be something you'd like to request?

**Comment by mikeallbutt** [comment]
> @mikeallbutt in a collaborative environment it would make it hard for another user to come to that group record and know who was in the group.
> I like the idea of a `potential members` field. Would that be something you'd like to request?

Yes as you suggest, a potential members field I think would be useful. It could be made from existing contacts or just a text box where names can be written.

**Comment by jlebouch76** [comment]
I agree with Mike. Sometimes, when I indicate a contact who is part of a group, it could in fact be a "pre-group" (not a real DBS group, but a gathering that could happen with potential POPs). So for me, it will not be good to have an automatic ticking like suggested.

**Comment by mikeallbutt** [comment]
This concept of auto-filling fields, could also be useful to adjust the people groups of a group.
