### ISSUE TITLE
Make activity section easier to read

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#382]
<a href="https://github.com/burntsun"><img src="https://avatars3.githubusercontent.com/u/20836899?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [burntsun](https://github.com/burntsun)**
_Monday Dec 18, 2017 at 15:30 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/302_

----

Here are some ideas:

- Stop using italics
- Use bold to separate the part before the colon and the part after the colon in a single line
- Use the quick action icons

**Comment by micahmills** [comment]
This issue is pretty old. Is it still relevant and are we getting complaints about the readability of the current design?
