### ISSUE TITLE
Display social media urls as links in display mode.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#395]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [corsacca](https://github.com/corsacca)**
_Thursday Dec 21, 2017 at 13:28 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/315_

----

![image](https://user-images.githubusercontent.com/24901539/34257663-17354ee4-e65b-11e7-9e63-ea5cc3a28f01.png)
If the entry is a link, make it clickable when not in edit mode.

**Comment by corsacca** [comment]
![screenshot from 2018-04-29 21-26-22](https://user-images.githubusercontent.com/24901539/39410690-3a278698-4bf4-11e8-958a-dbc5ff5d81e9.png)

**Comment by mikeallbutt** [comment]
@corsacca this functionality has been removed in version 1 of the theme. But it was very helpful, so can we please have it reinstated.

**Comment by corsacca** [comment]
Oh. Great catch.Opened i new issue.
