### ISSUE TITLE
Create the ability to favorite or star contacts.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#402]
Have the stared contact appear in the contacts list filters.

**Comment by mikeallbutt** [comment]
This feature would be very useful in the app also.

**Comment by mikeallbutt** [comment]
This idea needs a mockup. I will have a go at it. Any suggestions from others about this and where the star could be used and seen?

**Comment by corsacca** [comment]
On the top bar possibly.

**Comment by mikeallbutt** [comment]
> On the top bar possibly.

Yes, because this will be part of navigation, on the top bar next to the 'add new icon' might work.

Where to display and set the 'star' should be in the details tile (for contacts and groups) and probably on the left side of the user/group name.

**Comment by mikeallbutt** [comment]
> I was thinking next to the Follow button.
> Next to the contact/group name could work too.

That would be a great spot. That is where this type of feature often is ie. Google Contacts.
It would also be useful to have the star to the left side of the name or group on the list pages. That way as you are looking through the list you can click if you want them starred or not, and save going to their individual contact page to apply it.

This feature is needed. Using tags is ok but is system wide. Others can see what theya re tagged as and if you create a tag like 'Star' then someone else could remove it.

**Comment by mikeallbutt** [comment]
In the header area near the "add new" and "notifications" icons there could be an icon for a "Pin" that opens a page that has a list of things that have been pinned. These could be:

- contacts
- groups
- trainings
- searches
- saved metrics/ results

**Comment by corsacca** [comment]
This feature will be depend on: 
https://github.com/DiscipleTools/disciple-tools-theme/issues/1270
