### ISSUE TITLE
Requiring Psalm 119 plugin

### ISSUE THREAD

**Issue by grantholle** [DiscipleTools/disciple-tools-theme#405]
While it is nice, should this plugin actually be required? Seems like unnecessary bloat

**Comment by ChrisChasm** [comment]
Agreed. That was an experiment to understand publishing in the WordPress directory and seeing the analytics they provide. Totally not necessary any more.

**Comment by corsacca** [comment]
Cool. We should remove it.

**Comment by ChrisChasm** [comment]
Removed.
https://github.com/DiscipleTools/disciple-tools-theme/commit/de6d0161aa845fccb16344460e3684bba531ec64
