### ISSUE TITLE
Where did this old_key column come from?

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools-theme#410]
I'm confused on this migration. Is there supposed to be both old_value and old_key? If so where is the add for the old_key and where is the drop for the old_value?

https://github.com/DiscipleTools/disciple-tools-theme/blob/b195eda67d193e86ae94b326d22d0306f55bbd5b/dt-core/migrations/0001-add-activity-column.php#L12

https://github.com/DiscipleTools/disciple-tools-theme/blob/b195eda67d193e86ae94b326d22d0306f55bbd5b/dt-core/migrations/0001-add-activity-column.php#L44

**Comment by corsacca** [comment]
@ChrisChasm you are right. I messed that one up.
