### ISSUE TITLE
Add help on what/how to name a new group.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#420]

**Comment by corsacca** [comment]
@ahillbilly what is our group name convention?

**Comment by mikeallbutt** [comment]
> @ahillbilly what is our group name convention?

What are you meaning? You want a help modal suggesting how people should name the groups?

This is what the [documentation](https://disciple-tools.readthedocs.io/en/latest/Disciple_Tools_Theme/getting_started/groups.html#group-details) says.
