### ISSUE TITLE
Consider using resources not hosted by Google

### ISSUE THREAD

**Issue by grantholle** [DiscipleTools/disciple-tools-theme#444]
While there are obvious benefits of using resources from a CDN, where I am, I cannot load the page because it's trying to load jquery from Google. Something to consider

**Comment by corsacca** [comment]
@grantholle is https://cdnjs.com good?

**Comment by grantholle** [comment]
Great!

**Comment by corsacca** [comment]
These can be changed in /dt-assets/functions/enqueue-scripts.php
