### ISSUE TITLE
Bulk action Functionality

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#454]
- [x] Bulk assign-to
- [x] Bulk update needed
- [x] Update needed

**Comment by ahillbilly** [comment]
Bulk share/follow functionality is also needed

**Comment by mikeallbutt** [comment]
Within the WP Admin there is this ability to bulk adjust contacts. I think it might be a good place to add this functionality to also adjust things like Sources, tags and assigned to etc.

![Screenshot 2020-05-05 11 19 39](https://user-images.githubusercontent.com/43966676/81089930-9f8f7500-8ec2-11ea-9a42-0f1ee168ddaf.png)

**Comment by corsacca** [comment]
For this feature i would suggest using the existing filtering ui to create a list to update.
We need a UI for selecting the action to apply (set status, assigned to, tags, sharing, etc)
We can either apply the action to all the records match the filter ( even if 1000s )
Or we can add checkboxes or the user to select which records to update ( 0 - 100 unless more records are loaded in the list )

**Comment by micahmills** [comment]
With the coming release of the updated contact-types I thought having a bulk edit feature would be a good addition. So I have started to brain storm how this might work and look. Here is what I am thinking and I would be interested in your feedback.

Add "Bulk Edit" button next to the new "Fields" button. That will add checkboxes next to all the contacts/groups that are showing and open up a box similar to the "Fields" "Choose which fields to display" box. In that box I am thinking of putting some major items like assign/subassign, Share, Follow, Updated Needed, Change Status. Are there any other things that we would consider high traffic things that need a bulk edit? Ideally, all fields would be available for bulk editing, but I don't think that needs to be front and center. It could be hidden away behind an options button. 

Once the options are selected it will loop through all the checked boxes on the contacts/groups and update them. This will limit the update to only what is on the screen at 1 time. This keeps us from running a really long process to update potentially thousands of records. 

Does that seem reasonable to you guys? Are there things that need to be added?

**Comment by corsacca** [comment]
Those are great elements to start with! We can modularize it and make whole field types available (key_select, multi_select, connections...) as v2.
Other field to bulk update: Contact type, location, group, coach, tag.
The update strategy sounds good.

**Comment by corsacca** [comment]
Some of these won't apply if the access module or the dmm module and disabled.

**Comment by micahmills** [comment]
Hello gentlemen, I have created a PR for bulk editing. If you guys could take a look at it and let me know what you think.

https://github.com/DiscipleTools/disciple-tools-theme/pull/1077

**Comment by corsacca** [comment]
The PR has been merged. Thank you @micahmills for your hard work!

**Comment by corsacca** [comment]
See https://github.com/DiscipleTools/disciple-tools-theme/issues/1090 for locations field.
