### ISSUE TITLE
Add a button to 403.php page to request access to a record

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools-theme#477]
If we follow a link to a resource, like a group or contact, that we don't have access to, we go to a 403 page. On this page, we should add a button to request access. 

User case: A contact is assigned to you but the group has not been assigned to you. Right now there are a number of places where that group link shows up, but if you click it you go to a 403 page, because you have not been given access or sharing to the group.

User case: If you have access to a group, but not access to all the group members records. This will also bring you to a 403 page. 

Suggestion: We can create a button that submits a request from the current user and logs a request comment to the activity of the group/contact and creates a notification to the owner of the group/contact with a link to the sharing tool.

**Comment by ChrisChasm** [comment]
Use the Update Needed/Accept Contact template

**Comment by mikeallbutt** [comment]
Is this is message that needs to be improved?

<img width="673" alt="Screenshot 2019-12-05 19 54 29" src="https://user-images.githubusercontent.com/43966676/70292076-a6467e80-17a2-11ea-8c28-d3d429c8f182.png">

**Comment by corsacca** [comment]
We need a button that sends a notification to the assigned_to to grant permission.

**Comment by mikeallbutt** [comment]
> We need a button that sends a notification to the assigned_to to grant permission.

A button with the phrase "Request permission from your administrator" that once clicked, sends the notification and also gives the user a visual modal message that a notification has been sent, and to wait for approval. Maybe offer them the next action like return to their groups list.

**Comment by kodinkat** [comment]
## Analysis Summary

On encountering a 403 Permission Denied page, user's resource access request flow to be as follows:

1. 403 Page to be updated, so as to include a request button, with the caption `Request Permission From Resource Owner`
2. Once clicked, request button to display a request confirmation modal message; informing user, resource owner is to be notified of request.
3. Resource access request to be sent to resource owner, once model message confirmation has been given by the user.
4. Resource access request to be logged on group/contact activity stream.
5. Resource owner will also be notified of request and prompted to grant (or reject) access via the sharing tool.
6. User to be notified of request access decision via their activity stream and dispatched email.

**Comment by corsacca** [comment]
@kodinkat that looks right. I like the flow. Thank you.

1. We use the work `record` instead of `resource`
6. this should happen automatically when the record is shared.
