### ISSUE TITLE
Translation: Add customizable label section to the Admin Settings

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools-theme#478]
There are a number of labels that we might want to expose on a Settings Tab in WP Admin. 

Suggestion: There are translation plugins that expose all the translation strings inside the WP Admin, and allow you to create translations and save them without using POEdit. This might be beyond what is needed, but it might be possible to suggest something like this for heavy modification.

Suggestion: A lighter solution would be to identify key strings that people will want to modify and expose those in the Settings Tab.

**Comment by mikeallbutt** [comment]
Yes I agree. This would be a good thing. for example, I have adjust the wording in the seeker path but the changes don't reflect in the fast filters section of contacts.

**Comment by micahmills** [comment]
I believe we have solved this as well with #950

**Comment by corsacca** [comment]
I think this issue could be extended to all strings instead of just the fields, but i don't think we want to head in that direction.
#950 deals with the most commonly used strings suggested here.
