### ISSUE TITLE
Make phone, email, and address links in contact and group details page

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools-theme#479]
- [x]  I think we should make the phone numbers a link (tel:) so that you can click them on a phone and begin a call. 
- [x] We should make the email a link (mailto:) so that you can click it an open up your email client. 
- [ ] We should make the address a link (pre-make link to Google maps, or maybe a modal window that dynamically calls Google maps with with a pointer for the locations)

**Comment by corsacca** [comment]
https://github.com/DiscipleTools/disciple-tools-theme/pull/596 for phone and email

**Comment by corsacca** [comment]
The address one will require loading even more resources on the contact page. A link to google maps might work better
