### ISSUE TITLE
Move the `Address` up from below the `Show more` section.

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools-theme#480]
I'm personally finding myself expanding the show more section all the time to look at the address. This seems like a key part of information. 

Suggestion: Can we set a global preference for each user to permanently toggle the show more or note. We can saye it to their user record and display it in the profile, but if we intend to keep the show more logic, could we make the preference permanent per user.

**Comment by corsacca** [comment]
@ChrisChasm check the changes i made to the contact details section. I think you will like them :)
