### ISSUE TITLE
Build availability section in the Contact Details page

### ISSUE THREAD

**Issue by rtendesign** [DiscipleTools/disciple-tools-theme#481]
Here's the mock-up: 
![image](https://user-images.githubusercontent.com/32961877/38665468-5e1bf5ca-3e34-11e8-91a8-bf4e79c4d202.png)

The blue, active buttons mean that is when the contact is available. For example, this contact is available on Thursdays in the mornings and at night and also on Fridays around noon/lunch.

Here's a link to the mock-up on Figma: https://www.figma.com/file/jlr4RiXe16JTrlSOCHb4bh/Disciple.Tools-use-this-one

**Comment by corsacca** [comment]
This feature is now available with this plugin: https://disciple.tools/plugins/disciple-tools-availability/
Thanks @prykon
