### ISSUE TITLE
Nonce in js times out

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#507]
Trying to update a contact and i get:
{"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
This usually happens after being away from the page for a while.

**Comment by ChrisChasm** [comment]
I think a nonce should time out. I think we might consider a step inside the error response that might check for the situation where someone has had their browser open for half a day and then wants to continue on an update.

I believe the nonce has a 24 expiration window, which seems reasonable for most situations.
https://pantheon.io/blog/nonce-upon-time-wordpress

Thoughts.
