### ISSUE TITLE
Comments: like, favorite or react to a comment.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#537]
**Purpose**: Add clarity and usability to the comments area.

**Benefits**:
- Reactions will visually show that a user has seen the comment without having to write a whole reply.
- Reactions will allow the user to quickly scan the comments to find the most importand ones.
- Reactions will improve communication by allowing users to easily respond to any comment.

**Requirements**:
The user can react to any comment on a record.
The user can choose between 6 options of reaction.
If a comment has reactions they will be displayed under the comment. Each reaction icon with a number associated to it.
If the user hovers over (or clicks on for mobile) the reaction icon, it will show a list of users who reacted.
Default  reaction options (same as Facebook):  thumbs up, heart, laugh, wow, sad face, angry
Customization: add filters to allow for a plugin to add or remove from the list.

**Code considerations**:
Start with `dt-assests/js/comments.js`, `dt-assets/parts/loop-activity-comment.php`, `dt-posts/dt-posts.php` and `dt-posts/dt-posts-endpoins.php`
Reactions will likely be stored in the comment meta. This feature will need to extend the existing comment functions to include getting meta data.

**Comment by mikeallbutt** [comment]
A simple system like what GitHub uses would help.

<img width="153" alt="Screenshot 2020-07-14 13 16 22" src="https://user-images.githubusercontent.com/43966676/87461730-6d8e4380-c5d4-11ea-9089-8b973dd3a434.png">

**Comment by squigglybob** [comment]
How would users un-react to a comment? If clicking on the reaction shows the users who have reacted, should picking the same reaction again, unreact it?  In github, clicking the reaction unreacts it, and hovering shows the users... :O/

**Comment by squigglybob** [comment]
also where best to put the reaction dropdown button? underneath the comment? or to the right of the comment?

**Comment by corsacca** [comment]
Good questions @squigglybob ,
Here is a guess, tho i'm up for it being improved:
- click on a reaction to "un-react"
- show the reaction under the comment
- I don't know where the reaction dropdown best fits. Actions that appear when you hover of the text make sense, but won't work on mobile.

**Comment by squigglybob** [comment]
Yup, that's what I'm thinking, I can either put the dropdown button underneath 
![image](https://user-images.githubusercontent.com/9816214/112653487-60ee0a80-8e46-11eb-91ef-3536ebd1ea93.png)
or to the left 
![image](https://user-images.githubusercontent.com/9816214/112653826-b6c2b280-8e46-11eb-82ff-f6f52947ce5a.png)

**Comment by corsacca** [comment]
I think underneath next to edit and delete (when they are present) will work the best.
An icon with a plus on it like on slack would be nice.
I didn't see a good one on https://thenounproject.com/ where a lot of our icons have come from
