### ISSUE TITLE
Choose default display name when users are created

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#557]
If a user is created with a the first and last names filled out, then the display name will automatically be the first + last name.
We need a setting to configure this.

**Comment by mikeallbutt** [comment]
I suspect this is no longer going to be needed if there is only one field for name.

**Comment by corsacca** [comment]
@mikeallbutt this is on the user, not on the contact.
When creating a user the Admin can enter First and Last name and email address. 
The name of the user that appears in the theme is the display name, which is created from the first and last name. The user can change his display name in the settings, but it would be nice for the Admin to be able to set the display name to something other that the first and last nome when creating the user.

**Comment by mikeallbutt** [comment]
> but it would be nice for the Admin to be able to set the display name to something other that the first and last nome when creating the user.
> 
I agree. Currently all my new users get their email address as their display name and that is normally very "ugly".

**Comment by mikeallbutt** [comment]
@corsacca Until this issue is fixed, I do all my user creations in the WP-admin area so that I can control the user name. Having this fixed will allow others who don't have access to WP-admin to make users from contacts and not have the new user have a username they weren't able to choose/modify.

**Comment by corsacca** [comment]
@mikeallbutt sounds like you are requesting a different feature (setting or changing the username). Since this issue is related to the display name (not the username) we request you create a separate github issue for your request.

**Comment by mikeallbutt** [comment]
The `Display name` field could be added to the `Extra Disciple.Tools Information` area in WP admin like it is available in the modal.

![Screen Shot 2020-09-08 at 9 33 16 am](https://user-images.githubusercontent.com/43966676/92490393-971fb180-f1b6-11ea-89fb-5c49565d47f3.png)

**Comment by corsacca** [comment]
This no longer seems important.
