### ISSUE TITLE
When a user changes their display name, update the contact associated with them.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#558]

**Comment by corsacca** [comment]
@TheEvilTopHat, sorry this issue should have been closed already. It was referencing updating the contact that represents a user. But it seems we already did that with the `add_action( 'profile_update', [ &$this, 'profile_update_hook' ], 99 );`

I like what you did with replacing the text in the comments. Though the @mentions already go off and get the right display name if it updated.
Also, if there is someone named Hope, all the comments saying "Hope it works out..." would be changed.
Can you remove the part that replaces the names in a comment?

**Comment by TheEvilTopHat** [comment]
Sure thing I'll change it so that it takes it away
