### ISSUE TITLE
Notifications: more control

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#565]
On the user's profile/settings page.
Separate notification control for "my" contacts and contacts shared with me.

**Comment by ahillbilly** [comment]
From user:

I still get emails that look like this, it would be great if the Assigned User name was included in this message as well, as I can't tell the difference between emails meant for me and emails meant for someone else.

Current notification:

> An update is requested on [CONTACT NAME].

I would like instead:

> @[MULTIPLIER NAME], an update is requested on [CONTACT NAME].
