### ISSUE TITLE
Plugin: Meeting tracker for Groups

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#569]
- Record meeting attendance for each member 
- record meeting content and member reactions
- for attending members add note on contact's record for the meeting.

**Comment by jlebouch76** [comment]
Thanks this is exactly what I need! I will wait.

**Comment by jlebouch76** [comment]
Another thing that would be useful would be to save the story or Bible passage that was discussed.

**Comment by jlebouch76** [comment]
Another thing that would be useful would be to save the story or B passage that was discussed.

**Comment by mikeallbutt** [comment]
Also, ability to write about the next meeting and schedule the next meeting that also links to the notification system.

**Comment by micahmills** [comment]
See #996 for other things to include with a meeting tracker implementation.

**Comment by micahmills** [comment]
This issue is a bit more complex and @corsacca and others have started some work on this. If you want to jump in and tackle this one @corsacca can get you the code he has written and you can work off of that.

**Comment by corsacca** [comment]
Here is some starter code form the meetings tracker:
https://github.com/DiscipleTools/disciple-tools-meetings

**Comment by corsacca** [comment]
This plugin in implemented: https://disciple.tools/plugins/mettings-tracker/
