### ISSUE TITLE
Notifications: group notifications by contact or group id on the notification page.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#601]
**Purpose**
Simplify the notifications page by grouping the records by id. The notifications list can be a chore to go through if there are 5-10 notifications all for a single record.

**Benefits**
- Cleaner notification page
- More clarity on activity that happened for a specific record

**Requirements**
- Group notifications for each record together.
- Don’t group notification across multiple days. Keep days as separate rows
- Notification row: the record name as the title or header
- Notification row: a list of all the notification on the record for that day.
- Each notification still has a read/unread status

**Code considerations**
Start with `dt-assets/js/notifications.js`,  `dt-notifications/notifications-endpoints.php` and `template-notifications.php`
We expect most of the feature to be front end changes. But extra information may be needed from the API.

**Comment by cairocoder01** [comment]
Not sure if this is the same feature or something different.

As an admin user, I get a lot of email notifications for updates on groups - often multiple notifications for the same group/contact per day. I don't want to turn them and miss what's happening, but I would like to have them batched together to come less often than in real-time.

It would be nice to have a user preference that can specify the frequency with which someone would like to receive email notifications. Options I can think of are real-time (current, I think), hourly, or daily. This can keep people notified while not flooding them with emails for every change.

**Comment by corsacca** [comment]
Great suggestion @cairocoder01,
I think we have 2 issues here
- the display of notifications on the notifications page
- the sending of notification emails, which could be batched instead of sent in real time.

**Comment by corsacca** [comment]
Created: https://github.com/DiscipleTools/disciple-tools-theme/issues/724

**Comment by corsacca** [comment]
Description updated.

**Comment by squigglybob** [comment]
Hi, i'll take this one :O)

**Comment by squigglybob** [comment]
Would something like this look ok?
![image](https://user-images.githubusercontent.com/9816214/112465649-dd0c2380-8d5c-11eb-847a-275a51625e80.png)

**Comment by corsacca** [comment]
Thanks for the screenshot!
Yes! let's go with that.

**Comment by squigglybob** [comment]
Hopefully that's good to go... @corsacca
