### ISSUE TITLE
Set primary contact location

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#624]
A contact can have multiple locations.
One needs to me marked as primary for reporting purposes.

**Comment by mikeallbutt** [comment]
It might be good to be able to set a default for the location in the DT admin area. In my situation nearly all the contacts are in this town.

**Comment by mikeallbutt** [comment]
> @mikeallbutt are you saying that you'd want every contact created in your system to be automatically in a certain location unless specified otherwise?

Correct - that is what I was thinking.

**Comment by mikeallbutt** [comment]
> It might be good to be able to set a default for the location in the DT admin area. In my situation nearly all the contacts are in this town.

@corsacca I think this is now sort of available in the: settings > Multiplier Preferences > Locations you are willing to be responsible for

**Comment by corsacca** [comment]
We are looking for the primary "Contact" location if there are multiple set. The "User's" locations shouldn't affect this.

**Comment by corsacca** [comment]
Having a "primary" location is no longer a felt need.
