### ISSUE TITLE
Ability to clear date pickers.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#643]

**Comment by chancecox** [comment]
Which datepickers?  the baptized one worked fine for me. can you screenshot?

**Comment by corsacca** [comment]
@chancecox once you add a baptism date, you can't then remove it. You can select the text, and deleted it but it does not trigger an update. 
This is the same for the 3 dates boxes on the group. And any custom date field added from the wp-admin.

**Comment by mikeallbutt** [comment]
This issue has been around for a longtime. I wonder if @blachawk could help get it sorted?

**Comment by corsacca** [comment]
Example: 
![image](https://user-images.githubusercontent.com/24901539/70112481-cb79a680-1655-11ea-97a9-225685773e77.png)

Date pickers that need to be clearable:

- [ ] Baptism Date on the contact record. Clicking clear should send an API call to delete the baptism date 
- [ ] In custom date fields added from the D.T settings. See render_field_for_display() in dt-contacts/contacts-template.php
- [ ] Start Date, Church Start Date and End Date in the groups edit modal

**Comment by mikeallbutt** [comment]
Thanks @corsacca , so is there a place where the right type of code is already in place that can be used/copied to make this work?

**Comment by corsacca** [comment]
No, that is why it is a feature to implement.

**Comment by blachawk** [comment]
It appears that changing the date value works.  Removing it completely does not.  I feel confident I can solve this issue. If that sounds right, please feel free to assign this feature to me.

**Comment by mikeallbutt** [comment]
What would be good and look nice would be to have the date display in a box like the what is in the who 'Baptised By' field, with a X to the right of the date, that when pressed, it deletes the date.

![Screenshot 2019-12-04 12 33 13](https://user-images.githubusercontent.com/43966676/70170574-8f186b80-1692-11ea-8d6a-d86cf11603b8.png)

Another option is to have the word 'Clear' but that doesn't looks as good IMO.

**Comment by blachawk** [comment]
@mikeallbutt  what you are suggesting is right.  [But its not offered OOTB with ui-datepicker at the moment](https://github.com/OfficeDev/office-ui-fabric-react/issues/2725). 

We are going to have to a custom javascript hack for now. But the good news is that I found where the code needs to be modified in the javascript.  

Whats going on is that we are sending a `rest_api.update_post()` only when a date is selected. **We also** want to send a null value when the field is clear via keypress, [like this](https://stackoverflow.com/a/12649952/957186).

Working on it...

**Comment by blachawk** [comment]
Team, I have a plan, thanks to @corsacca on getting a button implemented. 
Also,  @mikeallbutt, I have a *potential* fix for the timezone bug we found yesterday.  I'll wrap all this up in a single branch shortly.
