### ISSUE TITLE
Spanish Español translation

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#652]
Here is the first Spanish translation of the 999 strings.
[ES Archive.zip](https://github.com/DiscipleTools/disciple-tools-theme/files/2595419/ES.Archive.zip)

**Comment by corsacca** [comment]
@mikeallbutt i've uploaded it in this commit: https://github.com/DiscipleTools/disciple-tools-theme/commit/bdd920f3a0c32a8d91cc6aa8fdbf6cbcb3f76779

**Comment by mikeallbutt** [comment]
Thanks - just make sure the files are named es_ES.po and es_ES.mo

**Comment by corsacca** [comment]
@mikeallbutt great catch. They are update now.
