### ISSUE TITLE
Reduce Translations Strings from Admin Area

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools-theme#663]
Suggestion: After looking at the amount of translation strings coming from the administrative area and the complexity of those strings, the proposal is to support multilingual only in the user interface and not in the admin area. @corsacca  and @ChrisChasm 

Con: This would require the administrators of the system to be multilingual having English.
Pro: This would reduce the amount of complicated and rarely used translation strings AND thereby encouraging volunteer translators to help out.

This issue is mostly a documentation of this development decision.

**Comment by corsacca** [comment]
This removes about 300 strings https://github.com/DiscipleTools/disciple-tools-theme/commit/1e830ebaae2b5225e804118a089746c7e267d1a7

**Comment by corsacca** [comment]
The Decision: for we won't go out of our way to translate the admin area. We'll exclude the strings form the base disciple_tools.pot 
We'll still write our code in a translatable manner: with __( "string", "disciple_tools ) or equivalent so we can easily add the files later.
