### ISSUE TITLE
Always available advanced global search feature.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#669]
Have a search icon available in the tap bar from anywhere on the site.
This will open a modal/overlay that lets you quickly search. You need to choose is you are searching in contacts or in groups. 
Needs to be available on desktop and on mobile.

**Comment by corsacca** [comment]
Something like this:
![screenshot from 2019-02-20 15-32-39](https://user-images.githubusercontent.com/24901539/53099139-7127b300-3525-11e9-81b7-8854b2770c09.png)

**Comment by corsacca** [comment]
Include where to search:
- everywhere
- comments
- texts fields 
- Contact info fields
etc

**Comment by corsacca** [comment]
Search in code for  `dt_search_extra_post_meta_fields` filter for current search implementation

**Comment by grantholle** [comment]
Will try to take this on

**Comment by corsacca** [comment]
Awesome! :)

**Comment by grantholle** [comment]
So you want the user to be able to specify the area in which to search?

An alternative I am thinking is just input that searches everything, then organizes the results into the different types (groups/contacts) based on results that were found anywhere

**Comment by corsacca** [comment]
I like this idea. It could be more powerful. It might require we build a search api that returns the correct info.
It will be best if the organization distinguishes where the result came from. Something like this?
Contacts > Comments
- contact 1
- contact 2
Contacts > Custom Text Field
- contact 2
Groups > Comments.
- group 1

**Comment by grantholle** [comment]
Yeah that's kind of what I was thinking

**Comment by mikeallbutt** [comment]
Looking forward to having this available. Currently if I am viewing a group, I have to click to the lest of contacts then do a search to find a contact.

**Comment by corsacca** [comment]
This issue has been started, but work has been paused. Anyone can continue from the pull request: https://github.com/DiscipleTools/disciple-tools-theme/pull/727

**Comment by mikeallbutt** [comment]
This is a feature that we really need. It is beyond my current abilities, but would give it a go if I could. I really hope someone (@blachawk?) with the right skills can get this completed asap.

**Comment by corsacca** [comment]
Icon opens the search modal.
The user types anything in the search modal
This could search the post names, post meta and comments for results
Have options to narrow the search on the side (exclude comments, only search contacts etc)
List out the results including name, post type and matched field.
Make it look awesome! :)

We'll need to build out a separate endpoint for this global search since the current ones rely on the post type being specified.

**Comment by micahmills** [comment]
The current function that creates the SQL and searches the DB is at https://github.com/micahmills/disciple-tools-theme/blob/fde30ca24e8aab52595278a5807ead46673f0610/dt-posts/posts.php#L911 

I think it would be possible to modify that to allow for searching in all posts if a post type is not specified. We could then keep backwards compatibility with the current search implementations and API, and allow for a global search using the same function. As @corsacca said we will need a new API end point for this.

**Comment by corsacca** [comment]
Using the current `search_viewable_post` would save us from having to re-implement the permission checking structure.
Permissions are based on the post_type tho, so it would be hard to remove the post_type param. Going this route would probably mean calling `search_viewable_post` separately for each post type.
