### ISSUE TITLE
Rename default list filters

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#675]
User would like to rename the default filters on the list page.  Specifically when they rename a status label (ie. Dispatch Needed => Ready for Dispatch) they'd like to change the name of the default filter to match.  Currently default filter names are hard coded.

Note: Default filters are not always one to one matches with status labels.  Some of the default filters have multiple components to create the filter.

**Comment by corsacca** [comment]
The filters now take their values from the field labels.
Filters can also be added to and changed from plugins via filters.
