### ISSUE TITLE
Make table column headers on list page mirror the dynamic field labels set in customizations.

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#676]
Field names are able to be relabeled in the customizations section.  These changes are not reflected in the header of the table on the list page as the headers are currently hardcoded.  They should be dynamic to reflect customizations.

**Comment by corsacca** [comment]
see https://github.com/DiscipleTools/disciple-tools-theme/issues/684 as well

**Comment by corsacca** [comment]
No longer an issue.
