### ISSUE TITLE
Duplicate detection UI upgrades

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#683]
Use cases: 
1. It would also be useful to have a very easy to find link to the real record in a duplicate, rather than just a comment in the comment feed.

2. Sometimes, even though a contact record has been closed as a duplicate through the new duplicate process, the button "Go to duplicates is still displayed".

Recommendations: 
1. Use blue notification banner (like the one used for transferred contacts via site to site linking) to notify that a closed record is a duplicate of another record and link to that record.

2. Make sure merging removes potential duplicate note from both contacts.  Note: there is still the potential that both merged records have another duplicate triggering this in a 3rd record, but this notification should only be displayed on the master of the two merged records, not on the one that has been closed as a duplicate.

**Comment by corsacca** [comment]
1. Links are implemented
2. The notification goes away.
