### ISSUE TITLE
Make filtered lists page table columns customizable

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#684]
Redesign list pages so that users can select which data fields to include in their lists of records.

Desktop - choosing which columns appear
Mobile view - consider implications or implement limitations of list customization on mobile

**Comment by ahillbilly** [comment]
Additional use case: 
When listing contacts in the search interface, it is not obvious which closed contacts are duplicates and which ones aren't. It would be useful if the close reason was displayed in the list of contacts.

**Comment by ahillbilly** [comment]
Additional component: scroll records without scrolling frame & keeping Header row visible

**Comment by corsacca** [comment]
Implemented in v1.
