### ISSUE TITLE
Lodash is overwritten when Jetpack plugin is installed.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#688]
This keeps the contacts list form loading and also keeps other parts of the theme from working.

**Comment by corsacca** [comment]
produces this error:
```
shared-functions.js?ver=1560414262:105 Uncaught TypeError: _.get is not a function
    at HTMLDocument.<anonymous> (shared-functions.js?ver=1560414262:105)
    at HTMLDocument.dispatch (jquery.min.js?ver=3.2.1:3)
    at HTMLDocument.q.handle (jquery.min.js?ver=3.2.1:3)
    at Object.trigger (jquery.min.js?ver=3.2.1:4)
    at A (jquery.min.js?ver=3.2.1:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js?ver=3.2.1:4)
```

**Comment by micahmills** [comment]
The problem appears to be that Jetpack uses underscore.js which uses the `_` variable like lodash does. So when you try to call the lodash functions they are being mapped to underscore and you are getting errors because their API is different. So We need to find a way to for `_` to be lodash and not be overwritten by underscore.

**Comment by micahmills** [comment]
According to https://make.wordpress.org/core/2018/12/06/javascript-packages-and-interoperability-in-5-0-and-beyond/

> Lodash Global

> 
> By default, Lodash will assign itself on the global scope using the _ name. Since WordPress will continue to bundle Underscore for the foreseeable future (see #43733), the core-registered Lodash adopts an approach similar to the enqueuing of jQuery to avoid naming conflicts. It does so using Lodash’s _.noConflict, assigning Lodash to the global scope as window.lodash. 
> 
> For this reason, if your plugin or theme uses Lodash as a dependency, you should make sure to not cause _.noConflict to be called multiple times in conflict with the core-registered script.
> 
> When using the copy of Lodash registered by core, your code should reference it by the window.lodash global.
> When enqueuing your own copy of Lodash, you should only call Lodash’s _.noConflict under the condition that window.lodash is not already assigned and that the core-registered Lodash will not be included on the page.
> In general, the _ global should be used only to reference Underscore.

With that in mind we should update our JS code to use `window.lodash` instead of the `_` global or move to underscore.
