### ISSUE TITLE
Typeahead clarity - grey out closed contacts from list

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#691]
It is sometimes (though rare) useful/important to have closed records available for selection in typeahead lists.  It would be super helpful as a user to see these closed options grey'd out or distinguished in some way that subtly clarifies that they're closed records, while not drawing greater attention to them than the active records and while keeping them available as a viable selection option.

**Comment by corsacca** [comment]
Thin one is being worked on.

**Comment by corsacca** [comment]
Implemented: #699
