### ISSUE TITLE
Cancel button when creating a contact or group

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#693]
There is no Cancel button/link if someone clicks to create a contact or group but decides not to complete the creation.

**Comment by mikeallbutt** [comment]
![image](https://user-images.githubusercontent.com/43966676/65358534-72a28200-dbbf-11e9-9e46-bbec2664e4fc.png)

**Comment by mikeallbutt** [comment]
Fix for issue #693 This is what it should look like now.

### New contact
<img width="672" alt="Screenshot 2019-10-27 16 19 16" src="https://user-images.githubusercontent.com/43966676/67642864-ca768c00-f8d5-11e9-9ac6-0d2a41413f15.png">

### New group
<img width="672" alt="Screenshot 2019-10-27 16 19 42" src="https://user-images.githubusercontent.com/43966676/67642865-cb0f2280-f8d5-11e9-81ad-e0d335ac2c88.png">

**Comment by corsacca** [comment]
@mikeallbutt small change request: could the buttons be the same size? I don't think we have anywhere else in the theme that that mixes 2 button sizes.

**Comment by mikeallbutt** [comment]
> @mikeallbutt small change request: could the buttons be the same size? I don't think we have anywhere else in the theme that that mixes 2 button sizes.

Technically that can be easily done (remove the class of small) but I did that sizing difference to help users see that the main choice they should make is not to cancel.
(I also think it looks good smaller ;) )

**Comment by corsacca** [comment]
this is also an option.
![image](https://user-images.githubusercontent.com/24901539/69624799-a1b4f400-1045-11ea-9234-027af4bc4721.png)
