### ISSUE TITLE
All text available to be translated

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#694]
Although it might be easy to hard code text into DT code, it make is hard for non english speakers to use DT. So, place hooks at all places where text is displayed so that it can be translated into other languages.

**Comment by micahmills** [comment]
hey @mikeallbutt I think this is largely taken care of, but wanted to check if there are any known places that aren't marked for translation.

**Comment by mikeallbutt** [comment]
Until we get the next merge of the translations operating in DT, I won't be able to confirm. But I think it is all good though.
