### ISSUE TITLE
List Filters: Exclude/not filter

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#695]
The one thing I would be very useful would be to have the ability to find people that aren’t listed. eg.  I want to see a list of contacts who are baptised but aren't baptising.

**Comment by mikeallbutt** [comment]
This is a feature that will be very helpful. I hope someone can work on it soon. It is beyond me abilities to work on.

**Comment by corsacca** [comment]
@mikeallbutt can you provide a few mokups for the UI for a few of the different filter pages?
One challenge is that "not" is difficult to make intuitive

**Comment by mikeallbutt** [comment]
An example of what would be useful is like what is here in the `People Groups` field. It is possible to filter for one or more people group/s but what if you want to find which records don't have a people group set? You might want to do this so your records/data is accurate.

![Screen Shot 2021-05-26 at 16 32 13](https://user-images.githubusercontent.com/43966676/119734035-fc4c2d80-be3f-11eb-8eca-1c9ad56e3e56.png)

So like in the attached image, having a box or toggle to flip the type of filter from `with` to become `without` whatever is being searched for.

**Comment by corsacca** [comment]
It think we can limit this one to the "connection" field type.
