### ISSUE TITLE
adjust the date of an entry of the comments area

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#696]
I sometimes need to adjust the date of an entry in the comments section. This might happen when I attend a meeting or meet with someone but don’t get a chance to log the interaction that same day. If I could adjust the date I wouldn’t have to write when the interaction happened (ie. the other day or yesterday etc).

**Comment by corsacca** [comment]
@mikeallbutt it is not generally assumed that a comment means that the activity happened at that exact moment.
Changing the time might even add confusion if another user logs in and and sees no comments. But then later sees that there was a comment posted and dated to before he last checked. This also would result in a distrust of the D.T system.
Would there be a different way to achieve the workflow you described?

**Comment by mikeallbutt** [comment]
> @mikeallbutt it is not generally assumed that a comment means that the activity happened at that exact moment.
> Changing the time might even add confusion if another user logs in and and sees no comments. But then later sees that there was a comment posted and dated to before he last checked. This also would result in a distrust of the D.T system.
> Would there be a different way to achieve the workflow you described?

Thanks @corsacca for explaining your other reasons. Not sure yet what other way there is to achieve the outcome I was hoping for, without making the comment area complicated with a date changer.

**Comment by corsacca** [comment]
@mikeallbutt I wonder if a contact meeting tracker might be what you are looking for. I don't know what that would look like. The easier and most simple is just to say "we met yesterday, did x and talked about x".

**Comment by Ferny-Gomez** [comment]
A User mentioned: I have a user asking about setting a date for quick actions. For example, he is recording actions that took place a few days earlier, but it is recorded as happening today. I also have thought it could be useful to be able to override the date for those actions (and possibly have more info attached). Anyone else have this desire too?

**Comment by corsacca** [comment]
The comment date is meant to indicate when a comment was made by a user. Not when a certain activity happened.
For changing quick action dates, see https://github.com/DiscipleTools/disciple-tools-theme/issues/1131.
When we have a meeting tracking, changing the date will be included in the options.
