### ISSUE TITLE
Translation: Set the default language for a site.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#697]
So that the new users don't all have to go change their language.
Also, if possible, so that user invitation go out in that language.

**Comment by mikeallbutt** [comment]
This would be useful in my context of how I use DT. 

It could be a multi-select field that is accessed on the users profile page.

**Comment by corsacca** [comment]
@mikeallbutt the language select is already available on the user's profile page.

**Comment by mikeallbutt** [comment]
> @mikeallbutt the language select is already available on the user's profile page.

When I invite a contact to become a user, having the option to preset their language would be useful so that the invite message goes out in the correct language. So, having the language set for a contact could be helpful.

**Comment by corsacca** [comment]
Ok, so this would be in addition to having a default language. 
The form in the wp-admin that is used to invite users and the modal on the contact  record under dispatcher tools could have this select.
A user's profile page (/settings) and a user's contact record are currently separate.

**Comment by micahmills** [comment]
I believe that Pull Request #914 fixes the initial issue presented by corsacca. 

You can set the default language in the wp-admin Site Settings ->General menu and then each user can have their own language selection option, but the default for the user is the site default. New user emails will go out in the sites default language.

**Comment by corsacca** [comment]
Looks like #914 solves the issue. Thanks @micahmills!
