### ISSUE TITLE
Contact Record: Allow adding custom fields to the progress tile.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#701]

**Comment by mikeallbutt** [comment]
Having the ability to move things around would be great. It would be good to be able to merge customs tiles into the `Other` tiles where tags are displayed.

**Comment by corsacca** [comment]
> Having the ability to move things around would be great. It would be good to be able to merge customs tiles into the `Other` tiles where tags are displayed.
Good suggestion. This would be a new issue if it is not already.

**Comment by corsacca** [comment]
Implemented in v1.
