### ISSUE TITLE
Bulk edit or delete tags

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#703]
It is currently simple to create and apply a tag to a contact. But if a tag is made it can not be edited or removed from the list of tags. Over time I am sure people will make spelling mistakes and need to edit them or remove tags.

**Comment by corsacca** [comment]
@mikeallbutt if a tag is not applied to any contacts it will not show up in the list. The only tags that exist are the ones applied to existing contacts.

**Comment by mikeallbutt** [comment]
A simple admin page listing the tags used and giving access to editing them should suffice, in the case of needing to change all instances of a tag.

**Comment by ahillbilly** [comment]
User should have a place (in wp-admin) where all the tags can be: 
- seen / listed 
- edited (with edit applied to all records already tagged 
- merged if needed

Search of a tag "example" should find both the tag "example" and "Example" regardless of capitalization used or searched for.

**Comment by corsacca** [comment]
Closed by https://github.com/DiscipleTools/disciple-tools-theme/pull/1096/
