### ISSUE TITLE
Metrics: Bar graph columns text is squashed on mobile

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#705]
![Screenshot_20190521-082907](https://user-images.githubusercontent.com/43966676/58114215-e5bdcc80-7bbc-11e9-8b80-097032561dc1.png)
The names of the columns are all on top of each other.

**Comment by mikeallbutt** [comment]
This issue and others like it, make using the metrics on a mobile device very difficult.

**Comment by corsacca** [comment]
@mikeallbutt it won't be possible for all metrics to work on mobile and most are better viewed on the desktop anyways.
We could hide the metrics tab on mobile altogether.
Or we could identify a short list of the most important metrics for the multiplier and only display those  on mobile.
The project milestones would not be one of those most important metrics.

**Comment by mikeallbutt** [comment]
Ok thanks @corsacca for the reply. If metrics won't be a part of the DT app, then having it working in the mobile version of DT would be good. Not everyone who needs the metrics can use a desktop version of DT. But I will have a think more about this area. Let's keep this issue on the issues radar though. ;)

**Comment by corsacca** [comment]
System wide charts and metrics will be geared towards desktop views.
Charts and metrics available to the multiplier will have more of a mobile focus.
