### ISSUE TITLE
Explanation of “Peers” in Group connections

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#706]
What is the intent for this field? Presuming if two groups select the same group as Parent, they would automatically visualize as siblings. Is Peer something different?
![peer-IMG_20190510_190032](https://user-images.githubusercontent.com/43966676/58180210-4efe1800-7c6f-11e9-849a-bcb9db3a4e0d.jpg)

**Comment by corsacca** [comment]
Peer groups is just a connection point to link related groups that aren’t parent/child in relationship.  It might indicate groups that collaborate, are about to merge, recently split, etc.
Todo: add to the modal

**Comment by mikeallbutt** [comment]
This info could be added to this documentation (and the screenshot needs to be updated too).
https://disciple-tools.readthedocs.io/en/latest/Disciple_Tools_Theme/getting_started/groups.html#parent-child-group-tile

**Comment by mikeallbutt** [comment]
This text can be updated in this file:
/disciple-tools-theme/dt-assets/parts/modals/modal-help.php 
And it would be good to adjust the code so that it is translatable too (not hardcoded in English into the core files).

**Comment by mikeallbutt** [comment]
This issue can be closed #706

<img width="883" alt="Screenshot 2019-10-27 14 40 12" src="https://user-images.githubusercontent.com/43966676/67641430-da876f00-f8c7-11e9-8269-619ff1a3e06c.png">
