### ISSUE TITLE
Wrong color search icon

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#707]
The search icon is black and not white like the other icons.

![Screenshot_20190522-091342](https://user-images.githubusercontent.com/43966676/58182037-83270800-7c72-11e9-95ea-b70d9e051509.jpeg)

**Comment by corsacca** [comment]
The icon is the correct color now.

**Comment by corsacca** [comment]
The icon is still black for groups.
