### ISSUE TITLE
next record button for list of records

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#708]
After filtering a list of contacts or groups, it would be good to be able to click on a / the first record then have a next button on that contacts or groups details page that goes to the next record instead of having to go back to the list of contacts or groups page so that you can then go to the following contact in the list.

**Comment by ahillbilly** [comment]
This is navigational improvement.  Needs to work from default views, but also filtered (temporary) lists.

**Comment by cwuensche** [comment]
I'm working on this.

**Comment by cwuensche** [comment]
Here's an example flow I'm thinking of implementing:
1) User loads Contacts page.
2) User filters list.
3) When a filter is set, a temporary session storage item is saved which includes the filtered list.
4) When contact is loaded, if the session is set with the filtered list it will give you the option to go next/prev/first/last to the contacts depending where in the list you are at.

**Comment by corsacca** [comment]
Thanks @cwuensche !
2-3. I'd suggest setting this cookie? whenever the list is returned from the api (so on default loads too).
3. We use cookies in the list already, so it might make sense to start there.
3. We can just save the ids of the records
4. Let's start with just next/prev

**Comment by cwuensche** [comment]
> Thanks @cwuensche !
> 2-3. I'd suggest setting this cookie? whenever the list is returned from the api (so on default loads too).
> 3. We use cookies in the list already, so it might make sense to start there.
> 3. We can just save the ids of the records
> 4. Let's start with just next/prev

I stepped away from the computer for a couple of hours. Ironically when I was digging into the code to see how it's currently working, I saw this was already sort of being done this way, so that's excellent!

**Comment by cwuensche** [comment]
Just an update here, I have successfully saved a list of posts from the Contacts page and I am working on the Next/prev links on the contacts page now.

**Comment by cwuensche** [comment]
I have something working now for the Contacts page and I will transfer this same functionality to groups.

**Comment by cwuensche** [comment]
I added navigation now to both the Groups and Contacts pages. If there are records existing, the navigation will show up giving you the option to go through the previously set filtered lists.

**Comment by corsacca** [comment]
![image](https://user-images.githubusercontent.com/24901539/113028451-30c6a480-9183-11eb-8708-3f045af7fc4f.png)
How about this for the button locations?

**Comment by cwuensche** [comment]
I didn't see this image. It's certainly an idea.
