### ISSUE TITLE
Comments: @mention not working on mobile.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#709]

**Comment by mikeallbutt** [comment]
Using the @ symbol in the writing a comment box or a group on mobile doesn't suggest users like it does on full web version. (It is working fine for a contact though.)

**Comment by mikeallbutt** [comment]
@corsacca can you please advise where you fixed this issue before or what you think how it can be fixed?

**Comment by corsacca** [comment]
I started working on a fix, but have not been able to test it: https://github.com/DiscipleTools/disciple-tools-theme/tree/mobile-mentions-fix

**Comment by mikeallbutt** [comment]
> I started working on a fix, but have not been able to test it: https://github.com/DiscipleTools/disciple-tools-theme/tree/mobile-mentions-fix

Thanks @corsacca. If this @mention works for contacts but not groups, can't the same code that works be used to get this working again?

**Comment by corsacca** [comment]
@mikeallbutt it is the same code for contacts and for groups. Are you sure it works for one and not the other?

**Comment by mikeallbutt** [comment]
> @mikeallbutt it is the same code for contacts and for groups. Are you sure it works for one and not the other?

Hey, I just checked. It is all working again now in both. Cool. Issue can be closed.
