### ISSUE TITLE
Activity Highlights Feature: List/Feed of user's activity and comments across all records

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#711]
From user: 
This could simply be a feature to pull all the comments or milestone events from the past 30 days (or a selectable timeframe) for a Multiplier’s Contacts and/or Groups records. For example a user could select the Month of April and it would give a chronological “ministry log” of the month. It would pull the testimony typed up at the beginning of the month, the Baptism mid-month (milestone or status change), the Group becoming a church right after that, and the other comments made about various contacts as the user interacted with them throughout the month. 

It should leave out the automated “Quick Actions” (didn’t pick up phone, phone ringing, etc) and other system notifications for greater clarity and only include the user's activity and comments instead of all activity and comments for the same records.

If people took the time to type up full testimonies and good ministry updates then their newsletter would consist of hitting this tab under Notifications and copying and pasting into Mailchimp or Pages or whatever they use.

**Comment by corsacca** [comment]
From https://github.com/DiscipleTools/disciple-tools-theme/issues/1019.
Possible elements to include:
{contact/group} updated by {User};
-- {User} adjusted details for {contact/group};
-- {User} wrote a comment about {contact/group};
-- {User} adjusted member list {group};
-- {User} adjusted group health for {group};
-- {User} adjusted tag for {contact/group};
