### ISSUE TITLE
Baptism Date Calendar display issue

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#713]
<img width="352" alt="Screenshot 2019-05-25 09 33 12" src="https://user-images.githubusercontent.com/43966676/58370814-80c1e980-7ed0-11e9-9b87-a1ffbba5bc86.png">

When setting/clicking the baptism date field, a calendar pops up, but if the tags tile is below, the calendar has the search tags field through the calendar.

**Comment by corsacca** [comment]
Closed by https://github.com/DiscipleTools/disciple-tools-theme/commit/ae4a2dcd2e50ced435897918fba53cb68187aaab
