### ISSUE TITLE
Improve update needed workflow

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#716]
From User: I've noticed that in DT, the UPDATE NEEDED includes those who are closed/paused so it's impossible for Multipliers to have ZERO updates needed, this I believe is a hiccup and fosters multipliers to NOT be as vigilant about doing updates... When it shows ZERO that's like a reward to them, but when it always has numbers, then the fact that it always has numbers make them not notice it as much, overlook it even, and they are waiting on the redbell to alert them, which it doesn't always do. so more time goes by and the system ceases to foster/empower good reporting and faithful followup

**Comment by ahillbilly** [comment]
From developer: The update needed workflow does not ask for updates on paused and closed contacts.

The problem is a workflow issue. Which we can improve. We can best improve D.T if we can figure out where the actual problem lays.

If a coach pauses or closes a contact without providing an update, does this count as full communication?
Does setting a reason (paused or closed) count as providing an update?

for example
The user paused the update needed contact with reason (not responding). It would be nice to know if the multiplier sent an email, called, or tried to connect some other way, etc. And how many times they did.

1. We could require an written update before changing the status if the contact is update needed.
2. Or we could include a text box in the closed and paused modal that would be added as comment.
3. Or we can just dismiss the update needed flag when pausing or closing a contact
Can you think of other options?

I lean to trying to get more clarity.

This could be a part of a Multipliers tools upgrade to make what contacts need updates more obvious.

**Comment by corsacca** [comment]
We will remove the update needed flag when the contact is paused or closed with a reason.
