### ISSUE TITLE
Contact and Groups: Search with accents

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#723]
When searching for a contact anywhere a list of contacts can be searched (in connections or the main search field), if I search and type Jose Ramirez without accents on the e or the i, it should still offer José Ramírez which has the accents.

**Comment by grantholle** [comment]
I think there needs to be something like [this answer](https://dba.stackexchange.com/a/142946) and change the collation

**Comment by corsacca** [comment]
Fixed by https://github.com/DiscipleTools/disciple-tools-theme/commit/41e534d728a4fa19cfd5a14f3ffd714b1ed98ee7 for both the lists and the typeaheads.
