### ISSUE TITLE
Notifications: Batch send notification emails. 

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#724]
**Purpose**
Reduce email clutter and increase clarity on activity related to a record.

**use case**
- As an admin user, I get a lot of email notifications for updates on groups - often multiple notifications for the same group/contact per day. I don't want to turn them off and miss what's happening, but I would like to have them batched together to come less often than in real-time.

**Requirements**
- User preference that can specify the frequency with which someone would like to receive email notifications. Options: real-time, hourly, or daily. 
- Email queue for check for emails to send
- Group notifications for a user on a record together
- Cron (wp scheduler) to check for emails to send every hour.

**Code considerations**
Start with `dt-notifications/notifications.php` and `dt-notifications/notifications-email.php`. The email queue is a new system that will need to be implemented. 

Note: Making sure scheduled emails are sent on time will be greatly improved by implementing a real cron service: 
see https://github.com/DiscipleTools/disciple-tools-theme/issues/888 and https://developers.disciple.tools/hosting/cron

**Comment by squigglybob** [comment]
@corsacca or @ahillbilly I have a couple of questions regarding this system...

1) For the option of being sent batch emails daily, should they be able to choose a time to have the emails sent? Or just implement a fixed time for all people?

2) If a user is receiving batch emails and then switches their preference to real-time, should the next batch email arrive as normal, or should it be sent when they make this change?

**Comment by ahillbilly** [comment]
1. I'd probably start with fixed time for all people.

2. I'd probably fire the saved batch up to real time at that time and then switch to real time from there.
