### ISSUE TITLE
Show who the record is shared with when hovering over the share button.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#726]
**Purpose**
Quickly see how many users a record is shared with. Easily see who those users are.

**Benefits**
This feature will speed up access to important information when the data is needed.
This feature will improve the UI of the record

**Requirements**
Currently the user needs to click the share button and wait for the typeahead to load to see who a record is shared with.
Add a number beside the text “Share” to indicate how many user the record is shared with.
When a user hovers or the button or the number, display the list of the users the record is shared with.
Clicking the button will load the current sharing modal.
This functionality needs to work for Contacts, Groups and custom post types.

**Code considerations**
Start with `dt-assets/functions/details-bar.php`,  `dt-posts/dt-posts.php` and `dt-posts/dt-posts-endpoins.php`
You will need to include the shared-with information in the get_post function.

**Comment by cwuensche** [comment]
I'm looking for all files this will affect.
<img width="188" alt="Screen Shot 2021-03-23 at 8 51 27 AM" src="https://user-images.githubusercontent.com/6157604/112176402-4ea96d80-8bb5-11eb-8706-d47dff81aa20.png">
<img width="1537" alt="Screen Shot 2021-03-23 at 8 21 35 AM" src="https://user-images.githubusercontent.com/6157604/112176417-51a45e00-8bb5-11eb-9503-d678a81b343b.png">
