### ISSUE TITLE
Lists: Ability to see the last modified date for each record.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#732]

**Comment by blachawk** [comment]
@corsacca, which wp-admin page are you referring to, in which you want a column for last modified date applied to?

**Comment by corsacca** [comment]
It would be adding it to the contacts list. Probably next to the group column. It think the data is already available in the js.
![image](https://user-images.githubusercontent.com/24901539/69437123-f6edbe80-0d42-11ea-8830-31dfcbc80827.png)

**Comment by blachawk** [comment]
if you think the data is already available from the database, and all it needs is to wired up via JavaScript, feel free to assign this to me and I'll give it a look locally and let you know.

**Comment by blachawk** [comment]
requesting to close this conversation.  the branch is already merged.
