### ISSUE TITLE
Partner role for metrics access

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#745]
Create a role that only has high level metrics access to see metrics on a project level.

**Comment by micahmills** [comment]
Could this be done now with a plugin since we have made the roles and permission system modular? We may still want it to be part of core, but it could be done through a plugin at present I think.

**Comment by corsacca** [comment]
This is currently implemented as the strategist role.
A custom role can be created as well as Micah said.
