### ISSUE TITLE
Contacts: Ability to collapse/hide tiles on records.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#749]
This is already implemented for custom tiles created from the the wp-admin. It needs to be applied to the default tiles.
Also Save the closed/open preference for each user like the comment filter preferences.

Example:
Collapsed
![image](https://user-images.githubusercontent.com/24901539/63334787-06203300-c334-11e9-9c77-43c436143104.png)
Expanded
![image](https://user-images.githubusercontent.com/24901539/63334852-31a31d80-c334-11e9-9b7c-5edd9533ba16.png)

**Comment by blachawk** [comment]
@corsacca is this requested suited for me to look into? or is this more PHP Class and Database related?

**Comment by corsacca** [comment]
The html and css classes are already there on the custom tiles. They need to be copied from there to the default tiles.
Which tiles are open/close could be saved from js using a cookie. 
@blachawk I think you could give this one a go.

**Comment by blachawk** [comment]
Ok feel free to assign to me and I'll look into it.

Thanks!

**Comment by blachawk** [comment]
please feel free to close this conversation as the progress and communciation has advanced beyond this point.

**Comment by corsacca** [comment]
Hey, we'll keep this open until the feature is complete and merged in.
I wasn't clear with the initial description, the intended tiles to be collapsible are the ones below the  details tile.
We also still need which tiles are closed/expanded to be a saved preference (cookie) so the layout is the same when opening a new contact/group.
