### ISSUE TITLE
Round modal boarder corners

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#752]
Round all modal boarder corners to match record detail tiles rounded corners.  This is a simple UI upgrade.
![Screen_Shot_2019-08-23_at_3_23_21_PM](https://user-images.githubusercontent.com/25323324/63599784-311bb880-c5ba-11e9-8821-f44f61753515.jpg)

**Comment by mikeallbutt** [comment]
That might be something I can fix.

**Comment by groovyjosh** [comment]
What kind of browser support are we targeting? That could affect the CSS rules we use.

**Comment by corsacca** [comment]
Hi @groovyjosh!
Desktop and mobile. Some users have cheap older phones, so wider support is better.

**Comment by corsacca** [comment]
Close by PR #886
