### ISSUE TITLE
Contact Records: Icons next to field names

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#758]
Some fields have icons and others don't. Propose good corresponding icons and update the theme with the missing icons.
![2019-09-04_09-39](https://user-images.githubusercontent.com/24901539/64239274-df4b2a80-cef7-11e9-8972-35e3b7324fc4.png)

**Comment by mikeallbutt** [comment]
Icons missing are...

### Contact:

- [ ] Status
- [ ] Groups
- [ ] Connection or Relation
- [ ] Baptized By
- [ ] Baptized
- [ ] Coached By
- [ ] Coaching
- [ ] Seeker Path
- [ ] Faith Milestones
- [ ] Baptism Date
- [ ] Tags 

### Group:

- [ ] Status
- [ ] Group Coach / Church Planter
- [ ] Start Date
- [ ] End Date
- [ ] Church Start Date
- [ ] Member Count
- [ ] Member List
- [ ] Group Type 
- [ ] Parent Group
- [ ] Peer Group
- [ ] Child Groups

**Comment by blachawk** [comment]
Here is one proposal through Font Awesome 5

  #### Contact:

   * Status | [signal-alt](https://fontawesome.com/icons/signal-alt?style=solid)
   * Groups | [users](https://fontawesome.com/icons/users?style=solid)
   * Connection | [praying-hands](https://fontawesome.com/icons/praying-hands?style=solid)
   * Baptized By | [pray](https://fontawesome.com/icons/pray?style=solid)
   * Baptized | [diagnoses](https://fontawesome.com/icons/diagnoses?style=solid)
   * Coached | [chalkboard-teacher](https://fontawesome.com/icons?d=gallery&q=teacher)  with opacity set to 0.6
   * Coaching | [chalkboard-teacher](https://fontawesome.com/icons?d=gallery&q=teacher)
   * Seeker Path | [dove](https://fontawesome.com/icons/dove?style=solid)
   * Faith Milestones | [atom](https://fontawesome.com/icons/atom?style=solid)
   * Baptism Date | [calendar-day](https://fontawesome.com/icons/calendar-day?style=solid)
   * Tags | [Tags](https://fontawesome.com/icons/tags?style=solid)

  #### Group:
   * Status | [signal-alt](https://fontawesome.com/icons/signal-alt?style=solid)
   * Group Coach / Church Planter | [Users Cog Icon](https://fontawesome.com/icons/users-cog?style=solid)
   * Start Date | [hourglass-start](https://fontawesome.com/icons/hourglass-start?style=solid)
   * End Date | [hourglass-end](https://fontawesome.com/icons/hourglass-end?style=solid)
   * Church Start Date | [hourglass-start](https://fontawesome.com/icons/hourglass-start?style=light)
   * Member Count | [users-medical](https://fontawesome.com/icons/users-medical?style=solid)
   * Member List | [clipboard-list](https://fontawesome.com/icons/clipboard-list?style=solid)
   * Parent Type | [layer-group](https://fontawesome.com/icons/layer-group?style=solid)
   * Group Type | [layer-group](https://fontawesome.com/icons/layer-group?style=regular) 
   * Peer Group | [layer-group](https://fontawesome.com/icons/layer-group?style=duotone)
   * Child Groups | [layer-group](https://fontawesome.com/icons/layer-group?style=light)

**Comment by mikeallbutt** [comment]
> Here is one proposal through Font Awesome 5
> 

Thanks @blachawk for the idea. I will investigate how to use them. (but if you have any tips, please advise :) )

**Comment by blachawk** [comment]
You're welcome.  Tips, meaning how to integrate them? If that is what you mean I can give a look.

**Comment by mikeallbutt** [comment]
Yes that is what I was meaning. If you have experience in how to integrate them that would be good. Or together we can learn and give it a go.

**Comment by mikeallbutt** [comment]
So if we wanted to use https://fontawesome.com/icons/tags?style=solid for the tags icon, how do we use it?

**Comment by mikeallbutt** [comment]
@corsacca this is something I could research, but if you can give me a heads-up on what fonts to look at first. What font icon set is being used at present and do you have any recommendations.

**Comment by corsacca** [comment]
We currently use the foundation icons https://zurb.com/playground/foundation-icon-fonts-3 and custom icons from thenounproject and some others.
I'd like to know how much extra weight using fontawesome would add.

**Comment by blachawk** [comment]
Just my 2 cents - as long as we are still using Foundation behind the scenes within this project, using foundation icon fonts is probably the most "comfortable" way to go.  If for some reason you guys are experiencing issues with major limitations on the given font set, then my opinion of a plan B, is to attach the font-awesome 5 CDN to the structure of the site, so that you guys don't have "much weight" in the package with fonts.

**Comment by mikeallbutt** [comment]
@corsacca I am wanting to working on this issue. I was thinking of using the same font icons that are used in the DT app.

Maybe we could switch the icons on the web to use the same as what's in the app or vice versa. It would be good to use less font libraries to keep the overheads lower.

**Comment by corsacca** [comment]
Notes:
We are more and move moving to the link to the icons for each field are being stored in the field declaration array.
This will enable admin users to change the icon for a field (or field values) if they want.

Location field example:
```
['location_grid'] = [
    'name'        => __( 'Locations', 'disciple_tools' ),
    'type'        => 'location',
    "icon" => get_template_directory_uri() . "/dt-assets/images/location.svg",
];
```

A challenge will be to have this strategy also work for font icon sets.

**Comment by corsacca** [comment]
All default fields have icons now in v1.
Moved font icon library discussion here:
https://github.com/DiscipleTools/disciple-tools-theme/issues/1106
