### ISSUE TITLE
Default map to focus location but leave access to higher level views

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#761]
If you set the mapping focus at a country or district of a country, you are prevented from backing out of that location to higher levels of view.

i.e. A Mexico focus will show the map of Mexico, but you can't zoom back out to a world view.  A Mexico City focus will zoom in to focus on Mexico City, but will not let you back out to the entire country of Mexico or further out to a view of the whole world.

Keep the mapping focus working with the default location chosen, but provide the ability to step up/back, like you can drill in to lower detailed locations.

**Comment by corsacca** [comment]
This has been implemented.
