### ISSUE TITLE
Improve/Customize the Create Contact/Group pages

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#762]
As a regular user that adds lots of contacts and groups, I'd like to improve the Create Contact modal to include regular defaults for people groups and locations, allow me to add additional fields to the modal for the data that I most frequently track etc.

- Customize fields shown in modal
- Set default values for fields shown in modal
- Possibly provide expanding feature so that I can generally provide the quick essential data, but if I want to fill in more details I can do so from the same modal without additional navigation.

**Comment by mikeallbutt** [comment]
This should be set in the admin area on a page that allows the setting of what new fields to offer for new contacts/groups and what the default should be set to.

**Comment by corsacca** [comment]
Implemented in v1.
