### ISSUE TITLE
Make master add Contact/Group icon Green

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#765]
As a user, the green add button pops out well, on some screens, but I have to hunt for the master add button in the menu bar.  

Change to same green color as other "Add" buttons
![Screen Shot 2019-09-06 at 2 39 58 PM](https://user-images.githubusercontent.com/25323324/64432375-444b7f80-d0b4-11e9-9d3f-ee2274ba083b.png)

**Comment by mikeallbutt** [comment]
I have made an icon as described and it is located in the assets/images folder.

**Comment by mikeallbutt** [comment]
This is how it should look:

** New Groups **
<img width="352" alt="Screenshot 2019-10-26 23 12 19" src="https://user-images.githubusercontent.com/43966676/67629644-c9e2e480-f846-11e9-81b0-e0f5455cfaf8.png">
<img width="349" alt="Screenshot 2019-10-26 23 12 38" src="https://user-images.githubusercontent.com/43966676/67629645-c9e2e480-f846-11e9-8bf3-4a3d44a27e7c.png">
<img width="766" alt="Screenshot 2019-10-26 23 13 36" src="https://user-images.githubusercontent.com/43966676/67629646-ca7b7b00-f846-11e9-9a53-40002d6c14cc.png">
<img width="766" alt="Screenshot 2019-10-26 23 13 50" src="https://user-images.githubusercontent.com/43966676/67629647-ca7b7b00-f846-11e9-9ab2-e3c5d3934367.png">

** New Contacts **
<img width="346" alt="Screenshot 2019-10-26 23 17 35" src="https://user-images.githubusercontent.com/43966676/67629651-ca7b7b00-f846-11e9-8088-660ccba437bc.png">
<img width="346" alt="Screenshot 2019-10-26 23 18 45" src="https://user-images.githubusercontent.com/43966676/67629652-cb141180-f846-11e9-8ed1-3c47fb187b22.png">

<img width="876" alt="Screenshot 2019-10-26 23 14 24" src="https://user-images.githubusercontent.com/43966676/67629648-ca7b7b00-f846-11e9-973d-cc73e4d390c3.png">
<img width="876" alt="Screenshot 2019-10-26 23 14 48" src="https://user-images.githubusercontent.com/43966676/67629650-ca7b7b00-f846-11e9-96bc-1247c6193de9.png">

**Comment by corsacca** [comment]
@mikeallbutt can you move the icon in the menus to the left instead and then left align the text?

**Comment by mikeallbutt** [comment]
> @mikeallbutt can you move the icon in the menus to the left instead and then left align the text?

Something like this @corsacca ? 

*Mobile view*
<img width="352" alt="Screenshot 2019-10-28 14 15 00" src="https://user-images.githubusercontent.com/43966676/67714578-cc038b00-f98d-11e9-9509-5b3ddf795311.png">

*Standard view*
<img width="265" alt="Screenshot 2019-10-28 14 15 27" src="https://user-images.githubusercontent.com/43966676/67714580-cc038b00-f98d-11e9-990b-ab17c60c8c42.png">

**Comment by corsacca** [comment]
@mikeallbutt looks good.

**Comment by mikeallbutt** [comment]
> @mikeallbutt looks good.

Ok thanks. Want the background colours to be the same for the drop down? or just leave them different colors. (IMO we should leave it.)

**Comment by corsacca** [comment]
You can leave it.
