### ISSUE TITLE
Deduplication check for exact matches before new contact/group record creation

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#766]
As a user it is confusing to accidentally add a new record for someone already in my list.  It would be helpful to know I've already added the contact and to update that record instead of creating a new record.

Note: This will probably need to check against the user's record list only and not the whole list for security purposes.  If the user creates a duplicate record that someone else has already created, the duplicate detection notification should alert a dispatcher or admin role instead of telling the multiplier someone else is working with them.  This differentiation might be more warranted if a Multiplier "Light" role is implemented.

This should check for exact matches atleast on name, phone and email.

**Comment by corsacca** [comment]
Possible layout:
![image](https://user-images.githubusercontent.com/24901539/66034458-2df0e200-e501-11e9-8ac3-6f89d8be87e1.png)

**Comment by corsacca** [comment]
![image](https://user-images.githubusercontent.com/24901539/66034639-84f6b700-e501-11e9-8d33-72c3292bb38b.png)

**Comment by corsacca** [comment]
![image](https://user-images.githubusercontent.com/24901539/201646231-62761a6f-67d1-4f0c-9c06-dbaa64147574.png)

**Comment by corsacca** [comment]
Implemented in: https://github.com/DiscipleTools/disciple-tools-theme/pull/1864
