### ISSUE TITLE
Comments: show comments and their translation using google translate or other service

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#768]
Copy Facebook's comment/post auto translation where the comment is in one language, and shows the translation under it in the user's language. 
This will help speed up communication for multi lingual teams.
![image](https://user-images.githubusercontent.com/24901539/64955492-45349c00-d880-11e9-9da1-74b6b70b5286.png)

This will also help users understand the conversations happening on social media (ie Facebook messages) to determine the best next step.

**Comment by mikeallbutt** [comment]
This would be a useful feature for the prayer team who might not be able to read the comments written by a multiplier of a different language.

**Comment by micahmills** [comment]
I was looking into this today. Microsoft and Google offer Text Translation APIs but they require API keys and the free tiers stop at about 2 million characters of translation a month. 

One option would be to add a settings field in the admin with instructions on how to set up a Microsoft of Google account with and then enter the API key. Then if that API key exists we could show a button to translate the text similar to Facebook or Twitter. This would put the responsibility of setting up payment and managing the billing on the user, and it would leave those who don't need the feature unchanged.

Is this something that seems workable?

**Comment by corsacca** [comment]
That is a good idea.
We use that strategy for some of the mapping features. In the mapping settings you can enter your mapbox key and that will enable extra features related to mapping and geocoding.

**Comment by corsacca** [comment]
Thank you @micahmills! :)
