### ISSUE TITLE
Open or Close sidebar lists

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#773]
In the sidebar, have the ability to open or close the list by clicking the + or - symbol.

![image](https://user-images.githubusercontent.com/43966676/65358854-5226f780-dbc0-11e9-9e8b-ae4d9d5ecf9f.png)

**Comment by mikeallbutt** [comment]
@corsacca if you give me some pointers on where to look in the code and what needs to be done, I would like to have a go at fixing this issue.

**Comment by corsacca** [comment]
@mikeallbutt we use foundations accordion: https://foundation.zurb.com/sites/docs/accordion.html
I'm not confident there is a good solution without some fancy js or css.

**Comment by blachawk** [comment]
This request appears to be working within my localhost environment. I can click on the + and - signs to open / close these panels within the Contact Filters section.

**Comment by corsacca** [comment]
The end result for this on is the ability to close all the accordion list. Right now there is always one open

**Comment by blachawk** [comment]
I can look into it if its not already assigned to someone.

**Comment by corsacca** [comment]
@blachawk You are welcome to.

**Comment by blachawk** [comment]
@corsacca requesting to close this issue, as the feature has been recently merged into the master.

**Comment by corsacca** [comment]
Thanks @blachawk

**Comment by corsacca** [comment]
@blachawk The hoped for behavior:
- When the page loads one of the accordions is open (and highlighted in blue).
- The user can minimize the open accordion so that all of them are closed.
- Only one accordion can be open at a time.
Currently all the accordions can't be close at the same time. @blachawk would you be up for looking at this again. Or thoughts on feasibility?

**Comment by corsacca** [comment]
From Mike: https://github.com/DiscipleTools/disciple-tools-theme/commit/01d6ef0d3cd798f5ccc3593b27134a607e0b6864#diff-dd479bebdc6ce11aeda3b3e32b5468aeR1216

**Comment by corsacca** [comment]
This is working now. Thanks guys
