### ISSUE TITLE
Initial comment in details area

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#774]
In this first tile of the contact (or group), have a space where a descriptive comment can be noted and edited later if need be. Probably above the line of the phone numbers etc would be a good spot.

![image](https://user-images.githubusercontent.com/43966676/65359357-dfb71700-dbc1-11e9-85ef-f9b50c90d516.png)

**Comment by micahmills** [comment]
Can this be done with with a custom field and with the drag and drop tile sorter is pretty easy to add to the top of the list and even include eon the initial contact creation page. I put one in just to see how it works and it seems to do what you are looking for here. 
![Screen Shot 2021-02-07 at 9 21 38 PM](https://user-images.githubusercontent.com/2531805/107155750-2fe77280-698b-11eb-87e2-be2d02c88d74.png)

I think we are better off leaving the default fields to a minimum and allowing users to create custom fields as they need them. I think there is probably a case to be made to make the custom field creation easier, but overall it works now.

@mikeallbutt what do you think does the custom fields ability meet the needs mentioned in this issues?

**Comment by mikeallbutt** [comment]
Putting in the general note field by default will help non digital strategy users. Doing as you did @micahmills does work, but like I had mentioned in another issue, have a field type like what is used for comments, will allow for more text and not just one line.

**Comment by micahmills** [comment]
I agree we need a text area field type to make this better. We have an issue #1049 that is a high priority for that very thing. I am going to close this issue with the understanding that when #1049 is complete this will be completely resolved by using custom fields.
