### ISSUE TITLE
Set group as inactive when creating a group

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#777]
When creating a group, there is no option to set the groups state as inactive. If I want to use DT to plan the beginning of a group, I have to create the group as active, then adjust the group as in active, which then sets a date of when the group was closed, but actually the group was never active.

**Comment by corsacca** [comment]
@mikeallbutt you could use a group type instead. Like 'Pre Group'.

**Comment by mikeallbutt** [comment]
> @mikeallbutt you could use a group type instead. Like 'Pre Group'.

Yes that would be one way to do it too. But that would show incorrect metrics.

**Comment by mikeallbutt** [comment]
This is how it could look:

![image](https://user-images.githubusercontent.com/43966676/67643601-d1ee6300-f8de-11e9-858b-2736dc48aada.png)

I can get the fields to display but they aren't recording the data.

**Comment by corsacca** [comment]
I think this issue will depend on https://github.com/DiscipleTools/disciple-tools-theme/issues/762
Creating group "placeholders" seems like a specific use case that might not apply to everyone.

**Comment by corsacca** [comment]
The group status is available on the create group page.
