### ISSUE TITLE
Time Conversion to "how long ago"

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-theme#783]
As a user, I find it easier to read that an action took place 6 days ago or 6 months ago rather than seeing the date of the action and calculating it myself.

----- 

Normally The date/time is displayed with a standard timezone (show what one is used) for all guest users, and logged in users can usually change their timezone in their settings
At least, that’s how it traditionally works

-----
I just had a look at reddit to see how they do it.
They show how long its been, in the most appropriate single number digit, then hovering on that, shows the full time, with timezone.
so < 1 hour  = show minutes
< 1 day = show hours
< 1 month = show days
< 1 year = show months
1 year = show years
which I really like, it works well, means more at a glance, and hovering gives full detailed time

**Comment by blachawk** [comment]
According to what I see in my Facebook timeline, Facebook resorts to a date, after 2 days. Within 2 days, they follow the methodology you are referring to @ahillbilly.  Do you see that as well?
