### ISSUE TITLE
GULP browser sync optimization Improvement

### ISSUE THREAD

**Issue by blachawk** [DiscipleTools/disciple-tools-theme#784]
Developers who desire to improve the DiscipleTools theme, may request for live reloading from a local development standpoint.  This needs to be fixed internally,  and also documented within the README.md for other developers to use.

GULP, and JavaScript coding is required.

**Comment by corsacca** [comment]
Great suggestion @blachawk

**Comment by blachawk** [comment]
This issue is now resolved in regards to pull request #822
