### ISSUE TITLE
Contacts: Add Social Media icon

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#795]
Add a Social Media icon in the contact details tile.

<img width="387" alt="social media icon" src="https://user-images.githubusercontent.com/43966676/67528513-41feae00-f67f-11e9-9c49-a67272b9de6b.png">

Maybe something like this:

![socialmedia](https://user-images.githubusercontent.com/43966676/67528555-5cd12280-f67f-11e9-88aa-3719849bef0c.png)

**Comment by corsacca** [comment]
@mikeallbutt This looks good. would you be up for implementing it?
