### ISSUE TITLE
Custom fields to be assigned to a tile 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#801]
It would be great if a custom list could be assigned to appear on a particle tile. (rather than it appearing in a new tile altogether.)

If the field could be positioned / ordered (at the top, middle or bottom) in the tile would be a bonus.

**Comment by corsacca** [comment]
This is to let new fields be placed in the existing tiles: other, progress, or connections

**Comment by mikeallbutt** [comment]
This issue is related to #701

**Comment by corsacca** [comment]
Implemented in v1
