### ISSUE TITLE
favicon design update

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#806]
The logo of DT has changed so the favicon should also.

Existing favicons
![image](https://user-images.githubusercontent.com/43966676/67710879-77104680-f986-11e9-8b0d-991d22b9be0d.png)

**Comment by mikeallbutt** [comment]
Please assign this issue to me @mikeallbutt

**Comment by mikeallbutt** [comment]
I found this online code that utilises gulp to make the favicons.
[https://realfavicongenerator.net/favicon/gulp](https://realfavicongenerator.net/favicon/gulp)

**Comment by mikeallbutt** [comment]
@corsacca can you please have a look at this FAQ. [https://realfavicongenerator.net/faq#.Xd7WpJNKjwc](https://realfavicongenerator.net/faq#.Xd7WpJNKjwc)

I think we should follow the advice and move the favicons to root.

I would also like to remove the tags in the header.php file - doing so would make it easier to maintain too.

**Comment by corsacca** [comment]
@mikeallbutt  why do we need a whole gulp process instead of just replacing the current icons with new ones?

**Comment by mikeallbutt** [comment]
> @mikeallbutt why do we need a whole gulp process instead of just replacing the current icons with new ones?

We don't need all those images but the script makes them all - and it is a one off script that sped up the file creation process.

**Comment by corsacca** [comment]
Ok, what are your steps forward?

**Comment by mikeallbutt** [comment]
> Ok, what are your steps forward?
I will put the new files where you want them but my preference is in root.

I can also remove ones that don't get used, but if we leave them there it doesn't really affect anything.

> You asked about removing the favicon meta in the header. Is it not needed?

If you place the favicons in the root, the browsers will use the correct one. So defining in the meta tag in the header what favicon  to use is not needed.
That is explained well in this FAQ page
https://realfavicongenerator.net/faq#.Xd7WpJNKjwc

**Comment by corsacca** [comment]
@mikeallbutt what do you mean by putting it the root folder? Is that the root folder of the D.T theme? Currently the favicons are in the dt-assets folder and your PR places theme in a different folder in dt-assets.

**Comment by mikeallbutt** [comment]
> @mikeallbutt what do you mean by putting it the root folder? Is that the root folder of the D.T theme? Currently the favicons are in the dt-assets folder and your PR places theme in a different folder in dt-assets.

Hi - Yes I was thinking of the root folder of the site, but I now realise that that is not an option. So the next best thing (and therefore what is needed) is to have code in the html header specifying which  favicons to use and where to find them.
