### ISSUE TITLE
Translatable custom fields for sites in 2 or more languages

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#809]
In our context, we have some users who need DT to be completely useable in one language (English) while other uses of the same DT instance need to use DT completely in another language (Spanish). Much of the site can be switched to another language but there are custom fields that can only be defined in one language and not the other.

Example:
The site is used by some in English but the 'Seeker Path' can only be set to one language (the fields can only have one text). So everyone has to use the 'seeker path' choices in Spanish, even if they cannot read Spanish.

*settings for seeker path*
<img width="775" alt="Screenshot 2019-10-28 21 47 23" src="https://user-images.githubusercontent.com/43966676/67736421-3556be80-f9cd-11e9-8995-6961bcd4b719.png">

*Metrics use settings fields*
<img width="998" alt="Screenshot 2019-10-28 21 04 58" src="https://user-images.githubusercontent.com/43966676/67736420-3556be80-f9cd-11e9-9cd1-5a67f50634b0.png">

This example can be seen in all the user definable settings (custom list, tiles & fields) in the Admin area of DT.

**Comment by mikeallbutt** [comment]
An idea I had is to have a different page in the admin area that lists all the fields and then assign then to a particular language. Then the admin user just switches this admin page to be associated to a particular language and all the fields get shown for that language.

**Comment by micahmills** [comment]
I believe this is solved with #950.

**Comment by corsacca** [comment]
I think so too.
