### ISSUE TITLE
User assigns 1 or more languages to their profile

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#812]
As discussed in issue #697 "A user's profile page (/settings) and a user's contact record are currently separate."

I suggest that the users language is used for the contact record too, and have an area in DT that lists the languages that the DT instance can operate in, but make that list a multi select so that the user can utilise the installed languages list but store what languages they also understand. This might need another list item entry for them to store some other language/s that they speak but aren't in the install. And as users or contacts have languages added to the DT list of languages, that list will grow over time, and this data can be used in the filters and metrics.

**Comment by mikeallbutt** [comment]
@corsacca has this now been implemented?

**Comment by corsacca** [comment]
We implemented in the profile section a field to track what languages the user can/wants to use to communicate with contacts.
The languages list can be edited in the WP-Admin > DT Settings > Custom Lists
