### ISSUE TITLE
Standardised naming conventions for assets

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#814]
When naming assets (images and icons) to be used throughout DT, it would make it easier in the future to have the (default) asset be named the same as the 'value'.

Like in the attached image, the one odd one out is house.svg which is being used for address. 

<img width="259" alt="Screenshot 2019-10-29 09 23 36" src="https://user-images.githubusercontent.com/43966676/67782147-0c1a4a80-fa2e-11e9-9df3-79808c6b8ac8.png">

Doing this will help with putting a different design on the site but other orgs.

**Comment by corsacca** [comment]
@mikeallbutt I don't understand what you are suggesting. The value is the name of the field. An icon can be used for multiple fields. Would your suggestion be to duplicate the icon under different names?

**Comment by corsacca** [comment]
So a metrics page that wants to use the house icon (not in an address context) would need to copy the address icon and name it house.svg before using it?

**Comment by corsacca** [comment]
If the icon colors can be changed through css then we just need "email-solid.svg" and "email-clear.svg"

**Comment by micahmills** [comment]
Since the SVG icons can be changed with css to do just about whatever you want, and we have another issue for adding custom icons. I think I can going to close this issue for now.
