### ISSUE TITLE
Comments: Showing special characters i don&#039;t have &quot;42&quot;

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#815]
Sometimes a comment is not display correctly.
Example: `My script: i don't have "42"`
shows:
`My script: i don&#039;t have &quot;42&quot;`

In this case the key word `script` is triggering an issue with the comment parser.

**Comment by mikeallbutt** [comment]
If someone wanted to look at this issue, where would they start?

**Comment by corsacca** [comment]
The comments.js

**Comment by mikeallbutt** [comment]
> The comments.js

Thanks @corsacca. Maybe @blachawk can have a look at this?

**Comment by blachawk** [comment]
Sure. @corsacca please feel free to assign this too me. I'll give it a shot.

**Comment by blachawk** [comment]
Team, here is my theory.  This is intentional within the system.  I believe it is a security feature to prevent nasty JavaScript injections into the comments.  The JavaScript logic will look for certain patterns of strings to determine that.  Here is a note I found in comment.js. which controls the comment section:

```javascript
/* comment_content should be HTML. However, we want to make sure that
       * HTML like "<div>Hello" gets transformed to "<div>Hello</div>", that
       * is, that all tags are closed, so that the comment_content can be
       * included in HTML without any nasty surprises. This is one way to do
       * that. This is not sufficient for malicious input, but hopefully we
       * can trust the contents of the database to have been sanitized
       * thanks to wp_new_comment . 
*/
```

* If we choose to  un-escape these comment strings, it may set us up for attacks.
* According to the system, `script i don't have...` looks pretty close to `<script>console.log('inject something');...`

Let me know how you would like to me to move forward.

**Comment by corsacca** [comment]
Unit tests:
Currently this works when displaying a comment:
- `[link name](http://dt.local/contacts/14493/)` makdown format for hyperlink
-  `@[bob](46)` this is a mention notification
- `http://dt.local/contacts/14493/` displays a link as clickable
- `Possible <strong>duplicates</strong> on Phone` shows up as: Possible **duplicates** on Phone. Note: if the users creates a comment with <strong>duplicates</strong> it will get escaped.

But this should not work:
- `<script>console.log('inject something');...`
- @todo look for a list of common xss attacks

@blachawk what special characters would be removed ?

**Comment by blachawk** [comment]
lets start out with removing single or double quotation marks.

**Comment by corsacca** [comment]
@blachawk Would this change this comment
`I don't think it was "green"` to `I dont think it was green` ?

**Comment by blachawk** [comment]
yes

**Comment by corsacca** [comment]
I wonder if we can keep the best of both worlds by something like: https://github.com/cure53/DOMPurify

**Comment by blachawk** [comment]
DOMPurify appears to have potential.  At the moment, we have a good amount of code surrounding the [Underscore.js library](https://underscorejs.org/) in our comment.js file.  It may take some time in configuring these large mountains around to play nice together without hacking code.

But before we compound another library on top of what we have, I would recommend some more time investigating more on the Underscores.js library,  and see if there are more options to how data can be "escaped" for comments. Just my 2 cents.

**Comment by corsacca** [comment]
@blachawk thanks for investigating some more.
Note: We use Lodash instead of underscore

**Comment by blachawk** [comment]
ahhh I see now.  Thanks for clarifying that.

**Comment by blachawk** [comment]
Please checkout my pull request at #837 I believe we have a fix.  Feel free to test when time permits.
