### ISSUE TITLE
Hide empty rows in metrics list

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#835]
When looking at the Metrics > Mapping > List, it shows all the locations in the system. It would be useful to have a way to only show the rows that have data (contacts, groups, workers etc.).

A 'Show empty rows' slider like what is available on the Contacts list page, which says 'Closed Contacts' would be one option.

Not showing empty rows as default would be ideal.

![map list switch](https://user-images.githubusercontent.com/43966676/69454005-d31e7e80-0d2a-11ea-86f0-d9f58a72cab7.png)

**Comment by mikeallbutt** [comment]
@ChrisChasm this would be great to get implemented soon now IMO ;)

**Comment by corsacca** [comment]
Thanks for the suggestion Mike. We have chosen not to implement this one.
