### ISSUE TITLE
Transfer 'Issues' from Disciple Tools Plugin repo

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools-theme#84]
We need to move the issues from the Disciple Tools plugin repo to this repo. Here is a Python script that will help do that. https://github.com/IQAndreas/github-issues-import

**Comment by grantholle** [comment]
I was about to ask about this...

Should the theme issues be flagged as such, so we at least know which issue is for which project (at least in the short term).

**Comment by corsacca** [comment]
@grantholle we are about to merge the theme and the plugin together. Mostly for simplicity, clarity and ease of updating.
We were tracking all issues in the plugin, but now the plugin repo will be probably be archived.

**Comment by grantholle** [comment]
👍

That would definitely simplify things and be a lot more manageable/organized

**Comment by corsacca** [comment]
Done. Sorry for all the notifications.
