### ISSUE TITLE
Update DT logo

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#844]
In the top left corner of the website there is a logo.

**Previous logo DT beta**
![disciple-tools-logo-beta](https://user-images.githubusercontent.com/43966676/69843133-c9fe4780-122b-11ea-9f0b-4a8788ecf370.png)

**The current logo**
![Screenshot 2019-11-28 22 15 05](https://user-images.githubusercontent.com/43966676/69843345-a687cc80-122c-11ea-9f48-9477afe12c2e.png)

The word beta is no longer at the end but what it was replaced with (and svg file) doesn't display cleanly (screenshot from Firefox).

This next logo is what is on the actual DT website, so maybe this logo would be good. But when it is smaller (20px high) it hard to read the words. It does use less space, allowing more room for navigation items.
.
<img width="197" alt="Screenshot 2019-11-28 21 30 42" src="https://user-images.githubusercontent.com/43966676/69841821-632a5f80-1226-11ea-9c9e-c119fe42c536.png">
<img width="658" alt="Screenshot 2019-11-28 22 01 30" src="https://user-images.githubusercontent.com/43966676/69842948-fcf40b80-122a-11ea-9a85-142797d75112.png">

Another option is something like this:
![disciple-tools-logo](https://user-images.githubusercontent.com/43966676/69843027-4ba1a580-122b-11ea-81f4-e7ae8e669cb2.png)

<img width="658" alt="Screenshot 2019-11-28 22 00 55" src="https://user-images.githubusercontent.com/43966676/69842898-bc948d80-122a-11ea-8e77-4dc2f48a99c9.png">

**Comment by mikeallbutt** [comment]
I think if we make the DT logo this size (26px high) it will work nicely.

![Screenshot 2019-11-28 22 37 06](https://user-images.githubusercontent.com/43966676/69843978-b1902c00-122f-11ea-85de-9bd68ccdeb43.png)

**Comment by corsacca** [comment]
This is implemented
