### ISSUE TITLE
Update needed message triggers 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#845]
Currently when the message is displayed "This group needs an update." it can only be removed automatically when the user who is assigned this group writes a comment.

A subassigned/group coach users, comment should be able to clear the update needed message notification. 

Also, in mobile view, the toggle to override the message is not available to an administrator or dispatcher. 

(the same issue happens for contacts)

**Comment by corsacca** [comment]
@mikeallbutt D.T is setup so the update needed flag does not go away if an admin or dispatcher (or someone who has access to all contacts ) makes the comment. If another multipliers makes the comment the flag will go away. Is this process not working correctly?

The admin can turn the notification off manually on the desktop version. 
We should make this also available on the mobile interface. We could create a github issue for this piece by itself.

**Comment by corsacca** [comment]
Thanks for submitting this issue.
We will be keeping this functionality:
An admin posting a comment asking for an update on a contact or group should not take the updated needed flag away.
From what we can tell, the theme is currently respecting this behavior. If you have any question or more information, please let us know.
The update needed toggle is available on mobile.
