### ISSUE TITLE
Share list displays user numbers and opens list when clicked

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#849]
The typeahead fields have the name of the user and their ID number after. The share field doesn't.

Currently it displays like this:
<img width="595" alt="Screenshot 2019-12-03 06 27 24" src="https://user-images.githubusercontent.com/43966676/70056487-28ffeb80-15a1-11ea-8837-05bd0a45ff60.png">

But it would be good if it looked more like this with the user ID in brackets and the hashtag:
<img width="234" alt="Screenshot 2019-12-03 06 26 32" src="https://user-images.githubusercontent.com/43966676/70056569-49c84100-15a1-11ea-8b5c-1bca17779a95.png">

User (#849)

Also, the list of contacts should open when the cursor is placed in the input box.

**Comment by micahmills** [comment]
I think this is taken car of as well

**Comment by corsacca** [comment]
Similar to #1262.
