### ISSUE TITLE
Mapping: Locations List: Add New Location - gets added but not displayed

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#855]
The issue is that when adding a new location, it does get added when the save button is clicked, but nothing is displayed in the table above, so the user (like I did) will re-press the save button, but this then makes a second new entry, and they can't be removed (another issue to be fixed).

As you can see, Caracas was added twice, because after the first click and it not displaying, I clicked it again. It still didn't display so I went to another page. When I made my way back, there were now 2 entries - and no way to delete the extra one.

![Screenshot 2019-12-05 21 51 15](https://user-images.githubusercontent.com/43966676/70294755-1dcbdc00-17aa-11ea-8d62-638b1e41807f.png)

**Comment by corsacca** [comment]
Fixed by https://github.com/DiscipleTools/disciple-tools-theme/commit/431f1fd2b61832c1a15b9fea3efb1079032d3391
Thanks @mikeallbutt for the report!
