### ISSUE TITLE
People Group/Location/Source Name Translations

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#856]
So the internationalization works really well and most of the data seems to be translatable. I have noticed that when creating or updating a contact's details the Location, Source, and People Group dropdown are populated with English data. I am sure that this is because the data sources for these fields is in English, and doesn't provided the localized names.

For my region and users I need particularly to have the people groups and city names written in the local script and language, or else they will get ignored and we will miss key data. 

I am happy to work on this, but since I am new to this project I wanted to get some input on the best path forward. My initial thought is to add custom fields to the Post Type, but then we would have to sort out getting those to populate in the dropdown based on the users locale. I could also add them to the translation files, but there might be some downsides there I haven't seen yet.

Any insight or ideas on this?

**Comment by corsacca** [comment]
Hey, 
Great questions.

You can modify and add custom entries to fields like **sources** in the wp-admin under Settings (DT) -> Custom Fields.
The sources field was treated differently when we started (and still is in some ways) and it looks like we didn't come back and make those default options translatable. Issue created: https://github.com/DiscipleTools/disciple-tools-theme/issues/857
You can rename or delete and add new ones as you wish. The only downside with custom values is that all users will see the same translation for that option (see https://github.com/DiscipleTools/disciple-tools-theme/issues/809).

**People Groups** you can easily rename from the People Groups tab in the wp-admin.

**Locations** you can as well from wp-admin > Mapping > Locations List.
Chose a location in "Select a location to Edit" and update the name.
If in your context you have a considerable number of locations this could be quite a chore. We'd love help in automating this process.

**Comment by mikeallbutt** [comment]
In my context, I just need 2 languages - Spanish and English - so getting this issue fixed will be one more step closer to having users use DT.

**Comment by micahmills** [comment]
I think that @mikeallbutt and I are having the same issue and it is similar to #809. 

For instance, I need to have the list of People Groups and cities  to be in Latin script when the locale is English, and Persian/Arabic script when the local is Persian. If I change the name of the people group in the People Groups Tab, or the Locations List and make them all in Persian/Arabic Script then someone viewing it in English will only see the Persian script names.

I could create a second list of People Groups and Locations, one in English and one in Persian, but that will make reporting more difficult. 

The ideal situation is something similar to what happens when we select a gender for a contact. What shows up on the front end is pulled from the .po file based on their locale, and what gets saved to the DB from the input value can be in English.

**Comment by mikeallbutt** [comment]
Yes @micahmills we have the same issue. It also affects the faith milestones and any custom tiles that I have made.

**Comment by mikeallbutt** [comment]
I think with your latest work @micahmills we have got this issue resolved?

**Comment by micahmills** [comment]
Yes PR #950 should resolve this. There are a couple of things that need to be done in that PR to get it complete but when it is merged this can be closed.

**Comment by micahmills** [comment]
#950 was merged so this is now closed.
