### ISSUE TITLE
Multi-site install : WP-Admin : Multiple user roles

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#861]
It is possible to see and set multiple user roles on a single DT install but on a multisite install the option to choose roles is not available.

![Screenshot 2019-12-05 18 43 45](https://user-images.githubusercontent.com/43966676/70400032-0aa94e00-19ee-11ea-8cdb-a89474d36314.png)

**Comment by corsacca** [comment]
Either in the admin or on the front end we could use a better user management page with more D.T relate settings. 
An initial work in progress available here: https://github.com/DiscipleTools/disciple-tools-dispatcher

**Comment by corsacca** [comment]
This is now possible from the front end under the settings gear > users
