### ISSUE TITLE
Tags: clickable tag to create a list/filter

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#863]
Have a tag (that is in the tags field of the other tile of a contact) be clickable so that when clicked, it creates a list/filter of contacts or groups that have that tag.

**Comment by corsacca** [comment]
This one requires the list to accept query parameters.
Ex
dt.com/contacts/?tags=awesome_tag
dt.com/contacts/?assigned_to=4&overall_status=active
etc

**Comment by squigglybob** [comment]
Hi I can take this one @corsacca
