### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#870]
Have Portuguese translation of DT.

**Comment by corsacca** [comment]
Please clarify your intent for this issue.

**Comment by mikeallbutt** [comment]
> Please clarify your intent for this issue.

Have the DT interface in Portuguese so that, for example, a person from Brazil who speaks Portuguese, can understand and use DT in their language.

**Comment by corsacca** [comment]
We have a Portuguese translation.
