### ISSUE TITLE
Filtering "Sub-assigned to" typeahead shows those who are "Sub-assigned to" someone

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#871]
The sub-assigned users should only offer the list of users who have been sub assigned.

When using a filter to narrow a list of contacts, one can use the sub-assigned to field. The issue is that the created drop down list in the "type to search field" actually shows all system uses. It should only list a user that is sub-assigned by someone.

**Comment by corsacca** [comment]
A user might want to create a filter for someone as a placeholder for when they do have subassigned contacts even though they don't yet.
I'd rather not limit it in that case.
Is there a certain problem we would some with this request?

**Comment by mikeallbutt** [comment]
> A user might want to create a filter for someone as a placeholder for when they do have sub-assigned contacts even though they don't yet.
> We'd not want to limit it in that case.

Ok I hadn't thought of that possibility. But I think it is confusing to have people in the list who currently do not have any sub-assigned people. If their names are listed, I naturally expect that their names are there because they have someone sub-assigned to them, and not that in the future they might get sub-assigned someone.

> Is there a certain problem we would fix with this request?

Another small aspect to this issue is that the list can be super long if it includes all of the contacts in the system.

**Comment by corsacca** [comment]
We need to keep the functionality, so will not be able to filter out the unconnected contacts.
