### ISSUE TITLE
Irrelevant html title tags

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#872]
On many pages the html title tag is `<title>DiscipleTools</title>` instead of being something more relevant to the page. eg. `<title>Create new contact - DiscipleTools</title>`

Pages that need fixing are:

- [ ] Dashboard
- [ ] Metrics
- [ ] All sub-pages of metrics ie. /metrics/mapping/map
- [ ] Create new contact
- [ ] Create new group
- [ ] Settings
- [ ] Notifications
- [ ] any plugins ie. clusters

**Comment by mikeallbutt** [comment]
@corsacca please give me some ideas of where to fix these and I will do it.

**Comment by corsacca** [comment]
It looks like this is set in the header.php file.
We'd probably need to add a filter so individual pages can hook in and set the value.
Wordpress might have a better option.

**Comment by mikeallbutt** [comment]
Another thing I have noted is that the other pages like "Contact" only have that word in the title tag. They should have which site appended to the end so that when you have various windows or tabs open, you can easily identify which site this Contact page is referring to.

**Comment by mikeallbutt** [comment]
I suggest this type of structure:

{name} - {section} - {site}

{contact name} - {Contacts} - {DT instance name}
{group name} - {Groups} - {DT instance name}
eg. Someone - Contacts - DiscipleTools
{add new contact} - {contacts}- {site}

{Metrics} - {site}
{Critical Path} - {Metrics} - {site}

**Comment by mikeallbutt** [comment]
Maybe @micahmills you can look into this. ;) ? I tried but don't have enough experience with WP.

**Comment by mikeallbutt** [comment]
@micahmills this has been closed by still the title tag is not helpful. It should have the name of the instance on the end - like what the wpadmin has.

![titletabs](https://user-images.githubusercontent.com/43966676/107263217-197efc80-6a07-11eb-9386-aa180d239bff.png)

**Comment by ahillbilly** [comment]
@mikeallbutt can you confirm this is still an issue?  

My recent investigation showed things working nearly like your described desire.  The only thing I saw not consistent were these two:
{contact name} - {Contacts} - {DT instance name}
{group name} - {Groups} - {DT instance name}

Currently it is showing: 
{contact name} - {DT instance name}  - without the section "Contacts"
{group name} - {DT instance name} - without the section "Groups"

Your screenshot above does not seem to show what I'm seeing.

**Comment by mikeallbutt** [comment]
Here is another example for improving the title tag. In this list, how does a user distinguish the different DT instance - there are 2 pages called group - but they are different DT instances? The last menu item makes it clear that it is a window for DT Demo Data.

<img width="175" alt="browser-window-list-items" src="https://user-images.githubusercontent.com/43966676/117552319-30d28380-b010-11eb-8821-eafb6f007e08.png">

Putting the DT site name onto the end of the title tag will help a lot for us who have more than one instance.

**Comment by mikeallbutt** [comment]
The attached images show clearly that it is hard not possible to identify which page on what site is being requested.

<img width="179" alt="Screen Shot 2021-05-09 at 05 00 21" src="https://user-images.githubusercontent.com/43966676/117568123-79c41f80-b084-11eb-838e-60c0cf572230.png">
<img width="179" alt="Screen Shot 2021-05-09 at 05 00 43" src="https://user-images.githubusercontent.com/43966676/117568124-7af54c80-b084-11eb-8dff-5436866398bd.png">

Please reopen this issue.

**Comment by ahillbilly** [comment]
I think a bit of added context is that some browsers (Chrome...) natively add the domain/sub-domain, but that others (firefox?) don't... so it is a bigger issue for some browsers than others.
