### ISSUE TITLE
Having the ability to move things to merge customs tiles into the `Other` tiles

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#876]
> Having the ability to move things around would be great. It would be good to be able to merge customs tiles into the `Other` tiles where tags are displayed.

> Good suggestion. This would be a new issue if it is not already.

_Originally posted by @corsacca in https://github.com/DiscipleTools/disciple-tools-theme/issues/701#issuecomment-563121077_

**Comment by corsacca** [comment]
Fields and tiles are now fully customizable in V1
