### ISSUE TITLE
Group details tile: Date fields using wrong language

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#880]
My site uses lanuage1/spanish as the primary language but I choose to override this and use language2/english. When I view the interface it correctly shows all the labels in language2/english - except fields where dates are displayed in the group details tile in lanuage1/spanish (the site default language).

![Screenshot 2019-12-14 07 06 57](https://user-images.githubusercontent.com/43966676/70849160-57eb4c80-1e40-11ea-8b5a-bb618eaf1dc9.png)

**Comment by micahmills** [comment]
So I was seeing the same thing and I dug into this a bit. The group dates are set in line 131 of dt-core/global-functions.php. It is getting that data format from the General Settings of Wordpress. We can consider doing changing the way that function works, but the easy solution is to change the  Date Format in the WP admin Settings->General. I chose d/m/Y and that solved my problem for me.

**Comment by corsacca** [comment]
Todo: get formatted dates in user's local
