### ISSUE TITLE
.pot file missing contexts

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#883]
It looks like the .pot file (along with the .po files) are missing some context fields. So `_x( 'Male', 'Gender label', 'disciple_tools' )` in dt-contacts/contacts-post-type.php line 367 doesn't actually pull the translation from the po file because it doesn't have the proper context. This is true of quite a few strings in the particular file.

**Comment by corsacca** [comment]
Those context fields were just added. So we might need to just re create the .pot files and they'll show up.

**Comment by micahmills** [comment]
Is there instructions written for remaking the pot file?

**Comment by corsacca** [comment]
Using https://poedit.net/ you can open the .pot and "update from code"

**Comment by micahmills** [comment]
resolved by commit 3bc35c7034013434611128b624a7cdea5c2c5916
