### ISSUE TITLE
If you create a a contact and delete the contacts name you cannot then open the user

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#931]
When you create a contact if forces you to enter a name, but if you then open that new contact and edit the information you can clear out the contacts name. It will then show up in the list, but the link to open the contact is not there because there is not name to put the link on.

**Comment by corsacca** [comment]
I think this is an issue on the list page and the notification page. 
It would be great to make the cell (or the whole row?) clickable instead of just the name.
Plus we might want to protect from the user erasing the name in the UI and in the create/update code
