### ISSUE TITLE
Ability to change the Church health icons

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#937]
This is a request for a WP-Admin UI where the icons of the church health metrics can be changed.
These icons appear under the church health circle.
- Also for the icons within the circle to be changed. This might require a new svg to be supplied.

**Comment by prykon** [comment]
Does this get covered by the Custom Church Health Plugin?
https://github.com/prykon/custom-church-health-plugin

**Comment by corsacca** [comment]
https://disciple.tools/plugins/custom-group-health/ Is a great suggestion! I hope a future release will let the user replace an icon with their own icon.

**Comment by corsacca** [comment]
This is now possible.
