### ISSUE TITLE
Hide translate option if the comment language is the same as the user's locale

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#945]
This is a suggestion because it might require more API calls to do. 
If a comment is in English and i click on the translate link i get the comment in English since my selected locale is English. The UI would be simpler if the Translate button was only visible on comments in other languages.

![image](https://user-images.githubusercontent.com/24901539/79550975-f60e4e00-8090-11ea-8c70-0616c3b9c1fc.png)
![image](https://user-images.githubusercontent.com/24901539/79550686-9c0d8880-8090-11ea-84a6-9b1bc25f187a.png)

**Comment by micahmills** [comment]
Yeah I considered that as well, it would be one more API call every time the comment is loaded. Unless we added some metadata in the comment itself that saved the language information from Google Translate. 

So we could make a call to Google Translate, get the comments language, update the comment to include the language metadata. On subsequent calls check if the metadata exists before making the call to Google Translate. Then only show the Translate UI when the comment language doesn't match the users locale.

**Comment by micahmills** [comment]
Now that I think about it, we could save the comment translation that we get back from Google Translate as well, then displaying that instead of making a round trip to the translate API every time. 

This would make the comment object bigger, but I think we can work with that.

**Comment by corsacca** [comment]
We could look up the locale of the user that made the comment. But it isn't a guarantee they wrote in the same language.

I like the idea of saving data return by an API call.

An API call for each comment might create a rather large usage bill. Even if it is just once per comment. If Facebook conversations are imported there can be 100s of messages per contact.

**Comment by corsacca** [comment]
I don't think this is worth pursuing.
