### ISSUE TITLE
Lists: clear search input box when list changes.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#951]
I search for a name and get a list of results.
I click to another filter.
The name i searched for is still in the search input. 
The search input should be cleared to avoid confusion.

**Comment by mikeallbutt** [comment]
Related to this would be a way to remove a filtered item when on the record list page. eg. I want to see all the "females" who "have bible" who are "active", but if I want to adjust the results that are shown, I just remove a filter eg. gender, and the list refreshes to now only show the 3 filters.

**Comment by prykon** [comment]
What page(s) does this happen in?

**Comment by corsacca** [comment]
Contacts list page, Groups list page, etc

**Comment by squigglybob** [comment]
I don't mind taking this one too... unless you are @prykon?

**Comment by corsacca** [comment]
Go ahead with this one @squigglybob
