### ISSUE TITLE
Notifications number indicator wrong place

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#954]
On the notifications page the number is in the wrong place:
![image](https://user-images.githubusercontent.com/24901539/80019646-c667a780-84cf-11ea-8b2c-166fa26529c4.png)
Please check you changes in a right to left language like Arabic

**Comment by mikeallbutt** [comment]
This issue affects the mobile view of the website too. The issue might need to be reopened.

**Comment by corsacca** [comment]
@mikeallbutt  can you post a screen shoot of what you mean? It looks the same on desktop and on mobile for me.

**Comment by mikeallbutt** [comment]
> @mikeallbutt can you post a screen shoot of what you mean? It looks the same on desktop and on mobile for me.

I checked again now. All good.
