### ISSUE TITLE
Some Filter Names not translated

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#964]
In the Contacts Filter List the word Contacts in All Contacts and My Contacts is note being translated into the users language. 

It appears the problem originates in contacts.php line 1854 and its use of Disciple_Tools_Contact_Post_Type::instance()->plural. That comes from contacts-post-type.php line 105. I think that the users locale is not being applied when that file is run and it gives the English text instead of the translated text.

**Comment by corsacca** [comment]
There could be a lag in the translation files.
Is this the same location you are referring to?
![image](https://user-images.githubusercontent.com/24901539/80511702-5d22e100-8974-11ea-82ba-c036d7a9b28f.png)

**Comment by corsacca** [comment]
@micahmills can you check that https://github.com/DiscipleTools/disciple-tools-theme/commit/7ae797fc7e0979e56900ae70ae115269e3a00519 fixes the issue?

**Comment by micahmills** [comment]
Yes that does it.
