### ISSUE TITLE
localized scripts cached in wrong language

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#965]
Data that is put on a page using wp_localize_scripts will be cached by many Caching plugins. If the user changes languages in the settings these cached scripts will not get updated. ie. wpApiListSettings

I am using WP-engine and the cache there persisted across logouts, browser changes, and private browsing modes, and was only resolved when I purged the WP-engine Cache. 

Possible solutions are: 
1. adding a language string to the URL so that the pages would be cached per locale. This would take some work to modify the routing in DT. 
2. adding a language key to the JS objects and putting a check in the JS that uses those objects to make sure the Objects language matches the users language, if not fetch a new copy from the server and replace the inlined version.

**Comment by corsacca** [comment]
I suspect this is more a server caching issue more than a browser/request caching issue.

**Comment by micahmills** [comment]
It is. WP-Engine uses Object caching so the Object was being cached in one language and not being updated when the language changed. I turned off object caching and that resolves the issue. 

There might be a way to avoid caching in the wrong language, but I think that is probably more work than it is worth. It is likely an edge case that someone would be switching languages often and on a host that is doing object caching. We should probably make a note in the documentation about turning off Object caching if you experience problems with things not being translated properly.

**Comment by corsacca** [comment]
The object caching extends to any part of the system that uses wp_options to store data. The fields list will be the most notable example.
