### ISSUE TITLE
Grant access to all groups the user is a part of

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#978]
When doing a conversion of a contact to a user, have a way for a contact who then becomes a user to then have access to all their relationships and groups they are in, so that someone doesn't have to go through and share this new user and give them access to all these contacts and groups, or sub-assign them one-by-one so they can see them.

**Comment by corsacca** [comment]
Might be linked to the #454 issue

**Comment by micahmills** [comment]
This can be done with the Bulk Edit feature.
