### ISSUE TITLE
Tile minimiser function

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#979]
Put a tile minimiser function (like the other tiles have) on the Contact details tiles and Group details tiles. 
In my case, I hardly ever need the info displayed in the details tile and always have to scroll down to get to the other tiles. That gets tiring. 
The other reason, is there are times I need to do screenshot but not with all the persons personal details displayed.
Maybe not everyone will want this functionality, but I am sure I am not the only one who would use it if it was implemented.

**Comment by corsacca** [comment]
Status, assigned to and subassigned are fields that we'd want to keep more visible.

**Comment by micahmills** [comment]
I think this is resolved in the V1 redesign, but can you confirm that.
