### ISSUE TITLE
Settings: Roles name uses incorrect info

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#982]
The Roles field on the /settings/ page of a user is not using the correct information - as seen in the attached image for a DT system in Spanish.

![Screenshot 2020-05-05 15 54 04](https://user-images.githubusercontent.com/43966676/81115255-07f14d00-8ee9-11ea-96c6-38a980483616.png)

**Comment by micahmills** [comment]
This is because in template-settings.php Line 100 we are getting the users roles from wp_get_current_user()->roles and those are in English.

**Comment by corsacca** [comment]
Fixed by https://github.com/DiscipleTools/disciple-tools-theme/commit/8e666b73df2633cf4a91097ae849ebdc93513f5c
