### ISSUE TITLE
Custom Field Translation Deletion

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#983]
If you set a custom field key translation then delete that translation, the default key will be shown but it will not pull the translated string from the .po files. 

For instance if you set the translation for seeker_path in a given language then delete that, the user will see Seeker Path on the contact page instead of the default translation that comes from gettext.

**Comment by corsacca** [comment]
I think this is now fixed with https://github.com/DiscipleTools/disciple-tools-theme/commit/afd6128a365dfcbf03754cf4555c1e9b3e2b234f
