### ISSUE TITLE
Administrator user not able to add DT roles to themselves

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#986]
Currently a Wordpress Administrator user cannot add a custom DT role to themselves because the User Role section does not appear in the WP_Admin. A different DT_Admin user can add a role to and Administrator user.

**Comment by corsacca** [comment]
Administrators should be able to add and remove roles and themselves. DT_Admin the same except they should not be able to give themselves the administrator role.

**Comment by corsacca** [comment]
This is implemented with v1.
