### ISSUE TITLE
Group Progress Translations

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-theme#991]
There are 2 terms under Groups -> Progress which are not being properly translated (and this is indirectly affecting the Mobile App bc we're pulling these particular terms from the D.T API):

- Group Type
- Church Health

Please see the red highlights in the attached screenshot

![Screenshot from 2020-05-31 23-08-11](https://user-images.githubusercontent.com/191707/83376678-14aa7900-a3a1-11ea-8b42-f4fb73c8ace7.png)

**Comment by corsacca** [comment]
Hey @zdmc23 
These are the result of custom labels being set on the fields on this particular instance.

**Comment by zdmc23** [comment]
See #950
