### ISSUE TITLE
Group member list tile improvement

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#996]
In many of our groups we have a few dozen members. There are only a few leaders, and assigning leaders to a group doesn't change too often. The current member list design uses the footprint icon to allow a member to be assigned/indicated as being a group leader. I suggest using the space where the footprint icon currently is, and it be replaced with a way to allow the marking of group attendance to a meeting. There could be a new field added for indicating the group leader/s - maybe in the group details tile (near the group coach / church planter field)

**Comment by mikeallbutt** [comment]
@ahillbilly maybe you can provide some insight as to the current design for the member list tile. It uses a significant design to other fields and name lists.
Does it really need every member to have a leader icon next to their name?

**Comment by ahillbilly** [comment]
Sorry, I didn't understand this: "It uses a significant design to other fields and name lists."

The member list tile probably doesn't need to have the leader icon next to every name, but when new groups are forming, the leadership isn't always clear.  A multi-select leader field could be an alternative.

As for marking attendance, that seems like a solid requirement for folks leading groups.  I think there are about a dozen different ways to accomplish it, all with pros and cons.  I don't know how using the same space to mark attendance would work past the most recent meeting.  There would have to be some way of storing the information over time, which goes far behind my comprehension of what would work well.

**Comment by mikeallbutt** [comment]
> Sorry, I didn't understand this: "It uses a significant design to other fields and name lists."

Most fields use a simple name box - like what's in the Relation field on the Connections tile for a contact. The members list tile uses this other design with each member on a separate row with icons etc.

> 
> The member list tile probably doesn't need to have the leader icon next to every name, but when new groups are forming, the leadership isn't always clear. A multi-select leader field could be an alternative.

Maybe having a new "Group Leaders" field below the member count field that only offers names once they are actually in the member list. I suggest the member list gets reverted to be the same as other fields that have contact names.

> 
> As for marking attendance, that seems like a solid requirement for folks leading groups. I think there are about a dozen different ways to accomplish it, all with pros and cons. I don't know how using the same space to mark attendance would work past the most recent meeting. There would have to be some way of storing the information over time, which goes far beyond my comprehension of what would work well.

This whole concept of marking attendance is related to the meeting tracker issue #569

**Comment by mikeallbutt** [comment]
This tile could have a place to list potential group members. That way DT could be used to plan a new group. This might be a simple text box to write names and also another field that searches contacts in DT to add to a potential member group list.

**Comment by mikeallbutt** [comment]
What should one do when members are not currently attending? I wonder if DT offered a way to not the member as being inactive in this group. Maybe they are away for a time and will/might return at some stage. You want the group count to be accurate, but it is also useful to track who has been in a group over time too.

**Comment by micahmills** [comment]
@mikeallbutt I think this request is pretty similar to #569. Is there a reason to keep both issues open or can we combine them?

**Comment by mikeallbutt** [comment]
> @mikeallbutt I think this request is pretty similar to #569. Is there a reason to keep both issues open or can we combine them?

@micahmills yes this too is related to who is in a group, but what each issue is describing is IMO different.

**Comment by micahmills** [comment]
I added a comment in #569 to refer to this issue. For the sake of cleaning up the issues list I am going to close this, but it will still be visible from #569 when we build the meeting tracker.
