### ISSUE TITLE
Connections tile improvements

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#997]
As DT gets used more, some of the initial information that was first entered is no longer as relevant, but should not be removed.

I suggest that a way to indicate or hide inactive contacts and/or groups in the connections fields be implemented. This could be done by changing the color of the text of the name of the contact/group. 
Or grouping them into sub groups within the field depending on their status.

**Comment by mikeallbutt** [comment]
A contact who has been doing good work will have lots of people that have coached but no longer coach. How can DT help this contact focus on they are currently coaching when all their previous coached contacts are in the same field.

**Comment by mikeallbutt** [comment]
Another thing to improve the Connections tile is to add icons next to each field - like the app uses.

**Comment by corsacca** [comment]
This issue is further explored here: https://github.com/DiscipleTools/disciple-tools-theme/issues/1267
