### ISSUE TITLE
Special Characters on Contact Lists not displaying properly

### ISSUE THREAD

**Issue by mercivic** [DiscipleTools/disciple-tools-theme#999]
It looks like the contact list page does not handle HTML special chars properly. It is showing them in encoded format. This shows up when looking at the Contact List with contacts "Waiting to be accepted" and the language set to French.

![image](https://user-images.githubusercontent.com/2756587/86411831-b3b9dd80-bc8b-11ea-90a9-47c816e501f3.png)

**Comment by micahmills** [comment]
This is a problem because that string in the French translation uses the wrong apostrophe. We can fix that.

**Comment by corsacca** [comment]
Fixed the issue by not double escaping the values to be displayed: https://github.com/DiscipleTools/disciple-tools-theme/commit/8a05863b28bc3426940bf56d897db244efa87fe2
